// Build stamp — REGENERATED by scripts/stamp-build.mjs (prebuild hook) with the
// current commit's date + short SHA at build time. This committed fallback only
// exists so a bare checkout compiles; 'dev' means "not a stamped build".
// Served by the Worker at /api/build-info for the SEO health/drift detector:
// "is production actually running the code we shipped?"
export const BUILD_DATE = '2026-07-07';
export const BUILD_SHA = 'c298460';
