// GENERATED by scripts/gen-docs.mjs from content/changelog/*.md — DO NOT EDIT BY HAND.
// Edit the markdown, then run: npm run docs:build

export const CHANGELOG_CONTENT = {
 "2026-10-04": [
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "This release brings several weeks of work to the live site at once. Most of it is about getting material in without losing anything on the way: a folder keeps its shape, a file keeps its name, and an image dragged in from the web stops depending on the page it came from."
    }
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Folders, file names and web images",
   "inline": [
    {
     "t": "text",
     "v": "Folders, file names and web images"
    }
   ],
   "id": "2026-10-04-folders-file-names-and-web-images"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Drag a folder from your desktop onto a canvas and it becomes a cluster named after it, each folder inside it a nested cluster in the same shape, and every file a card in the cluster it was in. "
     },
     {
      "t": "strong",
      "v": "Add → Folder…",
      "children": [
       {
        "t": "text",
        "v": "Add → Folder…"
       }
      ]
     },
     {
      "t": "text",
      "v": " does the same from a picker, on a desktop browser. See "
     },
     {
      "t": "link",
      "v": "dropping a folder",
      "href": "/docs/clusters#dropping-a-folder",
      "children": [
       {
        "t": "text",
        "v": "dropping a folder"
       }
      ]
     },
     {
      "t": "text",
      "v": "."
     }
    ],
    [
     {
      "t": "text",
      "v": "It runs with a progress bar and a "
     },
     {
      "t": "strong",
      "v": "Cancel",
      "children": [
       {
        "t": "text",
        "v": "Cancel"
       }
      ]
     },
     {
      "t": "text",
      "v": " that keeps what has landed, and its Undo takes every cluster it made to Trash. One drop reads up to 500 files and makes up to 60 clusters; folders nested deeper than 6 levels merge into the deepest cluster rather than being left out. On the free plan a folder is counted before anything uploads — a card per file, one per cluster — and "
     },
     {
      "t": "strong",
      "v": "Add what fits",
      "children": [
       {
        "t": "text",
        "v": "Add what fits"
       }
      ]
     },
     {
      "t": "text",
      "v": " brings files in, in order, up to what fits, without ever making an empty cluster."
     }
    ],
    [
     {
      "t": "text",
      "v": "Images and videos uploaded from now on keep the names their files had. "
     },
     {
      "t": "code",
      "v": "diner_ext_dusk_04.jpg"
     },
     {
      "t": "text",
      "v": " stays that in list view and comes back out of Download under it, rather than as "
     },
     {
      "t": "code",
      "v": "download.jpg"
     },
     {
      "t": "text",
      "v": ". Audio, PDFs and attachments always kept theirs."
     }
    ],
    [
     {
      "t": "text",
      "v": "An image dragged in from another tab is kept as a copy in your workspace, counted against the cluster owner's storage like any upload. It shows at once from the page, then switches to the copy, so it no longer breaks when that page moves, its link expires or the picture goes behind a login. Web images placed before this are copied a few at a time when someone who can edit the cluster opens it. Past 25 MB, behind a login, or in a format not every browser can show, an image stays a link, as before."
     }
    ],
    [
     {
      "t": "text",
      "v": "A "
     },
     {
      "t": "code",
      "v": ".fountain"
     },
     {
      "t": "text",
      "v": " or "
     },
     {
      "t": "code",
      "v": ".fdx"
     },
     {
      "t": "text",
      "v": " file dropped or pasted in becomes a new script document, title page included, on every plan. It used to be treated as a plain file, which the free plan refused. An unfinished download ("
     },
     {
      "t": "code",
      "v": ".crdownload"
     },
     {
      "t": "text",
      "v": ", "
     },
     {
      "t": "code",
      "v": ".part"
     },
     {
      "t": "text",
      "v": ") is skipped with a note to drop it again once it has finished, and on the free plan a PureRef "
     },
     {
      "t": "code",
      "v": ".pur"
     },
     {
      "t": "text",
      "v": " file gets a plain answer instead of an upgrade offer."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Search reads documents",
   "inline": [
    {
     "t": "text",
     "v": "Search reads documents"
    }
   ],
   "id": "2026-10-04-search-reads-documents"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "code",
      "v": "⌘K"
     },
     {
      "t": "text",
      "v": " searches the words inside documents, not only their titles. A match shows the line it came from under "
     },
     {
      "t": "strong",
      "v": "Inside docs",
      "children": [
       {
        "t": "text",
        "v": "Inside docs"
       }
      ]
     },
     {
      "t": "text",
      "v": " and opens the document at that page. A document written before this is indexed the next time it, or anything in its cluster, is edited."
     }
    ],
    [
     {
      "t": "text",
      "v": "It also finds an image or video by the name its file was uploaded with — a photo nobody captioned turns up as "
     },
     {
      "t": "code",
      "v": "diner_ext_dusk_04.jpg"
     },
     {
      "t": "text",
      "v": " — in the palette and in list view's search across clusters."
     }
    ],
    [
     {
      "t": "text",
      "v": "A search with brackets in it, such as "
     },
     {
      "t": "code",
      "v": "Act II (rev)"
     },
     {
      "t": "text",
      "v": ", finds the words instead of failing and showing nothing."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Projects and Home",
   "inline": [
    {
     "t": "text",
     "v": "Projects and Home"
    }
   ],
   "id": "2026-10-04-projects-and-home"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "strong",
      "v": "New project",
      "children": [
       {
        "t": "text",
        "v": "New project"
       }
      ]
     },
     {
      "t": "text",
      "v": " — on Home, from the "
     },
     {
      "t": "strong",
      "v": "+",
      "children": [
       {
        "t": "text",
        "v": "+"
       }
      ]
     },
     {
      "t": "text",
      "v": " beside Clusters in the sidebar, or "
     },
     {
      "t": "code",
      "v": "⌘K"
     },
     {
      "t": "text",
      "v": " → New project — makes a cluster at the top of your workspace, beside Studio, and opens it. Before, every way of making a cluster put it inside whichever one was open, unnamed and unopened. The canvas tool and right-click still add one inside the current cluster."
     }
    ],
    [
     {
      "t": "strong",
      "v": "Home",
      "children": [
       {
        "t": "text",
        "v": "Home"
       }
      ]
     },
     {
      "t": "text",
      "v": " shows your projects: "
     },
     {
      "t": "strong",
      "v": "Jump back in",
      "children": [
       {
        "t": "text",
        "v": "Jump back in"
       }
      ]
     },
     {
      "t": "text",
      "v": " with the clusters you were last in, then Studio and every project, newest work first, on a panel over the workspace graph. "
     },
     {
      "t": "strong",
      "v": "Explore universe",
      "children": [
       {
        "t": "text",
        "v": "Explore universe"
       }
      ]
     },
     {
      "t": "text",
      "v": " puts the panel away. On a phone or a touch tablet, Home is the panel alone."
     }
    ],
    [
     {
      "t": "text",
      "v": "The sidebar opens on your projects, most recently worked on first, and "
     },
     {
      "t": "strong",
      "v": "All clusters",
      "children": [
       {
        "t": "text",
        "v": "All clusters"
       }
      ]
     },
     {
      "t": "text",
      "v": " at the bottom of its list opens the cluster you pick. It used to drop a link card onto the canvas, which on the free plan cost a card."
     }
    ],
    [
     {
      "t": "text",
      "v": "Cards get "
     },
     {
      "t": "strong",
      "v": "Move to cluster…",
      "children": [
       {
        "t": "text",
        "v": "Move to cluster…"
       }
      ]
     },
     {
      "t": "text",
      "v": " in the right-click menu, listing every cluster in the workspace, so material gathered on one can be filed into another without a drag. Its Undo puts both sides back."
     }
    ],
    [
     {
      "t": "text",
      "v": "Moving cards at the card limit could lose the ones the destination would not take. A move now takes off the source only what landed, and a move within one workspace never changes your count."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Audio, downloads and list view",
   "inline": [
    {
     "t": "text",
     "v": "Audio, downloads and list view"
    }
   ],
   "id": "2026-10-04-audio-downloads-and-list-view"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Audio cards draw a real waveform, decoded from the file as it uploads. It used to be an invented shape, so two copies of the same take drew two different ones. Older cards get theirs filled in while the cluster is open; files over 25 MB or longer than 10 minutes show a flat strip and still play."
     }
    ],
    [
     {
      "t": "text",
      "v": "Tempo and key are read from the filename — "
     },
     {
      "t": "code",
      "v": "SFL_120_Gmin_Loop_Piano.wav"
     },
     {
      "t": "text",
      "v": " — and are editable on the card, where what you type is never overwritten. Cover art is lifted from the file's own tag in MP3, M4A and FLAC."
     }
    ],
    [
     {
      "t": "text",
      "v": "In list view, a cluster that is mostly audio swaps Type and Size for "
     },
     {
      "t": "strong",
      "v": "Time",
      "children": [
       {
        "t": "text",
        "v": "Time"
       }
      ]
     },
     {
      "t": "text",
      "v": ", "
     },
     {
      "t": "strong",
      "v": "BPM",
      "children": [
       {
        "t": "text",
        "v": "BPM"
       }
      ]
     },
     {
      "t": "text",
      "v": ", "
     },
     {
      "t": "strong",
      "v": "Key",
      "children": [
       {
        "t": "text",
        "v": "Key"
       }
      ]
     },
     {
      "t": "text",
      "v": " and "
     },
     {
      "t": "strong",
      "v": "Format",
      "children": [
       {
        "t": "text",
        "v": "Format"
       }
      ]
     },
     {
      "t": "text",
      "v": ", all sortable, with key in circle-of-fifths order. A row's thumbnail plays it, "
     },
     {
      "t": "code",
      "v": "↑"
     },
     {
      "t": "text",
      "v": " "
     },
     {
      "t": "code",
      "v": "↓"
     },
     {
      "t": "text",
      "v": " and "
     },
     {
      "t": "code",
      "v": "Space"
     },
     {
      "t": "text",
      "v": " audition from the keyboard, and when a clip ends the next row starts on its own. On the canvas, "
     },
     {
      "t": "code",
      "v": "Enter"
     },
     {
      "t": "text",
      "v": " plays the selected clip and "
     },
     {
      "t": "code",
      "v": "L"
     },
     {
      "t": "text",
      "v": " loops it."
     }
    ],
    [
     {
      "t": "text",
      "v": "Audio and video cards get a download button, there for anyone who can see the card, including a visitor on a shared link. "
     },
     {
      "t": "strong",
      "v": "Download all",
      "children": [
       {
        "t": "text",
        "v": "Download all"
       }
      ]
     },
     {
      "t": "text",
      "v": " in list view, or "
     },
     {
      "t": "strong",
      "v": "Download",
      "children": [
       {
        "t": "text",
        "v": "Download"
       }
      ]
     },
     {
      "t": "text",
      "v": " on a selection, makes one zip of up to 500 files or 500 MB."
     }
    ],
    [
     {
      "t": "text",
      "v": "A "
     },
     {
      "t": "code",
      "v": ".flac"
     },
     {
      "t": "text",
      "v": " or "
     },
     {
      "t": "code",
      "v": ".aiff"
     },
     {
      "t": "text",
      "v": " dropped in Safari, and an "
     },
     {
      "t": "code",
      "v": ".mp3"
     },
     {
      "t": "text",
      "v": " pasted from the clipboard, arrive as audio cards, which the free plan takes, instead of as file cards it turned away."
     }
    ],
    [
     {
      "t": "text",
      "v": "A cluster set to list view opens as a list on a shared or published link too, with its search, sorting, playback and downloads. List view also keeps its header and selection bar in view while you scroll, "
     },
     {
      "t": "code",
      "v": "Shift"
     },
     {
      "t": "text",
      "v": "-click selects a range, and in a narrow pane its columns give way in order, the name last."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "New pages, and a treatment to start from",
   "inline": [
    {
     "t": "text",
     "v": "New pages, and a treatment to start from"
    }
   ],
   "id": "2026-10-04-new-pages-and-a-treatment-to-start-from"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Comparisons with "
     },
     {
      "t": "link",
      "v": "Eagle",
      "href": "/vs/eagle",
      "children": [
       {
        "t": "text",
        "v": "Eagle"
       }
      ]
     },
     {
      "t": "text",
      "v": " and "
     },
     {
      "t": "link",
      "v": "Google Drive",
      "href": "/vs/google-drive",
      "children": [
       {
        "t": "text",
        "v": "Google Drive"
       }
      ]
     },
     {
      "t": "text",
      "v": ": what each does better, and when to keep both. The list view docs gain a plain yes-and-no table for "
     },
     {
      "t": "link",
      "v": "using Clusters like a drive",
      "href": "/docs/clusters/list-view#can-i-use-clusters-like-google-drive",
      "children": [
       {
        "t": "text",
        "v": "using Clusters like a drive"
       }
      ]
     },
     {
      "t": "text",
      "v": "."
     }
    ],
    [
     {
      "t": "text",
      "v": "Five pages for production departments: "
     },
     {
      "t": "link",
      "v": "shared reference boards",
      "href": "/tools/shared-reference-board",
      "children": [
       {
        "t": "text",
        "v": "shared reference boards"
       }
      ]
     },
     {
      "t": "text",
      "v": " for art teams, the "
     },
     {
      "t": "link",
      "v": "director's treatment",
      "href": "/tools/directors-treatment",
      "children": [
       {
        "t": "text",
        "v": "director's treatment"
       }
      ]
     },
     {
      "t": "text",
      "v": ", "
     },
     {
      "t": "link",
      "v": "production design",
      "href": "/tools/production-design-mood-board",
      "children": [
       {
        "t": "text",
        "v": "production design"
       }
      ]
     },
     {
      "t": "text",
      "v": ", "
     },
     {
      "t": "link",
      "v": "costume design",
      "href": "/tools/costume-design-mood-board",
      "children": [
       {
        "t": "text",
        "v": "costume design"
       }
      ]
     },
     {
      "t": "text",
      "v": " and the "
     },
     {
      "t": "link",
      "v": "cinematography lookbook",
      "href": "/tools/cinematography-lookbook",
      "children": [
       {
        "t": "text",
        "v": "cinematography lookbook"
       }
      ]
     },
     {
      "t": "text",
      "v": "."
     }
    ],
    [
     {
      "t": "text",
      "v": "The director's treatment page hands you a document to start from. Press its button and, once you are signed in, a treatment — a cover, then a page for each section — is added to a cluster in your own workspace and opens. Until you change it, it is a template: it does not count toward your cards and search does not list it."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Plans and pricing",
   "inline": [
    {
     "t": "text",
     "v": "Plans and pricing"
    }
   ],
   "id": "2026-10-04-plans-and-pricing"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Pressing "
     },
     {
      "t": "strong",
      "v": "Get Creator",
      "children": [
       {
        "t": "text",
        "v": "Get Creator"
       }
      ]
     },
     {
      "t": "text",
      "v": " on "
     },
     {
      "t": "link",
      "v": "/pricing",
      "href": "/pricing",
      "children": [
       {
        "t": "text",
        "v": "/pricing"
       }
      ]
     },
     {
      "t": "text",
      "v": " before you have an account now carries through sign-in: once you are in, the offer opens with the monthly or annual plan you picked. The choice is kept on that device for 24 hours, and "
     },
     {
      "t": "strong",
      "v": "Start free",
      "children": [
       {
        "t": "text",
        "v": "Start free"
       }
      ]
     },
     {
      "t": "text",
      "v": " drops it."
     }
    ],
    [
     {
      "t": "text",
      "v": "An empty grid costs no cards, however many boxes it has: only filled boxes count, so a storyboard laid out but not yet drawn is free."
     }
    ],
    [
     {
      "t": "text",
      "v": "When a Creator plan or trial ends, nothing you made is deleted. A card placed on Creator that had not yet been counted could be taken off the canvas at the next sync; now a card over the limit stays where it is, and new cards wait until you are back under it."
     }
    ],
    [
     {
      "t": "text",
      "v": "Starting a trial no longer returns you to a page saying a payment was taken: it says nothing was charged, and when the first charge will be. About three days before it, an email gives the date and the amount, with a link to "
     },
     {
      "t": "strong",
      "v": "Settings → Plan & billing",
      "children": [
       {
        "t": "text",
        "v": "Settings → Plan & billing"
       }
      ]
     },
     {
      "t": "text",
      "v": "."
     }
    ],
    [
     {
      "t": "text",
      "v": "Plans, pricing and marketing pages stop calling clusters unlimited. There is no separate limit on clusters, but each one sits on its parent's canvas as a card, and on the free plan it counts as one of your 50."
     }
    ],
    [
     {
      "t": "text",
      "v": "The pricing page can be read without JavaScript, by search engines and assistants, and as Markdown at "
     },
     {
      "t": "link",
      "v": "/pricing.md",
      "href": "/pricing.md",
      "children": [
       {
        "t": "text",
        "v": "/pricing.md"
       }
      ]
     },
     {
      "t": "text",
      "v": ". The Milanote, Miro, Storyflow, Eagle and Google Drive comparisons, and the five professional pages, show "
     },
     {
      "t": "strong",
      "v": "What it costs",
      "children": [
       {
        "t": "text",
        "v": "What it costs"
       }
      ]
     },
     {
      "t": "text",
      "v": " on the page."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "API and MCP",
   "inline": [
    {
     "t": "text",
     "v": "API and MCP"
    }
   ],
   "id": "2026-10-04-api-and-mcp"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Uploads can keep a file's own name: pass "
     },
     {
      "t": "code",
      "v": "filename"
     },
     {
      "t": "text",
      "v": " to "
     },
     {
      "t": "code",
      "v": "POST /uploads"
     },
     {
      "t": "text",
      "v": " or the multipart complete call, and "
     },
     {
      "t": "code",
      "v": "file_name"
     },
     {
      "t": "text",
      "v": " on the card. "
     },
     {
      "t": "code",
      "v": "GET /images"
     },
     {
      "t": "text",
      "v": " returns it, and "
     },
     {
      "t": "code",
      "v": "GET /images/:key"
     },
     {
      "t": "text",
      "v": " sends it in "
     },
     {
      "t": "code",
      "v": "Content-Disposition"
     },
     {
      "t": "text",
      "v": "."
     }
    ],
    [
     {
      "t": "text",
      "v": "On the hosted MCP server, "
     },
     {
      "t": "code",
      "v": "upload_image"
     },
     {
      "t": "text",
      "v": " takes "
     },
     {
      "t": "code",
      "v": "file_name"
     },
     {
      "t": "text",
      "v": ", and "
     },
     {
      "t": "code",
      "v": "add_cards"
     },
     {
      "t": "text",
      "v": " creates "
     },
     {
      "t": "code",
      "v": "audio"
     },
     {
      "t": "text",
      "v": " and "
     },
     {
      "t": "code",
      "v": "pdf"
     },
     {
      "t": "text",
      "v": " cards — two kinds the REST API always accepted but the tool's schema left out."
     }
    ],
    [
     {
      "t": "text",
      "v": "Webhook deliveries no longer follow redirects: a "
     },
     {
      "t": "code",
      "v": "3xx"
     },
     {
      "t": "text",
      "v": " counts as a failed delivery, so point each webhook at its final address. The address is also checked again at every delivery. The importer still follows redirects, but every hop must pass the same public-host rule, and one that does not fails that item with "
     },
     {
      "t": "code",
      "v": "source_refused"
     },
     {
      "t": "text",
      "v": "."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Elsewhere",
   "inline": [
    {
     "t": "text",
     "v": "Elsewhere"
    }
   ],
   "id": "2026-10-04-elsewhere"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "With your system set to reduce motion, the canvas could not pan or zoom at all. It can now."
     }
    ],
    [
     {
      "t": "text",
      "v": "A photo whose upload never finished — the tab closed, or a phone sent the browser to the background — no longer spins on the board forever or counts toward your card limit. Once it clearly cannot finish, it is removed the next time someone who can edit the cluster opens it, with a note saying how many to add again."
     }
    ],
    [
     {
      "t": "text",
      "v": "Coming back to look at a board no longer means being asked to add to it every visit. The add-more prompts stop after a couple of visits to the same board, suggestions take turns at one per visit rather than one a minute, and the tour no longer starts over on a new device for an account that has already built something."
     }
    ],
    [
     {
      "t": "strong",
      "v": "Send feedback",
      "children": [
       {
        "t": "text",
        "v": "Send feedback"
       }
      ]
     },
     {
      "t": "text",
      "v": " opens on a one-tap topic, with words and a screenshot both optional and "
     },
     {
      "t": "strong",
      "v": "OK to email me about this",
      "children": [
       {
        "t": "text",
        "v": "OK to email me about this"
       }
      ]
     },
     {
      "t": "text",
      "v": " unticked. Two one-time questions join the return question — what best describes you, and, after you close an upgrade offer on the free plan, what is holding you back — and each shows what is sent with your answer before you send it. See "
     },
     {
      "t": "link",
      "v": "data and privacy",
      "href": "/docs/account/data-and-privacy",
      "children": [
       {
        "t": "text",
        "v": "data and privacy"
       }
      ]
     },
     {
      "t": "text",
      "v": "."
     }
    ],
    [
     {
      "t": "text",
      "v": "Several pages described things the product does not do, and now say what it does. Nothing files or tags a dropped image for you: automatic tagging reads text, never a picture, and marks what it applies as auto for you to confirm or remove. A palette is built with the eyedropper, a swatch at a time, rather than extracted from an image. "
     },
     {
      "t": "link",
      "v": "Soleil Scout",
      "href": "/scout",
      "children": [
       {
        "t": "text",
        "v": "Soleil Scout"
       }
      ]
     },
     {
      "t": "text",
      "v": " is invite-only and not running yet."
     }
    ]
   ]
  }
 ],
 "2026-08-26": [
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "Settings used to be two separate modals, and Theme and Display — both personal preferences — sat behind a button labelled "
    },
    {
     "t": "strong",
     "v": "Workspace",
     "children": [
      {
       "t": "text",
       "v": "Workspace"
      }
     ]
    },
    {
     "t": "text",
     "v": ". There is now one grouped Settings panel, and the personal settings live under a heading that describes them."
    }
   ]
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Uploading a profile picture and then closing the panel no longer discards it."
     }
    ],
    [
     {
      "t": "text",
      "v": "Two checkboxes in Settings silently ticked each other. They are independent now."
     }
    ],
    [
     {
      "t": "text",
      "v": "All 64 documentation pages are reachable from inside the app, and from each other — every page now links to this changelog too. They were public and indexed the whole time, but nothing in the product ever pointed at them."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Canvas",
   "inline": [
    {
     "t": "text",
     "v": "Canvas"
    }
   ],
   "id": "2026-08-26-canvas"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Every open cluster now puts "
     },
     {
      "t": "strong",
      "v": "its own name",
      "children": [
       {
        "t": "text",
        "v": "its own name"
       }
      ]
     },
     {
      "t": "text",
      "v": " in the browser tab. Previously every tab said the same thing, and it was not the cluster's name — which made a row of open clusters unreadable at exactly the point you had enough of them to need it."
     }
    ],
    [
     {
      "t": "text",
      "v": "Vertical scroll pans the canvas. On an infinite surface, scrolling up and down past the content was close to meaningless."
     }
    ],
    [
     {
      "t": "text",
      "v": "A video clip on a reference board behaves like the GIF it replaced: it loops quietly instead of presenting a player with controls you did not ask for."
     }
    ],
    [
     {
      "t": "text",
      "v": "Which right-click menu you got in the cluster panel depended on exactly where in the panel you clicked. One menu now, wherever you click."
     }
    ]
   ]
  }
 ],
 "2026-08-23": [
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "A long pass over screenplay documents. The short version: text you typed now survives everything you can do to it afterwards."
    }
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Screenplay",
   "inline": [
    {
     "t": "text",
     "v": "Screenplay"
    }
   ],
   "id": "2026-08-23-screenplay"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Pressing Enter on an empty script line could never insert a line. It can now."
     }
    ],
    [
     {
      "t": "text",
      "v": "Pagination counts what the renderers actually draw, rather than estimating from the source — so the page breaks you see are the page breaks you export."
     }
    ],
    [
     {
      "t": "text",
      "v": "Autocomplete no longer steals Tab, no longer clobbers the line you were on, and closes when you dismiss it."
     }
    ],
    [
     {
      "t": "text",
      "v": "Content survives paste, mode toggles, block joins and marks. Round-trips are honest in both directions."
     }
    ],
    [
     {
      "t": "text",
      "v": "The scene rail lines up with the gutters, and Dual dialogue can no longer be paired blind."
     }
    ],
    [
     {
      "t": "text",
      "v": "Find and replace reports what it actually did."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Split panes and docs",
   "inline": [
    {
     "t": "text",
     "v": "Split panes and docs"
    }
   ],
   "id": "2026-08-23-split-panes-and-docs"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Each side of a split now navigates independently, and a docked document survives the trip instead of being torn down."
     }
    ],
    [
     {
      "t": "text",
      "v": "A docked script used to hold the caret and leave the canvas beside it dead to the mouse. Both surfaces stay live."
     }
    ],
    [
     {
      "t": "text",
      "v": "The split's close control moved onto the divider, where nothing else competes for the space."
     }
    ],
    [
     {
      "t": "text",
      "v": "With two boards open, the toolbar tells you which board it means."
     }
    ],
    [
     {
      "t": "text",
      "v": "Document gutters stay correct when the canvas is zoomed."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Elsewhere",
   "inline": [
    {
     "t": "text",
     "v": "Elsewhere"
    }
   ],
   "id": "2026-08-23-elsewhere"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "On a shared board, the photos were the one thing you could not open. Fixed."
     }
    ],
    [
     {
      "t": "text",
      "v": "The press-and-hold gesture on mobile was invisible, so most people never found it. It announces itself now."
     }
    ]
   ]
  }
 ],
 "2026-08-16": [
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "The theme of the week was reversibility. Deleting something in Clusters has always shown an undo toast; a surprising number of operations quietly did not."
    }
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Undo",
   "inline": [
    {
     "t": "text",
     "v": "Undo"
    }
   ],
   "id": "2026-08-16-undo"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Tag operations were the most casually destructive clicks in the app. They undo now."
     }
    ],
    [
     {
      "t": "text",
      "v": "Document structure changes and note text edits are recoverable."
     }
    ],
    [
     {
      "t": "text",
      "v": "Board-level operations that run on the server get an inverse, or at minimum a confirmation step before they run."
     }
    ],
    [
     {
      "t": "text",
      "v": "Soft-deleted items existed in the database but nothing in the interface could reach them. Trash and recovery are reachable."
     }
    ],
    [
     {
      "t": "text",
      "v": "Undo could previously lie: split panes double-fired it, and a toast could undo something other than what it named."
     }
    ],
    [
     {
      "t": "text",
      "v": "The sketch pad had no undo at all — and pressing it there mangled the board behind the pad."
     }
    ],
    [
     {
      "t": "text",
      "v": "Version history is back, as a browser you restore from rather than a crutch for undo."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "The universe view",
   "inline": [
    {
     "t": "text",
     "v": "The universe view"
    }
   ],
   "id": "2026-08-16-the-universe-view"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Every board is now a real solar system, and the galaxy earned its own bar."
     }
    ],
    [
     {
      "t": "text",
      "v": "The view showed exactly 1,000 nodes and presented that as everything. It renders the whole set now."
     }
    ],
    [
     {
      "t": "text",
      "v": "Spiral arms emerge from the layout instead of being drawn on, so large workspaces look ragged the way real galaxies do."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Production schedule",
   "inline": [
    {
     "t": "text",
     "v": "Production schedule"
    }
   ],
   "id": "2026-08-16-production-schedule"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "A day is a rundown, not a column of hour buckets."
     }
    ],
    [
     {
      "t": "text",
      "v": "The calendar could show you a month but not a day. It can show you a day."
     }
    ],
    [
     {
      "t": "text",
      "v": "It could show you a date but never let you change it. Now it can."
     }
    ],
    [
     {
      "t": "text",
      "v": "Laying out a shoot was documented but not reachable from anywhere."
     }
    ],
    [
     {
      "t": "text",
      "v": "In light theme the calendar drew nothing at all."
     }
    ],
    [
     {
      "t": "text",
      "v": "Instead of mailing a fresh call sheet every night, the crew is told what changed."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Elsewhere",
   "inline": [
    {
     "t": "text",
     "v": "Elsewhere"
    }
   ],
   "id": "2026-08-16-elsewhere"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Opening a shared board on a phone landed you at 11% scale."
     }
    ],
    [
     {
      "t": "text",
      "v": "The free card allowance is now tracked per account, so it can be adjusted for new people without moving anyone else's."
     }
    ]
   ]
  }
 ],
 "2026-08-09": [
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "The largest week in the product's history, and almost all of it is surface you can build against."
    }
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "The API",
   "inline": [
    {
     "t": "text",
     "v": "The API"
    }
   ],
   "id": "2026-08-09-the-api"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "A public REST API at "
     },
     {
      "t": "code",
      "v": "/api/v1"
     },
     {
      "t": "text",
      "v": ", authenticated with personal access tokens you mint in Settings. A token acts as you, under exactly the permissions your account already has."
     }
    ],
    [
     {
      "t": "text",
      "v": "Multipart uploads for large files, bulk board operations, and resumable listing."
     }
    ],
    [
     {
      "t": "text",
      "v": "Service accounts — a credential that belongs to the workspace rather than to a person."
     }
    ],
    [
     {
      "t": "text",
      "v": "Webhooks that fire for app edits, bulk writes, video and file cards, and audit reads."
     }
    ],
    [
     {
      "t": "text",
      "v": "Identifiers, custom properties, delta reads, whole-board-tree reads, and OMC export."
     }
    ],
    [
     {
      "t": "text",
      "v": "Import: bring reference in from wherever it currently lives."
     }
    ],
    [
     {
      "t": "text",
      "v": "Arrange: named layout algorithms and a coordinate system you can build with."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "MCP, for AI agents",
   "inline": [
    {
     "t": "text",
     "v": "MCP, for AI agents"
    }
   ],
   "id": "2026-08-09-mcp-for-ai-agents"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "An MCP server, available both as an npm package and hosted at a URL you paste into a client. One registry serves both transports."
     }
    ],
    [
     {
      "t": "text",
      "v": "OAuth 2.1, so connecting an assistant is a button rather than a copied secret, with a panel that shows you what is connected."
     }
    ],
    [
     {
      "t": "text",
      "v": "Published to the MCP Registry as "
     },
     {
      "t": "code",
      "v": "com.soleilpictures/clusters"
     },
     {
      "t": "text",
      "v": "."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Documentation",
   "inline": [
    {
     "t": "text",
     "v": "Documentation"
    }
   ],
   "id": "2026-08-09-documentation"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "A public documentation site at "
     },
     {
      "t": "link",
      "v": "/docs",
      "href": "/docs",
      "children": [
       {
        "t": "text",
        "v": "/docs"
       }
      ]
     },
     {
      "t": "text",
      "v": ", generated from source so it cannot describe a version of the product that no longer exists."
     }
    ],
    [
     {
      "t": "text",
      "v": "Every page has a raw Markdown twin — append "
     },
     {
      "t": "code",
      "v": ".md"
     },
     {
      "t": "text",
      "v": " to any documentation URL — plus "
     },
     {
      "t": "link",
      "v": "/llms.txt",
      "href": "/llms.txt",
      "children": [
       {
        "t": "text",
        "v": "/llms.txt"
       }
      ]
     },
     {
      "t": "text",
      "v": " for agents that want the index."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Canvas and images",
   "inline": [
    {
     "t": "text",
     "v": "Canvas and images"
    }
   ],
   "id": "2026-08-09-canvas-and-images"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Dropping a big batch of photos gives you a block, not a 5,200-pixel strip."
     }
    ],
    [
     {
      "t": "text",
      "v": "Image cards serve the smaller rendition when the larger one is not needed."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Soleil Scout",
   "inline": [
    {
     "t": "text",
     "v": "Soleil Scout"
    }
   ],
   "id": "2026-08-09-soleil-scout"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Text photos from set straight onto a canvas, with no app to open. Instant session links, multi-card deep links, and a Settings tab that connects a phone to an account you already have."
     }
    ]
   ]
  }
 ],
 "2026-08-02": [
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "A quiet week."
    }
   ]
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Arrows have a draggable midpoint dot. The automatic routing is still the default; this is for the cases where you want the curve to go somewhere else."
     }
    ],
    [
     {
      "t": "text",
      "v": "The just-in-time tips that teach one feature at a time were disappearing before you could act on them. They now stay long enough to be useful."
     }
    ]
   ]
  }
 ],
 "2026-07-26": [
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "The tour that ran before you had done anything is gone. In its place, a tip appears when you are about to need the feature it describes — and only then."
     }
    ],
    [
     {
      "t": "text",
      "v": "New accounts are asked what they are working on rather than walked through desktop mechanics they have not needed yet."
     }
    ],
    [
     {
      "t": "text",
      "v": "Zooming an image in the mobile viewer could crash Safari on iOS by running the device out of memory. Image tiers are capped on mobile so it does not."
     }
    ],
    [
     {
      "t": "text",
      "v": "Collaborative notes recover on their own from a class of corruption that previously required reloading, and a batch of rich-text editor errors are fixed."
     }
    ]
   ]
  }
 ],
 "2026-07-19": [
  {
   "type": "heading",
   "depth": 3,
   "text": "Collaboration is free",
   "inline": [
    {
     "t": "text",
     "v": "Collaboration is free"
    }
   ],
   "id": "2026-07-19-collaboration-is-free"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Editors do not cost anything. Capacity does. Whoever owns a cluster carries its card and storage allowance, and everyone they invite can edit without needing a plan of their own."
     }
    ],
    [
     {
      "t": "text",
      "v": "Invite links: send one link instead of collecting addresses, and see it when somebody joins."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Mobile",
   "inline": [
    {
     "t": "text",
     "v": "Mobile"
    }
   ],
   "id": "2026-07-19-mobile"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "A photos-first start on phones — two steps, camera roll first, because that is what a phone is good for."
     }
    ],
    [
     {
      "t": "text",
      "v": "Sign-in fields are 16 pixels on touch devices, which stops iOS zooming the page the moment you tap one. This covers iPad as well."
     }
    ],
    [
     {
      "t": "text",
      "v": "Starting on a phone and continuing on a computer is a handoff the product knows about rather than something you improvise."
     }
    ],
    [
     {
      "t": "text",
      "v": "The text-selection bubble in documents appears on any touch-capable device, not just narrow ones."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Production schedule",
   "inline": [
    {
     "t": "text",
     "v": "Production schedule"
    }
   ],
   "id": "2026-07-19-production-schedule"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Clicking into a day opens a peek, and the peek is the editing surface. The grid itself stays read-only."
     }
    ],
    [
     {
      "t": "text",
      "v": "Row types are legible at every zoom level, with honest overflow badges instead of clipped text."
     }
    ]
   ]
  }
 ],
 "2026-07-12": [
  {
   "type": "heading",
   "depth": 3,
   "text": "The schedule is a calendar now",
   "inline": [
    {
     "t": "text",
     "v": "The schedule is a calendar now"
    }
   ],
   "id": "2026-07-12-the-schedule-is-a-calendar-now"
  },
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "Production schedules used to be an abstract grid. They sit on real dates."
    }
   ]
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Create, switch and navigate months; jump to a date from the header title."
     }
    ],
    [
     {
      "t": "text",
      "v": "A Day and Hour peek that zooms into one date without leaving the view."
     }
    ],
    [
     {
      "t": "text",
      "v": "Drop, paste or add content directly into a slot."
     }
    ],
    [
     {
      "t": "text",
      "v": "Inline breakdowns, and the ability to graft one schedule into another."
     }
    ],
    [
     {
      "t": "text",
      "v": "Two-tier level-of-detail so a dense month stays readable."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Cluster Browser",
   "inline": [
    {
     "t": "text",
     "v": "Cluster Browser"
    }
   ],
   "id": "2026-07-12-cluster-browser"
  },
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "List view was rebuilt as something you can actually work in."
    }
   ]
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Table and Gallery modes, with real previews for every card kind."
     }
    ],
    [
     {
      "t": "text",
      "v": "Sort, filter and search across the cluster."
     }
    ],
    [
     {
      "t": "text",
      "v": "Live presence, so you can see who else is in there."
     }
    ],
    [
     {
      "t": "text",
      "v": "Drag files straight into list mode."
     }
    ],
    [
     {
      "t": "text",
      "v": "A detail popout, and linked grids grouped together."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Grids and images",
   "inline": [
    {
     "t": "text",
     "v": "Grids and images"
    }
   ],
   "id": "2026-07-12-grids-and-images"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Full image controls in grid cells: fit, reposition, zoom, and the same non-destructive photo adjustments as anywhere else."
     }
    ],
    [
     {
      "t": "text",
      "v": "A genuinely full-screen cell lightbox, with download."
     }
    ],
    [
     {
      "t": "text",
      "v": "Background colour on grid cells, matching note colours."
     }
    ],
    [
     {
      "t": "text",
      "v": "A pop-out cell menu, so a tiny cell can still reach every insert and split option."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Elsewhere",
   "inline": [
    {
     "t": "text",
     "v": "Elsewhere"
    }
   ],
   "id": "2026-07-12-elsewhere"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Custom cluster thumbnails — right-click a cluster, upload an image, crop and reposition it, or reset back to the automatic one."
     }
    ],
    [
     {
      "t": "link",
      "v": "/explore",
      "href": "/explore",
      "children": [
       {
        "t": "text",
        "v": "/explore"
       }
      ]
     },
     {
      "t": "text",
      "v": " gains search, sort and topic filters over the public catalogue."
     }
    ],
    [
     {
      "t": "text",
      "v": "Right-click menus are grouped into labelled sections, consistently across all three of them."
     }
    ],
    [
     {
      "t": "text",
      "v": "Creating a linked cluster from the right-click menu lands it where you clicked, instead of a fixed drop zone."
     }
    ],
    [
     {
      "t": "text",
      "v": "Typing "
     },
     {
      "t": "code",
      "v": "- "
     },
     {
      "t": "text",
      "v": " in a note stays literal, and toolbar bullets get visible markers."
     }
    ],
    [
     {
      "t": "text",
      "v": "Double-click a group label to rename it in place."
     }
    ],
    [
     {
      "t": "text",
      "v": "Sessions survive properly — the daily handoff used to invalidate refresh tokens and send everyone back to a one-time code."
     }
    ]
   ]
  }
 ]
};
