// GENERATED by scripts/gen-docs.mjs from content/changelog/*.md — DO NOT EDIT BY HAND.
// Edit the markdown, then run: npm run docs:build

export const CHANGELOG_META = {
  "path": "/changelog",
  "title": "Changelog — Soleil Clusters",
  "description": "Every user-visible change to Soleil Clusters, newest first, with dates. Updated weekly.",
  "h1": "Changelog",
  "answer": "Soleil Clusters ships continuously; this page lists every user-visible change, newest first, with the date it went live. Each entry covers one week. Fixes and additions are described in the same list rather than split apart, because the distinction rarely matters to the person reading."
};

export const CHANGELOG_ENTRIES = [
  {
    "date": "2026-08-26",
    "anchor": "2026-08-26",
    "title": "Settings you can find, and a tab that says which cluster",
    "summary": "Settings collapse from two modals into one grouped panel, every open cluster puts its own name in the browser tab, and the documentation is finally reachable from inside the app.",
    "headings": []
  },
  {
    "date": "2026-08-23",
    "anchor": "2026-08-23",
    "title": "Screenplay mode grows up, and split panes stop fighting each other",
    "summary": "Pagination that counts what the renderers actually draw, autocomplete that stops stealing Tab, and split panes where each side navigates itself without dragging the other along.",
    "headings": []
  },
  {
    "date": "2026-08-16",
    "anchor": "2026-08-16",
    "title": "Undo, everywhere — and a universe that does not stop at a thousand",
    "summary": "About nineteen operations that used to be permanent now undo, version history comes back as a restore browser, and the universe view renders every board instead of the first thousand.",
    "headings": []
  },
  {
    "date": "2026-08-09",
    "anchor": "2026-08-09",
    "title": "A public API, an MCP server, and the documentation to go with them",
    "summary": "Clusters becomes programmable — a REST API at /api/v1 with personal access tokens, a hosted MCP server for AI agents, OAuth 2.1, webhooks, service accounts, and a public documentation site.",
    "headings": []
  },
  {
    "date": "2026-08-02",
    "anchor": "2026-08-02",
    "title": "Bend an arrow by hand",
    "summary": "Arrows get a draggable midpoint so you can shape the curve yourself, and the just-in-time tips stay on screen long enough to act on.",
    "headings": []
  },
  {
    "date": "2026-07-26",
    "anchor": "2026-07-26",
    "title": "The tour gets out of the way",
    "summary": "The upfront feature tour is replaced by tips that appear when the feature is actually in front of you, and the mobile viewer stops crashing iOS Safari on zoom.",
    "headings": []
  },
  {
    "date": "2026-07-19",
    "anchor": "2026-07-19",
    "title": "Editors are free, and the schedule opens where you clicked",
    "summary": "Collaboration stops being the thing you pay for — editors are free and capacity is what is billed — plus invite links, a photos-first mobile start, and a schedule you edit by clicking into a day.",
    "headings": []
  },
  {
    "date": "2026-07-12",
    "anchor": "2026-07-12",
    "title": "The schedule becomes a calendar, and list view becomes a browser",
    "summary": "Production schedules move onto real dates with a day-level peek, list view is rebuilt as a Cluster Browser with table and gallery modes, and grids gain full image controls.",
    "headings": []
  }
];

// The newest entry's date. The sitemap's lastmod for /changelog and the RSS
// lastBuildDate both read this — it is the one page on the site whose lastmod
// is unambiguously honest, since the date IS the content.
export const CHANGELOG_LATEST = CHANGELOG_ENTRIES[0]?.date || null;

// True for anything shaped like a changelog URL, so the Worker can serve a real
// 404 for /changelog/nope rather than a soft-404 carrying homepage content.
// Does NOT match /changelog.md or /changelog.xml — those are static assets that
// env.ASSETS answers long before this is consulted.
export function isChangelogPath(pathname) {
  return /^\/changelog(?:\/|$)/i.test(String(pathname || ''));
}
