// GENERATED by scripts/gen-docs.mjs from content/changelog/*.md — DO NOT EDIT BY HAND.
// Edit the markdown, then run: npm run docs:build

export const CHANGELOG_CONTENT = {
 "2026-08-26": [
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Every open cluster now puts "
     },
     {
      "t": "strong",
      "v": "its own name",
      "children": [
       {
        "t": "text",
        "v": "its own name"
       }
      ]
     },
     {
      "t": "text",
      "v": " in the browser tab. Previously every tab said the same thing, and it was not the cluster's name — which made a row of open clusters unreadable at exactly the moment you had enough of them to need it."
     }
    ],
    [
     {
      "t": "text",
      "v": "A video clip on a reference board behaves like the GIF it replaced: it loops quietly instead of presenting a player with controls you did not ask for."
     }
    ],
    [
     {
      "t": "text",
      "v": "Which right-click menu you got in the cluster panel depended on exactly where in the panel you clicked. One menu now, wherever you click."
     }
    ]
   ]
  }
 ],
 "2026-08-23": [
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "A long pass over screenplay documents. The short version: text you typed now survives everything you can do to it afterwards."
    }
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Screenplay",
   "inline": [
    {
     "t": "text",
     "v": "Screenplay"
    }
   ],
   "id": "2026-08-23-screenplay"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Pressing Enter on an empty script line could never insert a line. It can now."
     }
    ],
    [
     {
      "t": "text",
      "v": "Pagination counts what the renderers actually draw, rather than estimating from the source — so the page breaks you see are the page breaks you export."
     }
    ],
    [
     {
      "t": "text",
      "v": "Autocomplete no longer steals Tab, no longer clobbers the line you were on, and closes when you dismiss it."
     }
    ],
    [
     {
      "t": "text",
      "v": "Content survives paste, mode toggles, block joins and marks. Round-trips are honest in both directions."
     }
    ],
    [
     {
      "t": "text",
      "v": "The scene rail lines up with the gutters, and Dual dialogue can no longer be paired blind."
     }
    ],
    [
     {
      "t": "text",
      "v": "Find and replace reports what it actually did."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Split panes and docs",
   "inline": [
    {
     "t": "text",
     "v": "Split panes and docs"
    }
   ],
   "id": "2026-08-23-split-panes-and-docs"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Each side of a split now navigates independently, and a docked document survives the trip instead of being torn down."
     }
    ],
    [
     {
      "t": "text",
      "v": "A docked script used to hold the caret and leave the canvas beside it dead to the mouse. Both surfaces stay live."
     }
    ],
    [
     {
      "t": "text",
      "v": "The split's close control moved onto the divider, where nothing else competes for the space."
     }
    ],
    [
     {
      "t": "text",
      "v": "With two boards open, the toolbar tells you which board it means."
     }
    ],
    [
     {
      "t": "text",
      "v": "Document gutters stay correct when the canvas is zoomed."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Elsewhere",
   "inline": [
    {
     "t": "text",
     "v": "Elsewhere"
    }
   ],
   "id": "2026-08-23-elsewhere"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "On a shared board, the photos were the one thing you could not open. Fixed."
     }
    ],
    [
     {
      "t": "text",
      "v": "The press-and-hold gesture on mobile was invisible, so most people never found it. It announces itself now."
     }
    ]
   ]
  }
 ],
 "2026-08-16": [
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "The theme of the week was reversibility. Deleting something in Clusters has always shown an undo toast; a surprising number of operations quietly did not."
    }
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Undo",
   "inline": [
    {
     "t": "text",
     "v": "Undo"
    }
   ],
   "id": "2026-08-16-undo"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Tag operations were the most casually destructive clicks in the app. They undo now."
     }
    ],
    [
     {
      "t": "text",
      "v": "Document structure changes and note text edits are recoverable."
     }
    ],
    [
     {
      "t": "text",
      "v": "Board-level operations that run on the server get an inverse, or at minimum a confirmation step before they run."
     }
    ],
    [
     {
      "t": "text",
      "v": "Soft-deleted items existed in the database but nothing in the interface could reach them. Trash and recovery are reachable."
     }
    ],
    [
     {
      "t": "text",
      "v": "Undo could previously lie: split panes double-fired it, and a toast could undo something other than what it named."
     }
    ],
    [
     {
      "t": "text",
      "v": "The sketch pad had no undo at all — and pressing it there mangled the board behind the pad."
     }
    ],
    [
     {
      "t": "text",
      "v": "Version history is back, as a browser you restore from rather than a crutch for undo."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "The universe view",
   "inline": [
    {
     "t": "text",
     "v": "The universe view"
    }
   ],
   "id": "2026-08-16-the-universe-view"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Every board is now a real solar system, and the galaxy earned its own bar."
     }
    ],
    [
     {
      "t": "text",
      "v": "The view showed exactly 1,000 nodes and presented that as everything. It renders the whole set now."
     }
    ],
    [
     {
      "t": "text",
      "v": "Spiral arms emerge from the layout instead of being drawn on, so large workspaces look ragged the way real galaxies do."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Production schedule",
   "inline": [
    {
     "t": "text",
     "v": "Production schedule"
    }
   ],
   "id": "2026-08-16-production-schedule"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "A day is a rundown, not a column of hour buckets."
     }
    ],
    [
     {
      "t": "text",
      "v": "The calendar could show you a month but not a day. It can show you a day."
     }
    ],
    [
     {
      "t": "text",
      "v": "It could show you a date but never let you change it. Now it can."
     }
    ],
    [
     {
      "t": "text",
      "v": "Laying out a shoot was documented but not reachable from anywhere."
     }
    ],
    [
     {
      "t": "text",
      "v": "In light theme the calendar drew nothing at all."
     }
    ],
    [
     {
      "t": "text",
      "v": "Instead of mailing a fresh call sheet every night, the crew is told what changed."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Elsewhere",
   "inline": [
    {
     "t": "text",
     "v": "Elsewhere"
    }
   ],
   "id": "2026-08-16-elsewhere"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Opening a shared board on a phone landed you at 11% scale."
     }
    ],
    [
     {
      "t": "text",
      "v": "The free card allowance is now tracked per account, so it can be adjusted for new people without moving anyone else's."
     }
    ]
   ]
  }
 ],
 "2026-08-09": [
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "The largest week in the product's history, and almost all of it is surface you can build against."
    }
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "The API",
   "inline": [
    {
     "t": "text",
     "v": "The API"
    }
   ],
   "id": "2026-08-09-the-api"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "A public REST API at "
     },
     {
      "t": "code",
      "v": "/api/v1"
     },
     {
      "t": "text",
      "v": ", authenticated with personal access tokens you mint in Settings. A token acts as you, under exactly the permissions your account already has."
     }
    ],
    [
     {
      "t": "text",
      "v": "Multipart uploads for large files, bulk board operations, and resumable listing."
     }
    ],
    [
     {
      "t": "text",
      "v": "Service accounts — a credential that belongs to the workspace rather than to a person."
     }
    ],
    [
     {
      "t": "text",
      "v": "Webhooks that fire for app edits, bulk writes, video and file cards, and audit reads."
     }
    ],
    [
     {
      "t": "text",
      "v": "Identifiers, custom properties, delta reads, whole-board-tree reads, and OMC export."
     }
    ],
    [
     {
      "t": "text",
      "v": "Import: bring reference in from wherever it currently lives."
     }
    ],
    [
     {
      "t": "text",
      "v": "Arrange: named layout algorithms and a coordinate system you can build with."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "MCP, for AI agents",
   "inline": [
    {
     "t": "text",
     "v": "MCP, for AI agents"
    }
   ],
   "id": "2026-08-09-mcp-for-ai-agents"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "An MCP server, available both as an npm package and hosted at a URL you paste into a client. One registry serves both transports."
     }
    ],
    [
     {
      "t": "text",
      "v": "OAuth 2.1, so connecting an assistant is a button rather than a copied secret, with a panel that shows you what is connected."
     }
    ],
    [
     {
      "t": "text",
      "v": "Published to the MCP Registry as "
     },
     {
      "t": "code",
      "v": "com.soleilpictures/clusters"
     },
     {
      "t": "text",
      "v": "."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Documentation",
   "inline": [
    {
     "t": "text",
     "v": "Documentation"
    }
   ],
   "id": "2026-08-09-documentation"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "A public documentation site at "
     },
     {
      "t": "link",
      "v": "/docs",
      "href": "/docs",
      "children": [
       {
        "t": "text",
        "v": "/docs"
       }
      ]
     },
     {
      "t": "text",
      "v": ", generated from source so it cannot describe a version of the product that no longer exists."
     }
    ],
    [
     {
      "t": "text",
      "v": "Every page has a raw Markdown twin — append "
     },
     {
      "t": "code",
      "v": ".md"
     },
     {
      "t": "text",
      "v": " to any documentation URL — plus "
     },
     {
      "t": "link",
      "v": "/llms.txt",
      "href": "/llms.txt",
      "children": [
       {
        "t": "text",
        "v": "/llms.txt"
       }
      ]
     },
     {
      "t": "text",
      "v": " for agents that want the index."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Canvas and images",
   "inline": [
    {
     "t": "text",
     "v": "Canvas and images"
    }
   ],
   "id": "2026-08-09-canvas-and-images"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Dropping a folder of photos gives you a block, not a 5,200-pixel strip."
     }
    ],
    [
     {
      "t": "text",
      "v": "Image cards serve the smaller rendition when the larger one is not needed."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Soleil Scout",
   "inline": [
    {
     "t": "text",
     "v": "Soleil Scout"
    }
   ],
   "id": "2026-08-09-soleil-scout"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Text photos from set straight onto a canvas, with no app to open. Instant session links, multi-card deep links, and a Settings tab that connects a phone to an account you already have."
     }
    ]
   ]
  }
 ],
 "2026-08-02": [
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "A quiet week."
    }
   ]
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Arrows have a draggable midpoint dot. The automatic routing is still the default; this is for the cases where you want the curve to go somewhere else."
     }
    ],
    [
     {
      "t": "text",
      "v": "The just-in-time tips that teach one feature at a time were disappearing before you could act on them. They now stay long enough to be useful."
     }
    ]
   ]
  }
 ],
 "2026-07-26": [
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "The tour that ran before you had done anything is gone. In its place, a tip appears when you are about to need the feature it describes — and only then."
     }
    ],
    [
     {
      "t": "text",
      "v": "New accounts are asked what they are working on rather than walked through desktop mechanics they have not needed yet."
     }
    ],
    [
     {
      "t": "text",
      "v": "Zooming an image in the mobile viewer could crash Safari on iOS by running the device out of memory. Image tiers are capped on mobile so it does not."
     }
    ],
    [
     {
      "t": "text",
      "v": "Collaborative notes recover on their own from a class of corruption that previously required reloading, and a batch of rich-text editor errors are fixed."
     }
    ]
   ]
  }
 ],
 "2026-07-19": [
  {
   "type": "heading",
   "depth": 3,
   "text": "Collaboration is free",
   "inline": [
    {
     "t": "text",
     "v": "Collaboration is free"
    }
   ],
   "id": "2026-07-19-collaboration-is-free"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Editors do not cost anything. Capacity does. Whoever owns a cluster carries its card and storage allowance, and everyone they invite can edit without needing a plan of their own."
     }
    ],
    [
     {
      "t": "text",
      "v": "Invite links: send one link instead of collecting addresses, and see it when somebody joins."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Mobile",
   "inline": [
    {
     "t": "text",
     "v": "Mobile"
    }
   ],
   "id": "2026-07-19-mobile"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "A photos-first start on phones — two steps, camera roll first, because that is what a phone is good for."
     }
    ],
    [
     {
      "t": "text",
      "v": "Sign-in fields are 16 pixels on touch devices, which stops iOS zooming the page the moment you tap one. This covers iPad as well."
     }
    ],
    [
     {
      "t": "text",
      "v": "Starting on a phone and continuing on a computer is a handoff the product knows about rather than something you improvise."
     }
    ],
    [
     {
      "t": "text",
      "v": "The text-selection bubble in documents appears on any touch-capable device, not just narrow ones."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Production schedule",
   "inline": [
    {
     "t": "text",
     "v": "Production schedule"
    }
   ],
   "id": "2026-07-19-production-schedule"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Clicking into a day opens a peek, and the peek is the editing surface. The grid itself stays read-only."
     }
    ],
    [
     {
      "t": "text",
      "v": "Row types are legible at every zoom level, with honest overflow badges instead of clipped text."
     }
    ]
   ]
  }
 ],
 "2026-07-12": [
  {
   "type": "heading",
   "depth": 3,
   "text": "The schedule is a calendar now",
   "inline": [
    {
     "t": "text",
     "v": "The schedule is a calendar now"
    }
   ],
   "id": "2026-07-12-the-schedule-is-a-calendar-now"
  },
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "Production schedules used to be an abstract grid. They sit on real dates."
    }
   ]
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Create, switch and navigate months; jump to a date from the header title."
     }
    ],
    [
     {
      "t": "text",
      "v": "A Day and Hour peek that zooms into one date without leaving the view."
     }
    ],
    [
     {
      "t": "text",
      "v": "Drop, paste or add content directly into a slot."
     }
    ],
    [
     {
      "t": "text",
      "v": "Inline breakdowns, and the ability to graft one schedule into another."
     }
    ],
    [
     {
      "t": "text",
      "v": "Two-tier level-of-detail so a dense month stays readable."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Cluster Browser",
   "inline": [
    {
     "t": "text",
     "v": "Cluster Browser"
    }
   ],
   "id": "2026-07-12-cluster-browser"
  },
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "List view was rebuilt as something you can actually work in."
    }
   ]
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Table and Gallery modes, with real previews for every card kind."
     }
    ],
    [
     {
      "t": "text",
      "v": "Sort, filter and search across the cluster."
     }
    ],
    [
     {
      "t": "text",
      "v": "Live presence, so you can see who else is in there."
     }
    ],
    [
     {
      "t": "text",
      "v": "Drag files straight into list mode."
     }
    ],
    [
     {
      "t": "text",
      "v": "A detail popout, and linked grids grouped together."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Grids and images",
   "inline": [
    {
     "t": "text",
     "v": "Grids and images"
    }
   ],
   "id": "2026-07-12-grids-and-images"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Full image controls in grid cells: fit, reposition, zoom, and the same non-destructive photo adjustments as anywhere else."
     }
    ],
    [
     {
      "t": "text",
      "v": "A genuinely full-screen cell lightbox, with download."
     }
    ],
    [
     {
      "t": "text",
      "v": "Background colour on grid cells, matching note colours."
     }
    ],
    [
     {
      "t": "text",
      "v": "A pop-out cell menu, so a tiny cell can still reach every insert and split option."
     }
    ]
   ]
  },
  {
   "type": "heading",
   "depth": 3,
   "text": "Elsewhere",
   "inline": [
    {
     "t": "text",
     "v": "Elsewhere"
    }
   ],
   "id": "2026-07-12-elsewhere"
  },
  {
   "type": "list",
   "ordered": false,
   "items": [
    [
     {
      "t": "text",
      "v": "Custom cluster thumbnails — right-click a cluster, upload an image, crop and reposition it, or reset back to the automatic one."
     }
    ],
    [
     {
      "t": "link",
      "v": "/explore",
      "href": "/explore",
      "children": [
       {
        "t": "text",
        "v": "/explore"
       }
      ]
     },
     {
      "t": "text",
      "v": " gains search, sort and topic filters over the public catalogue."
     }
    ],
    [
     {
      "t": "text",
      "v": "Right-click menus are grouped into labelled sections, consistently across all three of them."
     }
    ],
    [
     {
      "t": "text",
      "v": "Creating a linked cluster from the right-click menu lands it where you clicked, instead of a fixed drop zone."
     }
    ],
    [
     {
      "t": "text",
      "v": "Typing "
     },
     {
      "t": "code",
      "v": "- "
     },
     {
      "t": "text",
      "v": " in a note stays literal, and toolbar bullets get visible markers."
     }
    ],
    [
     {
      "t": "text",
      "v": "Double-click a group label to rename it in place."
     }
    ],
    [
     {
      "t": "text",
      "v": "Sessions survive properly — the daily handoff used to invalidate refresh tokens and send everyone back to a one-time code."
     }
    ]
   ]
  }
 ]
};
