// GENERATED by scripts/gen-docs.mjs from content/templates/*.md — DO NOT EDIT BY HAND.
// Edit the markdown, then run: npm run docs:build

export const CURATED_TEMPLATES = {
 "casting-board-template": {
  "path": "/templates/casting-board-template",
  "name": "Casting board template",
  "preset": "contact-sheet-3x3",
  "hints": [
   "LEAD",
   "LEAD",
   "LEAD",
   "SUPPORTING",
   "SUPPORTING",
   "SUPPORTING",
   "BACKGROUND",
   "BACKGROUND",
   "BACKGROUND"
  ]
 },
 "location-scout-template": {
  "path": "/templates/location-scout-template",
  "name": "Location scout template",
  "preset": "contact-sheet-3x3",
  "hints": [
   "LOCATION A — WIDE",
   "A — DETAIL",
   "A — LIGHT",
   "LOCATION B — WIDE",
   "B — DETAIL",
   "B — LIGHT",
   "LOCATION C — WIDE",
   "C — DETAIL",
   "C — LIGHT"
  ]
 },
 "shot-list-template": {
  "path": "/templates/shot-list-template",
  "name": "Shot list template",
  "preset": "db-row-1-3",
  "hints": [
   "SHOT + LENS",
   "FRAME",
   "MOVEMENT",
   "NOTES"
  ]
 },
 "storyboard-template": {
  "path": "/templates/storyboard-template",
  "name": "Storyboard template",
  "preset": "storyboard-1-2",
  "hints": [
   "ESTABLISHING",
   "ACTION",
   "REACTION"
  ]
 },
 "video-storyboard-template": {
  "path": "/templates/video-storyboard-template",
  "name": "Video storyboard template",
  "preset": "4up",
  "hints": [
   "HOOK",
   "BEAT 2",
   "BEAT 3",
   "END CARD"
  ]
 },
 "before-and-after-template": {
  "path": "/templates/before-and-after-template",
  "name": "Before and after template",
  "preset": "split-2",
  "hints": [
   "BEFORE",
   "AFTER"
  ]
 },
 "contact-sheet-template": {
  "path": "/templates/contact-sheet-template",
  "name": "Contact sheet template",
  "preset": "contact-sheet-3x3"
 },
 "product-lineup-template": {
  "path": "/templates/product-lineup-template",
  "name": "Product lineup template",
  "preset": "4up",
  "hints": [
   "FRONT",
   "SIDE",
   "DETAIL",
   "IN USE"
  ]
 },
 "brand-board-template": {
  "path": "/templates/brand-board-template",
  "name": "Brand board template",
  "preset": "2x2",
  "hints": [
   "LOGO",
   "PALETTE",
   "TYPEFACE",
   "IMAGERY"
  ]
 },
 "look-book-template": {
  "path": "/templates/look-book-template",
  "name": "Look book template",
  "preset": "2x2",
  "hints": [
   "COVER LOOK",
   "LOOK 02",
   "LOOK 03",
   "DETAIL"
  ]
 },
 "mood-board-template": {
  "path": "/templates/mood-board-template",
  "name": "Mood board template",
  "preset": "hero-3-strip",
  "hints": [
   "HERO IMAGE",
   "PALETTE",
   "TEXTURE",
   "DETAIL"
  ]
 },
 "wedding-mood-board-template": {
  "path": "/templates/wedding-mood-board-template",
  "name": "Wedding mood board template",
  "preset": "hero-3-strip",
  "hints": [
   "THE FEELING",
   "THE DRESS",
   "FLOWERS",
   "THE TABLE"
  ]
 },
 "comparison-grid-template": {
  "path": "/templates/comparison-grid-template",
  "name": "Comparison grid template",
  "preset": "split-2",
  "hints": [
   "OPTION A",
   "OPTION B"
  ]
 },
 "recipe-card-template": {
  "path": "/templates/recipe-card-template",
  "name": "Recipe card template",
  "preset": "db-row-1-3",
  "hints": [
   "INGREDIENTS",
   "THE DISH",
   "METHOD",
   "NOTES"
  ]
 },
 "social-media-grid-template": {
  "path": "/templates/social-media-grid-template",
  "name": "Social media grid template",
  "preset": "contact-sheet-3x3",
  "hints": [
   "POST 1",
   "POST 2",
   "POST 3",
   "POST 4",
   "POST 5",
   "POST 6",
   "POST 7",
   "POST 8",
   "POST 9"
  ]
 }
};
