// GENERATED by scripts/gen-docs.mjs from content/templates/*.md — DO NOT EDIT BY HAND.
// Edit the markdown, then run: npm run docs:build

export const CURATED_TEMPLATES = {
 "call-sheet-template": {
  "path": "/templates/call-sheet-template",
  "name": "Call sheet template",
  "preset": "call-sheet",
  "size": {
   "w": 420,
   "h": 560
  },
  "hints": [
   "PRODUCTION · DAY · CALL",
   "LOCATION + PARKING",
   "WEATHER · SUNSET",
   "NEAREST HOSPITAL",
   "SCHEDULE — SCENE, CAST, D/N, PAGES",
   "CAST + CALL TIMES",
   "CREW BY DEPARTMENT"
  ]
 },
 "casting-board-template": {
  "path": "/templates/casting-board-template",
  "name": "Casting board template",
  "preset": "casting-3x3",
  "size": {
   "w": 400,
   "h": 595
  },
  "hints": [
   "LEAD",
   "LEAD",
   "LEAD",
   "NAME · AGENT",
   "NAME · AGENT",
   "NAME · AGENT",
   "SUPPORTING",
   "SUPPORTING",
   "SUPPORTING",
   "NAME · AGENT",
   "NAME · AGENT",
   "NAME · AGENT",
   "BACKGROUND",
   "BACKGROUND",
   "BACKGROUND",
   "NAME · AGENT",
   "NAME · AGENT",
   "NAME · AGENT"
  ]
 },
 "location-scout-template": {
  "path": "/templates/location-scout-template",
  "name": "Location scout template",
  "preset": "location-recce",
  "size": {
   "w": 480,
   "h": 420
  },
  "hints": [
   "LOCATION A — WIDE",
   "A — DETAIL",
   "A — LIGHT",
   "LOCATION B — WIDE",
   "B — DETAIL",
   "B — LIGHT",
   "LOCATION C — WIDE",
   "C — DETAIL",
   "C — LIGHT"
  ]
 },
 "shot-list-template": {
  "path": "/templates/shot-list-template",
  "name": "Shot list template",
  "preset": "shot-list-rows",
  "size": {
   "w": 720,
   "h": 430
  },
  "hints": [
   "FRAME",
   "SIZE",
   "ANGLE",
   "MOVE",
   "NOTES",
   "FRAME",
   "SIZE",
   "ANGLE",
   "MOVE",
   "NOTES",
   "FRAME",
   "SIZE",
   "ANGLE",
   "MOVE",
   "NOTES",
   "FRAME",
   "SIZE",
   "ANGLE",
   "MOVE",
   "NOTES"
  ]
 },
 "storyboard-template": {
  "path": "/templates/storyboard-template",
  "name": "Storyboard template",
  "preset": "storyboard-6up",
  "size": {
   "w": 420,
   "h": 474
  },
  "hints": [
   "SHOT 1",
   "SHOT 2",
   "ACTION",
   "ACTION",
   "SHOT 3",
   "SHOT 4",
   "ACTION",
   "ACTION",
   "SHOT 5",
   "SHOT 6",
   "ACTION",
   "ACTION"
  ]
 },
 "video-storyboard-template": {
  "path": "/templates/video-storyboard-template",
  "name": "Video storyboard template",
  "preset": "storyboard-vertical-4",
  "size": {
   "w": 540,
   "h": 274
  },
  "hints": [
   "HOOK",
   "BEAT 2",
   "BEAT 3",
   "END CARD",
   "VO / TEXT",
   "VO / TEXT",
   "VO / TEXT",
   "VO / TEXT"
  ]
 },
 "before-and-after-template": {
  "path": "/templates/before-and-after-template",
  "name": "Before and after template",
  "preset": "split-2",
  "size": {
   "w": 360,
   "h": 300
  },
  "hints": [
   "BEFORE",
   "AFTER"
  ]
 },
 "contact-sheet-template": {
  "path": "/templates/contact-sheet-template",
  "name": "Contact sheet template",
  "preset": "contact-sheet-36",
  "size": {
   "w": 540,
   "h": 360
  }
 },
 "product-lineup-template": {
  "path": "/templates/product-lineup-template",
  "name": "Product lineup template",
  "preset": "product-hero-angles",
  "size": {
   "w": 480,
   "h": 440
  },
  "hints": [
   "BACK",
   "MAIN SHOT",
   "SIDE",
   "DETAIL",
   "SCALE",
   "IN USE"
  ]
 },
 "brand-board-template": {
  "path": "/templates/brand-board-template",
  "name": "Brand board template",
  "preset": "brand-board",
  "size": {
   "w": 480,
   "h": 430
  },
  "hints": [
   "LOGO",
   "TYPEFACE",
   "PALETTE",
   "",
   "",
   "",
   "IMAGERY",
   "IMAGERY",
   "IMAGERY"
  ]
 },
 "look-book-template": {
  "path": "/templates/look-book-template",
  "name": "Look book template",
  "preset": "look-book-spread",
  "size": {
   "w": 530,
   "h": 400
  },
  "hints": [
   "COVER LOOK",
   "LOOK 02",
   "LOOK 03",
   "DETAIL"
  ]
 },
 "mood-board-template": {
  "path": "/templates/mood-board-template",
  "name": "Mood board template",
  "preset": "mood-board-palette",
  "size": {
   "w": 480,
   "h": 430
  },
  "hints": [
   "TEXTURE",
   "HERO IMAGE",
   "DETAIL",
   "TYPE",
   "PALETTE",
   "",
   "",
   ""
  ]
 },
 "wedding-mood-board-template": {
  "path": "/templates/wedding-mood-board-template",
  "name": "Wedding mood board template",
  "preset": "hero-3-strip",
  "size": {
   "w": 360,
   "h": 300
  },
  "hints": [
   "THE FEELING",
   "THE DRESS",
   "FLOWERS",
   "THE TABLE"
  ]
 },
 "comparison-grid-template": {
  "path": "/templates/comparison-grid-template",
  "name": "Comparison grid template",
  "preset": "split-2",
  "size": {
   "w": 360,
   "h": 300
  },
  "hints": [
   "OPTION A",
   "OPTION B"
  ]
 },
 "recipe-card-template": {
  "path": "/templates/recipe-card-template",
  "name": "Recipe card template",
  "preset": "recipe-card",
  "size": {
   "w": 480,
   "h": 360
  },
  "hints": [
   "THE DISH",
   "INGREDIENTS",
   "NOTES",
   "METHOD"
  ]
 },
 "social-media-grid-template": {
  "path": "/templates/social-media-grid-template",
  "name": "Social media grid template",
  "preset": "social-grid-3x4",
  "size": {
   "w": 360,
   "h": 480
  },
  "hints": [
   "POST 1",
   "POST 2",
   "POST 3",
   "POST 4",
   "POST 5",
   "POST 6",
   "POST 7",
   "POST 8",
   "POST 9"
  ]
 }
};
