// GENERATED by scripts/gen-docs.mjs from src/lib/seoLanding.js — DO NOT EDIT BY HAND.
// Edit the markdown, then run: npm run docs:build

export const CURATED_TEMPLATES = {
 "storyboard-template": {
  "path": "/templates/storyboard-template",
  "name": "Storyboard template",
  "preset": "storyboard-1-2",
  "hints": [
   "ESTABLISHING",
   "ACTION",
   "REACTION"
  ]
 },
 "contact-sheet-template": {
  "path": "/templates/contact-sheet-template",
  "name": "Contact sheet template",
  "preset": "contact-sheet-3x3"
 },
 "shot-list-template": {
  "path": "/templates/shot-list-template",
  "name": "Shot list template",
  "preset": "db-row-1-3",
  "hints": [
   "SHOT + LENS",
   "FRAME",
   "MOVEMENT",
   "NOTES"
  ]
 }
};
