// Central re-exports of icons used in Boards. Phosphor "thin" weight
// (set as default in Icon.jsx), re-aliased to the names already used
// across the app so the swap from lucide is a single-file change.
//
// Adding a new icon? Add a re-export here so swapping libraries again
// later only touches this file.
export {
  Plus,
  Minus,
  X,
  Check,
  CaretDown as ChevronDown,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  CaretLeft as ChevronLeft,
  SidebarSimple as PanelLeftClose,
  Sidebar as PanelLeftOpen,
  SidebarSimple as PanelRight,
  Sidebar as PanelRightClose,
  ArrowsOut as Maximize2,
  ArrowsIn as Minimize2,
  MagnifyingGlass as Search,
  Funnel as Filter,
  GearSix as Settings,
  ShareNetwork as Share2,
  Tray as Inbox,
  Envelope,
  SquaresFour as LayoutGrid,
  ListBullets as List,
  Cursor as MousePointer2,
  DotsSixVertical as GripVertical,
  TextB as Bold,
  TextItalic as Italic,
  TextUnderline as Underline,
  TextStrikethrough as Strikethrough,
  TextAlignLeft as AlignLeft,
  TextAlignCenter as AlignCenter,
  TextAlignRight as AlignRight,
  TextAlignJustify as AlignJustify,
  ListNumbers as ListOrdered,
  Quotes as Quote,
  Code,
  Link,
  Bookmark,
  Image,
  TextAa as Type,
  Palette,
  NoteBlank as StickyNote,
  Calendar,
  Chat as MessageSquare,
  Trash as Trash2,
  Copy,
  ArrowUUpLeft as Undo,
  ArrowUUpRight as Redo,
  CircleNotch as Loader2,
  Folder,
  FolderOpen,
  FileText,
  Files,
  DotsThree as MoreHorizontal,
  Sun,
  Moon,
  ClockCounterClockwise as History,
  Columns as Columns2,
  House as Home,
  SignOut as LogOut,
  ArrowCounterClockwise as RotateCcw,
  User,
  PencilSimple as Edit,
  Smiley as Smile,
  Paperclip,
  UserPlus,
  UsersThree as Users,
  PushPin as Pin,
  Eye,
  EyeSlash as EyeOff,
  ChatCircle as MessageCircle,
  Tag,
  Hash,
  ListChecks,
  PaintBrush,
  PaintBucket,
  Hand,
  Square,
  ArrowRight,
  Scribble,
  NotePencil,
  CaretLineLeft,
  CaretLineRight,
  CursorText,
  PencilLine,
  Globe,
  Lock,
  DotsThreeVertical,
  Heart,
  Star,
  Question,
  Info,
  Warning,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ArrowSquareOut,
  Browsers,
  TreeView,
  Graph,
  Brain,
  Sparkle,
  Lightning,
  CalendarBlank,
  ChartBar,
  ChartLine,
  ChartPie,
  ArrowsClockwise,
  Clock,
  Triangle,
  Circle,
  Diamond as DiamondShape,
  Hexagon,
  ChatTeardrop,
  Headphones,
  Microphone,
  Globe as GlobeIcon,
  Compass,
  Rocket,
  Planet,
  Moon as MoonIcon,
  CloudArrowUp,
  CloudArrowDown,
  Download,
  Upload,
  Export,
  FloppyDisk,
  FilePlus,
  FileArrowDown,
  FilePdf,
  File as FileIcon,
  FileZip,
  FileDoc,
  FilmSlate as Clapperboard,
  Database,
  Function,
  Code as CodeIcon,
  TextHOne,
  TextHTwo,
  TextHThree,
  FlipHorizontal,
  FlipVertical,
  CircleHalf,
  Thermometer,
} from '@phosphor-icons/react';
