// GENERATED by scripts/gen-docs.mjs from content/templates/*.md — DO NOT EDIT BY HAND.
// Edit the markdown, then run: npm run docs:build

export const TEMPLATE_ITEMS = [
 {
  "slug": "call-sheet-template",
  "path": "/templates/call-sheet-template",
  "title": "Call Sheet Template — Free, for Film and Video",
  "metaDescription": "A free call sheet template in the order a unit reads it — production header, location, weather, hospital, schedule, then cast and crew call times.",
  "h1": "Call sheet template",
  "blurb": "Header, location, weather, hospital, schedule, cast and crew.",
  "answer": "The page the whole unit reads at six in the morning, in its real order — production and day and general call across the top, then where you are parking, what the weather is doing and where the nearest hospital is, then the schedule, then who is called and when. The hospital box sits up top because it belongs on every sheet, whatever is being shot.",
  "category": "film",
  "preset": "call-sheet",
  "hints": [
   "PRODUCTION · DAY · CALL",
   "LOCATION + PARKING",
   "WEATHER · SUNSET",
   "NEAREST HOSPITAL",
   "SCHEDULE — SCENE, CAST, D/N, PAGES",
   "CAST + CALL TIMES",
   "CREW BY DEPARTMENT"
  ],
  "cells": 7,
  "presetLabel": "Call sheet · header, schedule, cast and crew",
  "size": {
   "w": 420,
   "h": 560
  },
  "useCase": "running a shoot day",
  "targetQuery": "call sheet template",
  "updated": "2026-08-28",
  "related": [
   "/templates/shot-list-template",
   "/templates/casting-board-template",
   "/docs/canvas/grids"
  ]
 },
 {
  "slug": "casting-board-template",
  "path": "/templates/casting-board-template",
  "title": "Casting Board Template — Headshots by Role",
  "metaDescription": "A free casting board template. Nine headshots at 4:5, a row per role tier, each with a strip for the name and the agent. Share the whole read as one link.",
  "h1": "Casting board template",
  "blurb": "Nine headshots at 4:5, a row per tier, each with a name strip.",
  "answer": "Nine headshots at 4:5, the ratio a headshot is actually printed at, three across with a row for each tier — leads, supporting, background. Every frame carries a strip for the name and the agent, because a face nobody can put a name to is not a casting decision anyone can make.",
  "category": "film",
  "preset": "casting-3x3",
  "hints": [
   "LEAD",
   "LEAD",
   "LEAD",
   "NAME · AGENT",
   "NAME · AGENT",
   "NAME · AGENT",
   "SUPPORTING",
   "SUPPORTING",
   "SUPPORTING",
   "NAME · AGENT",
   "NAME · AGENT",
   "NAME · AGENT",
   "BACKGROUND",
   "BACKGROUND",
   "BACKGROUND",
   "NAME · AGENT",
   "NAME · AGENT",
   "NAME · AGENT"
  ],
  "cells": 18,
  "presetLabel": "Casting board · 9 headshots, 4:5 with names",
  "size": {
   "w": 400,
   "h": 595
  },
  "useCase": "casting a role",
  "targetQuery": "casting board template",
  "updated": "2026-08-28",
  "related": [
   "/templates/location-scout-template",
   "/templates/call-sheet-template",
   "/docs/canvas/grids"
  ]
 },
 {
  "slug": "location-scout-template",
  "path": "/templates/location-scout-template",
  "title": "Location Scout Template — Three Options Compared",
  "metaDescription": "A free location scout template. One row per location — a wide that carries the row, then the detail and the light at the hour you would shoot.",
  "h1": "Location scout template",
  "blurb": "A row per location — a wide that leads, then the detail and the light.",
  "answer": "One row per location, and the wide takes half the row because it is the frame that decides whether the space works at all. Beside it the two that decide whether it works on the day — the detail that shows the problem, and the light at the hour you would actually be there.",
  "category": "film",
  "preset": "location-recce",
  "hints": [
   "LOCATION A — WIDE",
   "A — DETAIL",
   "A — LIGHT",
   "LOCATION B — WIDE",
   "B — DETAIL",
   "B — LIGHT",
   "LOCATION C — WIDE",
   "C — DETAIL",
   "C — LIGHT"
  ],
  "cells": 9,
  "presetLabel": "Location recce · 3 locations, wide plus two",
  "size": {
   "w": 480,
   "h": 420
  },
  "useCase": "scouting a location",
  "targetQuery": "location scout template",
  "updated": "2026-08-28",
  "related": [
   "/templates/shot-list-template",
   "/templates/call-sheet-template",
   "/tools/shot-list-maker"
  ]
 },
 {
  "slug": "shot-list-template",
  "path": "/templates/shot-list-template",
  "title": "Shot List Template — Frame, Size, Angle, Movement",
  "metaDescription": "A free shot list template with the reference frame in the row. Four setups, each with a column for shot size, camera angle, movement and notes.",
  "h1": "Shot list template",
  "blurb": "One row per setup — reference frame, then size, angle, movement, notes.",
  "answer": "Four setups, one per row, in the columns a crew reads on the day. The reference frame leads at 16:9, then how tight it is, what angle it is from, how the camera moves, and anything to watch for. Stamp a copy when four rows are not enough and the list carries on.",
  "category": "film",
  "preset": "shot-list-rows",
  "hints": [
   "FRAME",
   "SIZE",
   "ANGLE",
   "MOVE",
   "NOTES",
   "FRAME",
   "SIZE",
   "ANGLE",
   "MOVE",
   "NOTES",
   "FRAME",
   "SIZE",
   "ANGLE",
   "MOVE",
   "NOTES",
   "FRAME",
   "SIZE",
   "ANGLE",
   "MOVE",
   "NOTES"
  ],
  "cells": 20,
  "presetLabel": "Shot list · 4 setups, frame and columns",
  "size": {
   "w": 720,
   "h": 430
  },
  "useCase": "planning setups",
  "targetQuery": "shot list template",
  "updated": "2026-08-28",
  "related": [
   "/templates/storyboard-template",
   "/templates/location-scout-template",
   "/tools/shot-list-maker"
  ]
 },
 {
  "slug": "storyboard-template",
  "path": "/templates/storyboard-template",
  "title": "Storyboard Template — Free and Editable Online",
  "metaDescription": "A free storyboard template on the film-standard sheet — six 16:9 panels, each with an action line ruled underneath. Add it to a board in one click.",
  "h1": "Storyboard template",
  "blurb": "Six 16:9 panels, each with an action line ruled underneath.",
  "answer": "Six panels to a page, two across and three down, each a true 16:9 frame with a band under it for the action and the dialogue. Six is the number a scene is normally boarded at, and the band is what makes a panel legible to someone who was not in the room when it was drawn.",
  "category": "film",
  "preset": "storyboard-6up",
  "hints": [
   "SHOT 1",
   "SHOT 2",
   "ACTION",
   "ACTION",
   "SHOT 3",
   "SHOT 4",
   "ACTION",
   "ACTION",
   "SHOT 5",
   "SHOT 6",
   "ACTION",
   "ACTION"
  ],
  "cells": 12,
  "presetLabel": "Storyboard · 6 panels, 16:9",
  "size": {
   "w": 420,
   "h": 474
  },
  "useCase": "boarding a scene",
  "targetQuery": "storyboard template",
  "updated": "2026-08-28",
  "related": [
   "/templates/video-storyboard-template",
   "/templates/shot-list-template",
   "/tools/storyboard-maker"
  ]
 },
 {
  "slug": "video-storyboard-template",
  "path": "/templates/video-storyboard-template",
  "title": "Video Storyboard Template — Vertical 9:16 Beats",
  "metaDescription": "A free video storyboard template for vertical cuts. Four 9:16 panels, hook to end card, each with a line for the voiceover or the on-screen text.",
  "h1": "Video storyboard template",
  "blurb": "Four 9:16 panels — hook, two beats, end card.",
  "answer": "Boarded in the shape it will be watched in. Four panels at 9:16 rather than 16:9, because a phone cut framed on a landscape sheet is planned wrong before anyone shoots it, and a line under each for the voiceover or the words on screen.",
  "category": "film",
  "preset": "storyboard-vertical-4",
  "hints": [
   "HOOK",
   "BEAT 2",
   "BEAT 3",
   "END CARD",
   "VO / TEXT",
   "VO / TEXT",
   "VO / TEXT",
   "VO / TEXT"
  ],
  "cells": 8,
  "presetLabel": "Storyboard · 4 vertical beats, 9:16",
  "size": {
   "w": 540,
   "h": 274
  },
  "useCase": "boarding a short vertical video",
  "targetQuery": "video storyboard template",
  "updated": "2026-08-28",
  "related": [
   "/templates/storyboard-template",
   "/templates/social-media-grid-template",
   "/tools/storyboard-maker"
  ]
 },
 {
  "slug": "before-and-after-template",
  "path": "/templates/before-and-after-template",
  "title": "Before and After Template — Free Side by Side",
  "metaDescription": "A free before and after template. Two even panels, labelled, so a retouch, a renovation or a redesign reads as one comparison rather than two files.",
  "h1": "Before and after template",
  "blurb": "Two even panels, labelled — the comparison reads at a glance.",
  "answer": "Two panels of exactly equal size, one labelled BEFORE and one AFTER. Equal size is the whole point — the moment one is bigger you are arguing rather than showing. Drop an image in each and the labels disappear on their own.",
  "category": "photography",
  "preset": "split-2",
  "hints": [
   "BEFORE",
   "AFTER"
  ],
  "cells": 2,
  "presetLabel": "Side by side",
  "size": {
   "w": 360,
   "h": 300
  },
  "useCase": "showing a change",
  "targetQuery": "before and after template",
  "updated": "2026-08-27",
  "related": [
   "/templates/comparison-grid-template",
   "/templates/contact-sheet-template",
   "/docs/canvas/images"
  ]
 },
 {
  "slug": "contact-sheet-template",
  "path": "/templates/contact-sheet-template",
  "title": "Contact Sheet Template — 36 Frames at 3:2",
  "metaDescription": "A free contact sheet template built like a roll of 35mm — six strips of six, every frame at 3:2. Drop in a shoot, re-order by dragging, share one link.",
  "h1": "Contact sheet template",
  "blurb": "Six strips of six, every frame at 3:2 — a whole roll on one sheet.",
  "answer": "A roll of 35mm as it was always printed: six strips of six frames, thirty-six in all, each one at 3:2 because that is the shape of the negative. Nothing is labelled, which is the point — a proof sheet is the one sheet you read without being told what to think.",
  "category": "photography",
  "preset": "contact-sheet-36",
  "hints": null,
  "cells": 36,
  "presetLabel": "Contact sheet · 36 frames, 3:2",
  "size": {
   "w": 540,
   "h": 360
  },
  "useCase": "proofing a shoot",
  "targetQuery": "contact sheet template",
  "updated": "2026-08-28",
  "related": [
   "/templates/social-media-grid-template",
   "/templates/casting-board-template",
   "/tools/mood-board-maker"
  ]
 },
 {
  "slug": "product-lineup-template",
  "path": "/templates/product-lineup-template",
  "title": "Product Photo Template — Hero and Five Angles",
  "metaDescription": "A free product photo template. A square main shot, back and side stacked beside it, then detail, scale and in-use — the set an online listing needs.",
  "h1": "Product lineup template",
  "blurb": "A square main shot, with back, side, detail, scale and in-use around it.",
  "answer": "The main shot is square because that is the crop a marketplace thumbnails to, and it is the one image anyone decides on. Back and side stack beside it; detail, scale and in-use run underneath. Scale gets a box of its own because how big is it is the question that drives returns.",
  "category": "photography",
  "preset": "product-hero-angles",
  "hints": [
   "BACK",
   "MAIN SHOT",
   "SIDE",
   "DETAIL",
   "SCALE",
   "IN USE"
  ],
  "cells": 6,
  "presetLabel": "Product · square hero and five angles",
  "size": {
   "w": 480,
   "h": 440
  },
  "useCase": "lining up product shots",
  "targetQuery": "product photo template",
  "updated": "2026-08-28",
  "related": [
   "/templates/contact-sheet-template",
   "/templates/before-and-after-template",
   "/docs/canvas/images"
  ]
 },
 {
  "slug": "brand-board-template",
  "path": "/templates/brand-board-template",
  "title": "Brand Board Template — Logo, Palette, Type",
  "metaDescription": "A free brand board template. Logo and typeface across the top, the palette as four real swatches, and three imagery frames along the bottom.",
  "h1": "Brand board template",
  "blurb": "Logo and typeface, four palette swatches, three imagery frames.",
  "answer": "Logo and typeface across the top because they are the two that get misused, the palette underneath as four actual swatches rather than a paragraph naming hex codes, and three imagery frames along the bottom where they can be judged as a set. Hand someone this page and they can make something on-brand without asking.",
  "category": "design",
  "preset": "brand-board",
  "hints": [
   "LOGO",
   "TYPEFACE",
   "PALETTE",
   "",
   "",
   "",
   "IMAGERY",
   "IMAGERY",
   "IMAGERY"
  ],
  "cells": 9,
  "presetLabel": "Brand board · logo, type, palette, imagery",
  "size": {
   "w": 480,
   "h": 430
  },
  "useCase": "pinning a brand identity",
  "targetQuery": "brand board template",
  "updated": "2026-08-28",
  "related": [
   "/templates/mood-board-template",
   "/templates/look-book-template",
   "/docs/canvas/palettes-and-color"
  ]
 },
 {
  "slug": "look-book-template",
  "path": "/templates/look-book-template",
  "title": "Look Book Template — Four Looks, Free Online",
  "metaDescription": "A free look book template laid out as a spread. The cover look holds a full-height 2:3 page, with a second look and two detail frames stepping down beside it.",
  "h1": "Look book template",
  "blurb": "A full-height cover look at 2:3, with three stepping down beside it.",
  "answer": "A spread rather than a grid. The cover look holds a full-height page at 2:3 — the proportions of a fashion plate — and the second look sits beside it with two smaller frames stepping down under that. Four even squares read as a proof sheet with clothes in it; this reads as a book.",
  "category": "design",
  "preset": "look-book-spread",
  "hints": [
   "COVER LOOK",
   "LOOK 02",
   "LOOK 03",
   "DETAIL"
  ],
  "cells": 4,
  "presetLabel": "Look book · cover look and three",
  "size": {
   "w": 530,
   "h": 400
  },
  "useCase": "presenting looks",
  "targetQuery": "look book template",
  "updated": "2026-08-28",
  "related": [
   "/templates/mood-board-template",
   "/templates/brand-board-template",
   "/tools/look-book-maker"
  ]
 },
 {
  "slug": "mood-board-template",
  "path": "/templates/mood-board-template",
  "title": "Mood Board Template — Free, Editable, Online",
  "metaDescription": "A free mood board template — one hero image, three supporting frames for texture, detail and type, and a palette strip of swatches along the bottom.",
  "h1": "Mood board template",
  "blurb": "A hero image, three supporting frames, and a palette strip.",
  "answer": "One image carries the direction, three beside it hold the texture, the detail and the type, and a strip of four swatches runs along the bottom. The palette is the part that gets asked for and the part a plain grid of squares has nowhere to put, so it has a row of its own.",
  "category": "design",
  "preset": "mood-board-palette",
  "hints": [
   "TEXTURE",
   "HERO IMAGE",
   "DETAIL",
   "TYPE",
   "PALETTE",
   "",
   "",
   ""
  ],
  "cells": 8,
  "presetLabel": "Mood board · hero, three refs, palette strip",
  "size": {
   "w": 480,
   "h": 430
  },
  "useCase": "setting a visual direction",
  "targetQuery": "mood board template",
  "updated": "2026-08-28",
  "related": [
   "/templates/look-book-template",
   "/templates/brand-board-template",
   "/tools/mood-board-maker"
  ]
 },
 {
  "slug": "wedding-mood-board-template",
  "path": "/templates/wedding-mood-board-template",
  "title": "Wedding Mood Board Template — Free Online",
  "metaDescription": "A free wedding mood board template: one hero image over the dress, the flowers and the table setting. Labelled boxes, editable, shared with a link.",
  "h1": "Wedding mood board template",
  "blurb": "The overall feeling on top, then the dress, the flowers and the table.",
  "answer": "A wedding mood board arranged the way the decisions actually get made: the overall feeling across the top, then the three that everything else follows from — the dress, the flowers and the table setting. Share the link with your planner or your florist.",
  "category": "design",
  "preset": "hero-3-strip",
  "hints": [
   "THE FEELING",
   "THE DRESS",
   "FLOWERS",
   "THE TABLE"
  ],
  "cells": 4,
  "presetLabel": "Hero + 3 below",
  "size": {
   "w": 360,
   "h": 300
  },
  "useCase": "planning a wedding look",
  "targetQuery": "wedding mood board template",
  "updated": "2026-08-27",
  "related": [
   "/templates/mood-board-template",
   "/templates/look-book-template",
   "/tools/mood-board-maker"
  ]
 },
 {
  "slug": "comparison-grid-template",
  "path": "/templates/comparison-grid-template",
  "title": "Comparison Chart Template — Two Options, Free",
  "metaDescription": "A free comparison chart template. Two labelled columns for weighing option A against option B with real images, not just rows of text in a spreadsheet.",
  "h1": "Comparison grid template",
  "blurb": "Two labelled columns for weighing one option against another.",
  "answer": "Two columns, labelled OPTION A and OPTION B, for the decisions a spreadsheet handles badly — the ones where you need to see the two things rather than read about them. Each column takes images, text, links or a nested board.",
  "category": "planning",
  "preset": "split-2",
  "hints": [
   "OPTION A",
   "OPTION B"
  ],
  "cells": 2,
  "presetLabel": "Side by side",
  "size": {
   "w": 360,
   "h": 300
  },
  "useCase": "weighing two options",
  "targetQuery": "comparison chart template",
  "updated": "2026-08-27",
  "related": [
   "/templates/before-and-after-template",
   "/templates/mood-board-template",
   "/docs/canvas/grids"
  ]
 },
 {
  "slug": "recipe-card-template",
  "path": "/templates/recipe-card-template",
  "title": "Recipe Card Template — Photo, Method, Notes",
  "metaDescription": "A free recipe card template. The dish photo holds the left column with the notes under it, and ingredients and method run down the right in order.",
  "h1": "Recipe card template",
  "blurb": "The dish and the notes down one column, ingredients and method down the other.",
  "answer": "Two columns. The dish photo takes the top of the left with the notes underneath it, and the right runs ingredients then method — short list first, long list second, which is the order you actually work in. One card per recipe, and stamping a copy gives you the next already laid out.",
  "category": "planning",
  "preset": "recipe-card",
  "hints": [
   "THE DISH",
   "INGREDIENTS",
   "NOTES",
   "METHOD"
  ],
  "cells": 4,
  "presetLabel": "Recipe card · dish, ingredients, method",
  "size": {
   "w": 480,
   "h": 360
  },
  "useCase": "writing up a recipe",
  "targetQuery": "recipe card template",
  "updated": "2026-08-28",
  "related": [
   "/templates/shot-list-template",
   "/templates/product-lineup-template",
   "/docs/canvas/grids"
  ]
 },
 {
  "slug": "social-media-grid-template",
  "path": "/templates/social-media-grid-template",
  "title": "Instagram Grid Template — Plan Nine Posts",
  "metaDescription": "A free Instagram grid template at 3:4, the ratio a profile grid crops every thumbnail to. Nine numbered boxes, so you see the rows before you publish.",
  "h1": "Social media grid template",
  "blurb": "Nine numbered boxes at 3:4 — the ratio a profile grid actually crops to.",
  "answer": "Nine boxes three across, at 3:4 rather than square. The profile grid stopped being square in 2025 and now crops every thumbnail to 3:4, so planning a feed in squares means composing for a picture the grid will never show. Fill them in posting order and read the next three rows as they will land.",
  "category": "planning",
  "preset": "social-grid-3x4",
  "hints": [
   "POST 1",
   "POST 2",
   "POST 3",
   "POST 4",
   "POST 5",
   "POST 6",
   "POST 7",
   "POST 8",
   "POST 9"
  ],
  "cells": 9,
  "presetLabel": "Posting grid · 9 posts, 3:4",
  "size": {
   "w": 360,
   "h": 480
  },
  "useCase": "planning a posting grid",
  "targetQuery": "instagram grid template",
  "updated": "2026-08-28",
  "related": [
   "/templates/video-storyboard-template",
   "/templates/mood-board-template",
   "/docs/canvas/grids"
  ]
 }
];

const BY_PATH = new Map(TEMPLATE_ITEMS.map((t) => [t.path, t]));

// Matches the Worker's normalizePath: lowercase, strip a trailing slash.
export function getTemplateSpec(pathname) {
  if (!pathname) return null;
  let p = String(pathname).toLowerCase();
  if (p.length > 1 && p.endsWith('/')) p = p.slice(0, -1);
  return BY_PATH.get(p) || null;
}

// Shape-match, so an unknown /templates/<slug> can be a real 404 rather than
// page content at a URL whose status says gone.
export function isTemplatePath(pathname) {
  return /^\/templates\/[a-z0-9-]+\/?$/i.test(String(pathname || ''));
}
