// GENERATED by scripts/gen-docs.mjs from content/templates/*.md — DO NOT EDIT BY HAND.
// Edit the markdown, then run: npm run docs:build

export const TEMPLATE_CONTENT = {
 "/templates/shot-list-template": [
  {
   "type": "heading",
   "depth": 2,
   "text": "A shot list that shows the shot",
   "inline": [
    {
     "t": "text",
     "v": "A shot list that shows the shot"
    }
   ],
   "id": "a-shot-list-that-shows-the-shot"
  },
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "Most shot lists are a spreadsheet, and a spreadsheet cannot show you the frame. This template gives the reference image half the row and stacks the three fields a crew reads on the day beside it. On set that means one glance answers both \"what are we shooting\" and \"how\", instead of a row of text somebody has to translate back into a picture."
    }
   ]
  },
  {
   "type": "heading",
   "depth": 2,
   "text": "Beside the storyboard, not in another file",
   "inline": [
    {
     "t": "text",
     "v": "Beside the storyboard, not in another file"
    }
   ],
   "id": "beside-the-storyboard-not-in-another-file"
  },
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "The list belongs next to the frames it describes. Put these rows on the same canvas as your storyboard panels and the schedule, and the whole scene is one view instead of three documents that drift apart."
    }
   ]
  }
 ],
 "/templates/storyboard-template": [
  {
   "type": "heading",
   "depth": 2,
   "text": "Why one wide frame over two",
   "inline": [
    {
     "t": "text",
     "v": "Why one wide frame over two"
    }
   ],
   "id": "why-one-wide-frame-over-two"
  },
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "A sequence rarely reads as equal boxes. You establish, then you cut — so the template gives the establishing shot the full width and splits the beat underneath it. Drag the divider if your scene wants a different balance; the panels re-flow and nothing you have already dropped in moves."
    }
   ]
  },
  {
   "type": "heading",
   "depth": 2,
   "text": "One panel is not a storyboard",
   "inline": [
    {
     "t": "text",
     "v": "One panel is not a storyboard"
    }
   ],
   "id": "one-panel-is-not-a-storyboard"
  },
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "A scene needs more than three frames. Select the grid and the directional \"+\" handles appear on each edge: click one and you get an identical, linked panel beside it, carrying the same labels and any numbering slate you have set up. Change a divider on one and the whole row re-cuts together, so a six-panel sequence stays a grid rather than six drifting rectangles."
    }
   ]
  }
 ],
 "/templates/contact-sheet-template": [
  {
   "type": "heading",
   "depth": 2,
   "text": "Nine frames, evenly weighted",
   "inline": [
    {
     "t": "text",
     "v": "Nine frames, evenly weighted"
    }
   ],
   "id": "nine-frames-evenly-weighted"
  },
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "A contact sheet works because nothing on it is emphasised. Three by three is the point where a frame is still big enough to judge and the sheet is still small enough to take in as one image — which is why it is the shape darkroom proof sheets settled on and why it survived into digital. Every cell here is exactly the same size, so what you are comparing is the photographs, not the layout."
    }
   ]
  },
  {
   "type": "heading",
   "depth": 2,
   "text": "It is a live board, not a flat image",
   "inline": [
    {
     "t": "text",
     "v": "It is a live board, not a flat image"
    }
   ],
   "id": "it-is-a-live-board-not-a-flat-image"
  },
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "Most contact sheet templates hand you a file you fill in once. This one stays editable: swap a frame, drag one image past another to re-order, or zoom a single cell to full screen to check focus without leaving the sheet. Nothing is baked, so the sheet a client sees next week is the one you have kept working on rather than an export you have to remember to redo."
    }
   ]
  }
 ],
 "/templates/mood-board-template": [
  {
   "type": "heading",
   "depth": 2,
   "text": "Why one image leads",
   "inline": [
    {
     "t": "text",
     "v": "Why one image leads"
    }
   ],
   "id": "why-one-image-leads"
  },
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "A wall of equal thumbnails says everything matters equally, which is the opposite of a direction. Giving one image the top two-thirds forces the decision that makes a mood board useful: this is the feeling, and these three are why."
    }
   ]
  }
 ],
 "/templates/comparison-grid-template": [
  {
   "type": "heading",
   "depth": 2,
   "text": "Why not a spreadsheet",
   "inline": [
    {
     "t": "text",
     "v": "Why not a spreadsheet"
    }
   ],
   "id": "why-not-a-spreadsheet"
  },
  {
   "type": "para",
   "inline": [
    {
     "t": "text",
     "v": "A spreadsheet is the right tool when the criteria are numbers. It is the wrong one the moment the answer depends on what the options look like — which chair, which typeface, which location. This puts the two things themselves side by side, and lets the notes sit under them."
    }
   ]
  }
 ]
};
