// GENERATED by scripts/gen-docs.mjs from content/templates/*.md — DO NOT EDIT BY HAND.
// Edit the markdown, then run: npm run docs:build

export const TEMPLATE_CATEGORIES = [
 {
  "id": "film",
  "label": "Film and video",
  "blurb": "Storyboards, shot lists and the boards a crew reads on the day."
 },
 {
  "id": "photography",
  "label": "Photography",
  "blurb": "Comparing frames — proof sheets, before-and-afters, product lineups."
 },
 {
  "id": "design",
  "label": "Design and brand",
  "blurb": "Mood boards, look books and the boards that hold a visual direction."
 },
 {
  "id": "planning",
  "label": "Planning and comparison",
  "blurb": "Weighing options side by side, and laying a thing out before you make it."
 }
];

export const TEMPLATE_CARDS = [
 {
  "slug": "casting-board-template",
  "path": "/templates/casting-board-template",
  "h1": "Casting board template",
  "blurb": "Nine headshots, a row per role tier — lead, supporting, background.",
  "category": "film",
  "preset": "contact-sheet-3x3",
  "hints": [
   "LEAD",
   "LEAD",
   "LEAD",
   "SUPPORTING",
   "SUPPORTING",
   "SUPPORTING",
   "BACKGROUND",
   "BACKGROUND",
   "BACKGROUND"
  ],
  "cells": 9
 },
 {
  "slug": "location-scout-template",
  "path": "/templates/location-scout-template",
  "h1": "Location scout template",
  "blurb": "Three locations, three frames each — wide, detail, and the light.",
  "category": "film",
  "preset": "contact-sheet-3x3",
  "hints": [
   "LOCATION A — WIDE",
   "A — DETAIL",
   "A — LIGHT",
   "LOCATION B — WIDE",
   "B — DETAIL",
   "B — LIGHT",
   "LOCATION C — WIDE",
   "C — DETAIL",
   "C — LIGHT"
  ],
  "cells": 9
 },
 {
  "slug": "shot-list-template",
  "path": "/templates/shot-list-template",
  "h1": "Shot list template",
  "blurb": "A reference frame beside shot and lens, movement and notes — one row per setup.",
  "category": "film",
  "preset": "db-row-1-3",
  "hints": [
   "SHOT + LENS",
   "FRAME",
   "MOVEMENT",
   "NOTES"
  ],
  "cells": 4
 },
 {
  "slug": "storyboard-template",
  "path": "/templates/storyboard-template",
  "h1": "Storyboard template",
  "blurb": "A wide establishing frame over two beats, with every panel labelled.",
  "category": "film",
  "preset": "storyboard-1-2",
  "hints": [
   "ESTABLISHING",
   "ACTION",
   "REACTION"
  ],
  "cells": 3
 },
 {
  "slug": "video-storyboard-template",
  "path": "/templates/video-storyboard-template",
  "h1": "Video storyboard template",
  "blurb": "Four beats across — hook, two middles, end card.",
  "category": "film",
  "preset": "4up",
  "hints": [
   "HOOK",
   "BEAT 2",
   "BEAT 3",
   "END CARD"
  ],
  "cells": 4
 },
 {
  "slug": "before-and-after-template",
  "path": "/templates/before-and-after-template",
  "h1": "Before and after template",
  "blurb": "Two even panels, labelled — the comparison reads at a glance.",
  "category": "photography",
  "preset": "split-2",
  "hints": [
   "BEFORE",
   "AFTER"
  ],
  "cells": 2
 },
 {
  "slug": "contact-sheet-template",
  "path": "/templates/contact-sheet-template",
  "h1": "Contact sheet template",
  "blurb": "Nine even frames, sized so a whole shoot reads at a glance.",
  "category": "photography",
  "preset": "contact-sheet-3x3",
  "hints": null,
  "cells": 9
 },
 {
  "slug": "product-lineup-template",
  "path": "/templates/product-lineup-template",
  "h1": "Product lineup template",
  "blurb": "Four across — front, side, detail, and the in-use shot.",
  "category": "photography",
  "preset": "4up",
  "hints": [
   "FRONT",
   "SIDE",
   "DETAIL",
   "IN USE"
  ],
  "cells": 4
 },
 {
  "slug": "brand-board-template",
  "path": "/templates/brand-board-template",
  "h1": "Brand board template",
  "blurb": "Logo, palette, typeface and imagery on one page.",
  "category": "design",
  "preset": "2x2",
  "hints": [
   "LOGO",
   "PALETTE",
   "TYPEFACE",
   "IMAGERY"
  ],
  "cells": 4
 },
 {
  "slug": "look-book-template",
  "path": "/templates/look-book-template",
  "h1": "Look book template",
  "blurb": "Four even panels — a cover look, two more, and the detail.",
  "category": "design",
  "preset": "2x2",
  "hints": [
   "COVER LOOK",
   "LOOK 02",
   "LOOK 03",
   "DETAIL"
  ],
  "cells": 4
 },
 {
  "slug": "mood-board-template",
  "path": "/templates/mood-board-template",
  "h1": "Mood board template",
  "blurb": "One hero image over three supporting frames — palette, texture, detail.",
  "category": "design",
  "preset": "hero-3-strip",
  "hints": [
   "HERO IMAGE",
   "PALETTE",
   "TEXTURE",
   "DETAIL"
  ],
  "cells": 4
 },
 {
  "slug": "wedding-mood-board-template",
  "path": "/templates/wedding-mood-board-template",
  "h1": "Wedding mood board template",
  "blurb": "The overall feeling on top, then the dress, the flowers and the table.",
  "category": "design",
  "preset": "hero-3-strip",
  "hints": [
   "THE FEELING",
   "THE DRESS",
   "FLOWERS",
   "THE TABLE"
  ],
  "cells": 4
 },
 {
  "slug": "comparison-grid-template",
  "path": "/templates/comparison-grid-template",
  "h1": "Comparison grid template",
  "blurb": "Two labelled columns for weighing one option against another.",
  "category": "planning",
  "preset": "split-2",
  "hints": [
   "OPTION A",
   "OPTION B"
  ],
  "cells": 2
 },
 {
  "slug": "recipe-card-template",
  "path": "/templates/recipe-card-template",
  "h1": "Recipe card template",
  "blurb": "The dish photo at half width, with ingredients, method and notes beside it.",
  "category": "planning",
  "preset": "db-row-1-3",
  "hints": [
   "INGREDIENTS",
   "THE DISH",
   "METHOD",
   "NOTES"
  ],
  "cells": 4
 },
 {
  "slug": "social-media-grid-template",
  "path": "/templates/social-media-grid-template",
  "h1": "Social media grid template",
  "blurb": "Nine numbered boxes in the feed's own three-across shape.",
  "category": "planning",
  "preset": "contact-sheet-3x3",
  "hints": [
   "POST 1",
   "POST 2",
   "POST 3",
   "POST 4",
   "POST 5",
   "POST 6",
   "POST 7",
   "POST 8",
   "POST 9"
  ],
  "cells": 9
 }
];
