// GENERATED by scripts/gen-docs.mjs from content/templates/*.md — DO NOT EDIT BY HAND.
// Edit the markdown, then run: npm run docs:build

export const TEMPLATE_ITEMS = [
 {
  "slug": "casting-board-template",
  "path": "/templates/casting-board-template",
  "title": "Casting Board Template — Headshots by Role",
  "metaDescription": "A free casting board template. Nine headshots in a grid, labelled by role tier, so a director can compare a whole read at a glance and share one link.",
  "h1": "Casting board template",
  "blurb": "Nine headshots, a row per role tier — lead, supporting, background.",
  "answer": "Nine headshots laid out three across, with a row for each tier — leads on top, supporting in the middle, background at the bottom. Everyone reading for the same part sits on one line, which is the comparison a director is actually making.",
  "category": "film",
  "preset": "contact-sheet-3x3",
  "hints": [
   "LEAD",
   "LEAD",
   "LEAD",
   "SUPPORTING",
   "SUPPORTING",
   "SUPPORTING",
   "BACKGROUND",
   "BACKGROUND",
   "BACKGROUND"
  ],
  "cells": 9,
  "presetLabel": "Contact sheet · 3 × 3",
  "useCase": "casting a role",
  "targetQuery": "casting board template",
  "updated": "2026-08-27",
  "related": [
   "/templates/location-scout-template",
   "/templates/contact-sheet-template",
   "/docs/canvas/grids"
  ],
  "faq": [
   {
    "q": "Can I put a name or a tape link under each headshot?",
    "a": "Yes. Split a box in two and put the photo above and the text below, or drop a link card straight into the box — a cell takes an image, text, a link or a video."
   }
  ]
 },
 {
  "slug": "location-scout-template",
  "path": "/templates/location-scout-template",
  "title": "Location Scout Template — Three Options Compared",
  "metaDescription": "A free location scout template. Three locations, three frames each — wide, detail and the light at the hour you would shoot. One link for the whole recce.",
  "h1": "Location scout template",
  "blurb": "Three locations, three frames each — wide, detail, and the light.",
  "answer": "A recce grid: one row per location, three frames across — the wide that shows the space, the detail that shows the problem, and a photo of the light at the hour you would actually shoot. Three locations compared on one page instead of three folders.",
  "category": "film",
  "preset": "contact-sheet-3x3",
  "hints": [
   "LOCATION A — WIDE",
   "A — DETAIL",
   "A — LIGHT",
   "LOCATION B — WIDE",
   "B — DETAIL",
   "B — LIGHT",
   "LOCATION C — WIDE",
   "C — DETAIL",
   "C — LIGHT"
  ],
  "cells": 9,
  "presetLabel": "Contact sheet · 3 × 3",
  "useCase": "scouting a location",
  "targetQuery": "location scout template",
  "updated": "2026-08-27",
  "related": [
   "/templates/shot-list-template",
   "/templates/casting-board-template",
   "/tools/shot-list-maker"
  ],
  "faq": []
 },
 {
  "slug": "shot-list-template",
  "path": "/templates/shot-list-template",
  "title": "Shot List Template — Frame, Lens, Movement, Notes",
  "metaDescription": "A free shot list template that keeps the reference frame next to the details: shot and lens, camera movement, notes. Stamp one row per setup, numbered.",
  "h1": "Shot list template",
  "blurb": "A reference frame beside shot and lens, movement and notes — one row per setup.",
  "answer": "This shot list template pairs a reference frame with the three things a crew actually needs beside it: shot and lens, camera movement, and notes. Every box is labelled until you fill it. Add it to a board, then stamp a copy for each setup and the numbering follows.",
  "category": "film",
  "preset": "db-row-1-3",
  "hints": [
   "SHOT + LENS",
   "FRAME",
   "MOVEMENT",
   "NOTES"
  ],
  "cells": 4,
  "presetLabel": "Database row · 1 left / 3 stacked",
  "useCase": "planning setups",
  "targetQuery": "shot list template",
  "updated": "2026-08-27",
  "related": [
   "/templates/storyboard-template",
   "/templates/location-scout-template",
   "/tools/shot-list-maker"
  ],
  "faq": [
   {
    "q": "How do I add a row for every setup?",
    "a": "Select the row and click the \"+\" handle on its bottom edge to stamp a linked copy, which carries the same labels. The matrix generator lays out a whole day at once."
   },
   {
    "q": "Do the shots number themselves?",
    "a": "Yes. Put a numbering tag in a field and each row renders its own number based on where it sits on the canvas, so inserting a setup renumbers the ones after it automatically."
   }
  ]
 },
 {
  "slug": "storyboard-template",
  "path": "/templates/storyboard-template",
  "title": "Storyboard Template — Free and Editable Online",
  "metaDescription": "A free storyboard template: a wide establishing frame over two beats, every panel labelled. Drop in stills or sketches, caption each shot, share one link.",
  "h1": "Storyboard template",
  "blurb": "A wide establishing frame over two beats, with every panel labelled.",
  "answer": "This storyboard template is a three-panel grid: one wide establishing frame across the top, two beats beneath it. Each box carries a label until you fill it, so a stranger opening the file knows what goes where. Add it to Clusters in one click, then drop in stills, sketches or captions.",
  "category": "film",
  "preset": "storyboard-1-2",
  "hints": [
   "ESTABLISHING",
   "ACTION",
   "REACTION"
  ],
  "cells": 3,
  "presetLabel": "Storyboard · 1 top / 2 bottom",
  "useCase": "boarding a scene",
  "targetQuery": "storyboard template",
  "updated": "2026-08-27",
  "related": [
   "/templates/video-storyboard-template",
   "/templates/shot-list-template",
   "/tools/storyboard-maker"
  ],
  "faq": [
   {
    "q": "Can I add more panels?",
    "a": "Yes. Select the grid and click a \"+\" on any edge to stamp a linked panel beside it, or use the matrix generator to lay out a whole page at once. Stamped panels carry the same labels."
   },
   {
    "q": "What if I want a different panel layout?",
    "a": "Drag any divider to re-balance the frames, or split a panel in two. You can also pick a different template later — the images and captions you have already added carry across to the new shape."
   }
  ]
 },
 {
  "slug": "video-storyboard-template",
  "path": "/templates/video-storyboard-template",
  "title": "Video Storyboard Template — Four-Beat Strip",
  "metaDescription": "A free video storyboard template: four beats across in a strip, labelled hook to end card. Built for a short social or ad cut rather than a film scene.",
  "h1": "Video storyboard template",
  "blurb": "Four beats across — hook, two middles, end card.",
  "answer": "A short video is four beats, not a scene: the hook that stops the scroll, two beats of substance, and the end card. This lays them left to right in a strip so the pacing is visible as a shape rather than as a page of panels.",
  "category": "film",
  "preset": "4up",
  "hints": [
   "HOOK",
   "BEAT 2",
   "BEAT 3",
   "END CARD"
  ],
  "cells": 4,
  "presetLabel": "4 across",
  "useCase": "boarding a short video",
  "targetQuery": "video storyboard template",
  "updated": "2026-08-27",
  "related": [
   "/templates/storyboard-template",
   "/templates/social-media-grid-template",
   "/tools/storyboard-maker"
  ],
  "faq": [
   {
    "q": "How is this different from the storyboard template?",
    "a": "That one is a scene — a wide establishing frame with beats under it. This is a strip of four equal beats, which is the shape a short ad or social cut actually takes."
   }
  ]
 },
 {
  "slug": "before-and-after-template",
  "path": "/templates/before-and-after-template",
  "title": "Before and After Template — Free Side by Side",
  "metaDescription": "A free before and after template. Two even panels, labelled, so a retouch, a renovation or a redesign reads as one comparison rather than two files.",
  "h1": "Before and after template",
  "blurb": "Two even panels, labelled — the comparison reads at a glance.",
  "answer": "Two panels of exactly equal size, one labelled BEFORE and one AFTER. Equal size is the whole point — the moment one is bigger you are arguing rather than showing. Drop an image in each and the labels disappear on their own.",
  "category": "photography",
  "preset": "split-2",
  "hints": [
   "BEFORE",
   "AFTER"
  ],
  "cells": 2,
  "presetLabel": "Side by side",
  "useCase": "showing a change",
  "targetQuery": "before and after template",
  "updated": "2026-08-27",
  "related": [
   "/templates/comparison-grid-template",
   "/templates/contact-sheet-template",
   "/docs/canvas/images"
  ],
  "faq": [
   {
    "q": "Can I stack several before-and-afters?",
    "a": "Yes. Stamp a linked copy below the first with the \"+\" handle and you get a second labelled pair, aligned to the one above it."
   }
  ]
 },
 {
  "slug": "contact-sheet-template",
  "path": "/templates/contact-sheet-template",
  "title": "Contact Sheet Template — 3 × 3 Grid, Free Online",
  "metaDescription": "A free 3 × 3 contact sheet template. Drop nine stills, frames or product shots into an even grid, re-order by dragging, and share the sheet with one link.",
  "h1": "Contact sheet template",
  "blurb": "Nine even frames, sized so a whole shoot reads at a glance.",
  "answer": "A contact sheet template is a nine-frame grid, three across and three down, sized so every frame reads at a glance. Add it to a board in one click and fill the cells with stills, frames or product shots — then re-cut the grid without losing any of them.",
  "category": "photography",
  "preset": "contact-sheet-3x3",
  "hints": null,
  "cells": 9,
  "presetLabel": "Contact sheet · 3 × 3",
  "useCase": "proofing a shoot",
  "targetQuery": "contact sheet template",
  "updated": "2026-08-27",
  "related": [
   "/templates/social-media-grid-template",
   "/templates/casting-board-template",
   "/tools/mood-board-maker"
  ],
  "faq": [
   {
    "q": "How many images does the contact sheet hold?",
    "a": "Nine by default, in a three by three grid. You can split a cell for more, or stamp a second linked sheet beside the first to continue onto another page."
   },
   {
    "q": "Can I re-order the frames?",
    "a": "Yes. Drag one frame onto another to swap them, and the grid re-flows around the move. Nothing is fixed in place once it is dropped."
   }
  ]
 },
 {
  "slug": "product-lineup-template",
  "path": "/templates/product-lineup-template",
  "title": "Product Photo Template — Four Angles in a Row",
  "metaDescription": "A free product photo template: four panels across for the front, the side, the detail and the in-use shot. Labelled, editable, shared with one link.",
  "h1": "Product lineup template",
  "blurb": "Four across — front, side, detail, and the in-use shot.",
  "answer": "The four shots a product listing needs, side by side in the order a buyer looks at them: the front, the side, the detail that justifies the price, and one photo of the thing being used. Labelled until you fill each one.",
  "category": "photography",
  "preset": "4up",
  "hints": [
   "FRONT",
   "SIDE",
   "DETAIL",
   "IN USE"
  ],
  "cells": 4,
  "presetLabel": "4 across",
  "useCase": "lining up product shots",
  "targetQuery": "product photo template",
  "updated": "2026-08-27",
  "related": [
   "/templates/contact-sheet-template",
   "/templates/before-and-after-template",
   "/docs/canvas/images"
  ],
  "faq": []
 },
 {
  "slug": "brand-board-template",
  "path": "/templates/brand-board-template",
  "title": "Brand Board Template — Logo, Palette, Type",
  "metaDescription": "A free brand board template. Four labelled panels for the logo, the colour palette, the typeface and the imagery, on one page you can share.",
  "h1": "Brand board template",
  "blurb": "Logo, palette, typeface and imagery on one page.",
  "answer": "The four things a brand board has to answer, one per panel: what the logo is, what the colours are, what the type is, and what the photography looks like. Anyone handed this page can make something on-brand without asking a follow-up question.",
  "category": "design",
  "preset": "2x2",
  "hints": [
   "LOGO",
   "PALETTE",
   "TYPEFACE",
   "IMAGERY"
  ],
  "cells": 4,
  "presetLabel": "2 × 2",
  "useCase": "pinning a brand identity",
  "targetQuery": "brand board template",
  "updated": "2026-08-27",
  "related": [
   "/templates/mood-board-template",
   "/templates/look-book-template",
   "/docs/canvas/palettes-and-color"
  ],
  "faq": [
   {
    "q": "Can the palette be real swatches rather than a picture of some?",
    "a": "Yes. Drop a palette card into that panel and every colour on it becomes pickable everywhere else on the board."
   }
  ]
 },
 {
  "slug": "look-book-template",
  "path": "/templates/look-book-template",
  "title": "Look Book Template — Four Looks, Free Online",
  "metaDescription": "A free look book template. Four even panels for a cover look, two more, and a detail shot — labelled, editable in the browser, shared with one link.",
  "h1": "Look book template",
  "blurb": "Four even panels — a cover look, two more, and the detail.",
  "answer": "A four-panel look book: the cover look top-left, two more beside and below it, and a detail shot to close. Even weighting, because a look book is a sequence of equals rather than one hero. Fill each panel with a photo, a fabric or a still.",
  "category": "design",
  "preset": "2x2",
  "hints": [
   "COVER LOOK",
   "LOOK 02",
   "LOOK 03",
   "DETAIL"
  ],
  "cells": 4,
  "presetLabel": "2 × 2",
  "useCase": "presenting looks",
  "targetQuery": "look book template",
  "updated": "2026-08-27",
  "related": [
   "/templates/mood-board-template",
   "/templates/brand-board-template",
   "/tools/look-book-maker"
  ],
  "faq": [
   {
    "q": "How do I add more looks?",
    "a": "Stamp a linked copy with the \"+\" on any edge. Each copy carries the same four labels, so a twelve-look book stays consistent without retyping anything."
   }
  ]
 },
 {
  "slug": "mood-board-template",
  "path": "/templates/mood-board-template",
  "title": "Mood Board Template — Free, Editable, Online",
  "metaDescription": "A free mood board template: one hero image over a strip of three supporting frames, each box labelled. Drop in references and share a link.",
  "h1": "Mood board template",
  "blurb": "One hero image over three supporting frames — palette, texture, detail.",
  "answer": "A mood board template that leads with one image instead of treating everything as equal. The hero carries the direction; the three frames beneath it hold the palette, the texture and the detail that back it up. Add it to a board, drop your references in, and share a link.",
  "category": "design",
  "preset": "hero-3-strip",
  "hints": [
   "HERO IMAGE",
   "PALETTE",
   "TEXTURE",
   "DETAIL"
  ],
  "cells": 4,
  "presetLabel": "Hero + 3 below",
  "useCase": "setting a visual direction",
  "targetQuery": "mood board template",
  "updated": "2026-08-27",
  "related": [
   "/templates/look-book-template",
   "/templates/brand-board-template",
   "/tools/mood-board-maker"
  ],
  "faq": [
   {
    "q": "Can I use more than four images?",
    "a": "Yes. Split any box in two, or stamp a linked copy of the whole board beside the first to continue. The labels come with it."
   }
  ]
 },
 {
  "slug": "wedding-mood-board-template",
  "path": "/templates/wedding-mood-board-template",
  "title": "Wedding Mood Board Template — Free Online",
  "metaDescription": "A free wedding mood board template: one hero image over the dress, the flowers and the table setting. Labelled boxes, editable, shared with a link.",
  "h1": "Wedding mood board template",
  "blurb": "The overall feeling on top, then the dress, the flowers and the table.",
  "answer": "A wedding mood board arranged the way the decisions actually get made: the overall feeling across the top, then the three that everything else follows from — the dress, the flowers and the table setting. Share the link with your planner or your florist.",
  "category": "design",
  "preset": "hero-3-strip",
  "hints": [
   "THE FEELING",
   "THE DRESS",
   "FLOWERS",
   "THE TABLE"
  ],
  "cells": 4,
  "presetLabel": "Hero + 3 below",
  "useCase": "planning a wedding look",
  "targetQuery": "wedding mood board template",
  "updated": "2026-08-27",
  "related": [
   "/templates/mood-board-template",
   "/templates/look-book-template",
   "/tools/mood-board-maker"
  ],
  "faq": []
 },
 {
  "slug": "comparison-grid-template",
  "path": "/templates/comparison-grid-template",
  "title": "Comparison Chart Template — Two Options, Free",
  "metaDescription": "A free comparison chart template. Two labelled columns for weighing option A against option B with real images, not just rows of text in a spreadsheet.",
  "h1": "Comparison grid template",
  "blurb": "Two labelled columns for weighing one option against another.",
  "answer": "Two columns, labelled OPTION A and OPTION B, for the decisions a spreadsheet handles badly — the ones where you need to see the two things rather than read about them. Each column takes images, text, links or a nested board.",
  "category": "planning",
  "preset": "split-2",
  "hints": [
   "OPTION A",
   "OPTION B"
  ],
  "cells": 2,
  "presetLabel": "Side by side",
  "useCase": "weighing two options",
  "targetQuery": "comparison chart template",
  "updated": "2026-08-27",
  "related": [
   "/templates/before-and-after-template",
   "/templates/mood-board-template",
   "/docs/canvas/grids"
  ],
  "faq": [
   {
    "q": "What if I am comparing three or four things?",
    "a": "Split a column, or start from a four-across layout instead. Content you have already placed moves over when you change the shape."
   }
  ]
 },
 {
  "slug": "recipe-card-template",
  "path": "/templates/recipe-card-template",
  "title": "Recipe Card Template — Photo, Method, Notes",
  "metaDescription": "A free recipe card template. The dish photo takes half the card, with ingredients, method and notes stacked beside it. Editable and shareable as a link.",
  "h1": "Recipe card template",
  "blurb": "The dish photo at half width, with ingredients, method and notes beside it.",
  "answer": "The photo takes half the card because that is what someone decides on, and the ingredients, the method and the notes stack beside it in the order you use them. One card per recipe, and stamping a copy gives you the next one already laid out.",
  "category": "planning",
  "preset": "db-row-1-3",
  "hints": [
   "INGREDIENTS",
   "THE DISH",
   "METHOD",
   "NOTES"
  ],
  "cells": 4,
  "presetLabel": "Database row · 1 left / 3 stacked",
  "useCase": "writing up a recipe",
  "targetQuery": "recipe card template",
  "updated": "2026-08-27",
  "related": [
   "/templates/shot-list-template",
   "/templates/product-lineup-template",
   "/docs/canvas/grids"
  ],
  "faq": []
 },
 {
  "slug": "social-media-grid-template",
  "path": "/templates/social-media-grid-template",
  "title": "Instagram Grid Template — Plan Nine Posts",
  "metaDescription": "A free Instagram grid template. Nine numbered boxes in the feed's own three-across shape, so you can see how posts sit together before publishing any.",
  "h1": "Social media grid template",
  "blurb": "Nine numbered boxes in the feed's own three-across shape.",
  "answer": "A profile grid is three across, so planning one in any other shape means guessing. Nine numbered boxes in the same arrangement the feed uses, filled in posting order, showing how the next three rows will look together before you publish any of them.",
  "category": "planning",
  "preset": "contact-sheet-3x3",
  "hints": [
   "POST 1",
   "POST 2",
   "POST 3",
   "POST 4",
   "POST 5",
   "POST 6",
   "POST 7",
   "POST 8",
   "POST 9"
  ],
  "cells": 9,
  "presetLabel": "Contact sheet · 3 × 3",
  "useCase": "planning a posting grid",
  "targetQuery": "instagram grid template",
  "updated": "2026-08-27",
  "related": [
   "/templates/video-storyboard-template",
   "/templates/mood-board-template",
   "/docs/canvas/grids"
  ],
  "faq": [
   {
    "q": "Does the numbering follow the feed or reading order?",
    "a": "Reading order, left to right and top to bottom — the same order a profile grid fills, so box 1 is the next thing you post."
   }
  ]
 }
];

const BY_PATH = new Map(TEMPLATE_ITEMS.map((t) => [t.path, t]));

// Matches the Worker's normalizePath: lowercase, strip a trailing slash.
export function getTemplateSpec(pathname) {
  if (!pathname) return null;
  let p = String(pathname).toLowerCase();
  if (p.length > 1 && p.endsWith('/')) p = p.slice(0, -1);
  return BY_PATH.get(p) || null;
}

// Shape-match, so an unknown /templates/<slug> can be a real 404 rather than
// page content at a URL whose status says gone.
export function isTemplatePath(pathname) {
  return /^\/templates\/[a-z0-9-]+\/?$/i.test(String(pathname || ''));
}
