// GENERATED by scripts/gen-docs.mjs from content/templates/*.md — DO NOT EDIT BY HAND.
// Edit the markdown, then run: npm run docs:build

export const TEMPLATE_CATEGORIES = [
 {
  "id": "film",
  "label": "Film and video",
  "blurb": "Storyboards, shot lists and the boards a crew reads on the day."
 },
 {
  "id": "photography",
  "label": "Photography",
  "blurb": "Comparing frames — proof sheets, before-and-afters, product lineups."
 },
 {
  "id": "design",
  "label": "Design and brand",
  "blurb": "Mood boards, look books and the boards that hold a visual direction."
 },
 {
  "id": "planning",
  "label": "Planning and comparison",
  "blurb": "Weighing options side by side, and laying a thing out before you make it."
 }
];

export const TEMPLATE_CARDS = [
 {
  "slug": "call-sheet-template",
  "path": "/templates/call-sheet-template",
  "h1": "Call sheet template",
  "blurb": "Header, location, weather, hospital, schedule, cast and crew.",
  "category": "film",
  "preset": "call-sheet",
  "hints": [
   "PRODUCTION · DAY · CALL",
   "LOCATION + PARKING",
   "WEATHER · SUNSET",
   "NEAREST HOSPITAL",
   "SCHEDULE — SCENE, CAST, D/N, PAGES",
   "CAST + CALL TIMES",
   "CREW BY DEPARTMENT"
  ],
  "cells": 7,
  "size": {
   "w": 420,
   "h": 560
  }
 },
 {
  "slug": "casting-board-template",
  "path": "/templates/casting-board-template",
  "h1": "Casting board template",
  "blurb": "Nine headshots at 4:5, a row per tier, each with a name strip.",
  "category": "film",
  "preset": "casting-3x3",
  "hints": [
   "LEAD",
   "LEAD",
   "LEAD",
   "NAME · AGENT",
   "NAME · AGENT",
   "NAME · AGENT",
   "SUPPORTING",
   "SUPPORTING",
   "SUPPORTING",
   "NAME · AGENT",
   "NAME · AGENT",
   "NAME · AGENT",
   "BACKGROUND",
   "BACKGROUND",
   "BACKGROUND",
   "NAME · AGENT",
   "NAME · AGENT",
   "NAME · AGENT"
  ],
  "cells": 18,
  "size": {
   "w": 400,
   "h": 595
  }
 },
 {
  "slug": "location-scout-template",
  "path": "/templates/location-scout-template",
  "h1": "Location scout template",
  "blurb": "A row per location — a wide that leads, then the detail and the light.",
  "category": "film",
  "preset": "location-recce",
  "hints": [
   "LOCATION A — WIDE",
   "A — DETAIL",
   "A — LIGHT",
   "LOCATION B — WIDE",
   "B — DETAIL",
   "B — LIGHT",
   "LOCATION C — WIDE",
   "C — DETAIL",
   "C — LIGHT"
  ],
  "cells": 9,
  "size": {
   "w": 480,
   "h": 420
  }
 },
 {
  "slug": "shot-list-template",
  "path": "/templates/shot-list-template",
  "h1": "Shot list template",
  "blurb": "One row per setup — reference frame, then size, angle, movement, notes.",
  "category": "film",
  "preset": "shot-list-rows",
  "hints": [
   "FRAME",
   "SIZE",
   "ANGLE",
   "MOVE",
   "NOTES",
   "FRAME",
   "SIZE",
   "ANGLE",
   "MOVE",
   "NOTES",
   "FRAME",
   "SIZE",
   "ANGLE",
   "MOVE",
   "NOTES",
   "FRAME",
   "SIZE",
   "ANGLE",
   "MOVE",
   "NOTES"
  ],
  "cells": 20,
  "size": {
   "w": 720,
   "h": 430
  }
 },
 {
  "slug": "storyboard-template",
  "path": "/templates/storyboard-template",
  "h1": "Storyboard template",
  "blurb": "Six 16:9 panels, each with an action line ruled underneath.",
  "category": "film",
  "preset": "storyboard-6up",
  "hints": [
   "SHOT 1",
   "SHOT 2",
   "ACTION",
   "ACTION",
   "SHOT 3",
   "SHOT 4",
   "ACTION",
   "ACTION",
   "SHOT 5",
   "SHOT 6",
   "ACTION",
   "ACTION"
  ],
  "cells": 12,
  "size": {
   "w": 420,
   "h": 474
  }
 },
 {
  "slug": "video-storyboard-template",
  "path": "/templates/video-storyboard-template",
  "h1": "Video storyboard template",
  "blurb": "Four 9:16 panels — hook, two beats, end card.",
  "category": "film",
  "preset": "storyboard-vertical-4",
  "hints": [
   "HOOK",
   "BEAT 2",
   "BEAT 3",
   "END CARD",
   "VO / TEXT",
   "VO / TEXT",
   "VO / TEXT",
   "VO / TEXT"
  ],
  "cells": 8,
  "size": {
   "w": 540,
   "h": 274
  }
 },
 {
  "slug": "before-and-after-template",
  "path": "/templates/before-and-after-template",
  "h1": "Before and after template",
  "blurb": "Two even panels, labelled — the comparison reads at a glance.",
  "category": "photography",
  "preset": "split-2",
  "hints": [
   "BEFORE",
   "AFTER"
  ],
  "cells": 2,
  "size": {
   "w": 360,
   "h": 300
  }
 },
 {
  "slug": "contact-sheet-template",
  "path": "/templates/contact-sheet-template",
  "h1": "Contact sheet template",
  "blurb": "Six strips of six, every frame at 3:2 — a whole roll on one sheet.",
  "category": "photography",
  "preset": "contact-sheet-36",
  "hints": null,
  "cells": 36,
  "size": {
   "w": 540,
   "h": 360
  }
 },
 {
  "slug": "product-lineup-template",
  "path": "/templates/product-lineup-template",
  "h1": "Product lineup template",
  "blurb": "A square main shot, with back, side, detail, scale and in-use around it.",
  "category": "photography",
  "preset": "product-hero-angles",
  "hints": [
   "BACK",
   "MAIN SHOT",
   "SIDE",
   "DETAIL",
   "SCALE",
   "IN USE"
  ],
  "cells": 6,
  "size": {
   "w": 480,
   "h": 440
  }
 },
 {
  "slug": "brand-board-template",
  "path": "/templates/brand-board-template",
  "h1": "Brand board template",
  "blurb": "Logo and typeface, four palette swatches, three imagery frames.",
  "category": "design",
  "preset": "brand-board",
  "hints": [
   "LOGO",
   "TYPEFACE",
   "PALETTE",
   "",
   "",
   "",
   "IMAGERY",
   "IMAGERY",
   "IMAGERY"
  ],
  "cells": 9,
  "size": {
   "w": 480,
   "h": 430
  }
 },
 {
  "slug": "look-book-template",
  "path": "/templates/look-book-template",
  "h1": "Look book template",
  "blurb": "A full-height cover look at 2:3, with three stepping down beside it.",
  "category": "design",
  "preset": "look-book-spread",
  "hints": [
   "COVER LOOK",
   "LOOK 02",
   "LOOK 03",
   "DETAIL"
  ],
  "cells": 4,
  "size": {
   "w": 530,
   "h": 400
  }
 },
 {
  "slug": "mood-board-template",
  "path": "/templates/mood-board-template",
  "h1": "Mood board template",
  "blurb": "A hero image, three supporting frames, and a palette strip.",
  "category": "design",
  "preset": "mood-board-palette",
  "hints": [
   "TEXTURE",
   "HERO IMAGE",
   "DETAIL",
   "TYPE",
   "PALETTE",
   "",
   "",
   ""
  ],
  "cells": 8,
  "size": {
   "w": 480,
   "h": 430
  }
 },
 {
  "slug": "wedding-mood-board-template",
  "path": "/templates/wedding-mood-board-template",
  "h1": "Wedding mood board template",
  "blurb": "The overall feeling on top, then the dress, the flowers and the table.",
  "category": "design",
  "preset": "hero-3-strip",
  "hints": [
   "THE FEELING",
   "THE DRESS",
   "FLOWERS",
   "THE TABLE"
  ],
  "cells": 4,
  "size": {
   "w": 360,
   "h": 300
  }
 },
 {
  "slug": "comparison-grid-template",
  "path": "/templates/comparison-grid-template",
  "h1": "Comparison grid template",
  "blurb": "Two labelled columns for weighing one option against another.",
  "category": "planning",
  "preset": "split-2",
  "hints": [
   "OPTION A",
   "OPTION B"
  ],
  "cells": 2,
  "size": {
   "w": 360,
   "h": 300
  }
 },
 {
  "slug": "recipe-card-template",
  "path": "/templates/recipe-card-template",
  "h1": "Recipe card template",
  "blurb": "The dish and the notes down one column, ingredients and method down the other.",
  "category": "planning",
  "preset": "recipe-card",
  "hints": [
   "THE DISH",
   "INGREDIENTS",
   "NOTES",
   "METHOD"
  ],
  "cells": 4,
  "size": {
   "w": 480,
   "h": 360
  }
 },
 {
  "slug": "social-media-grid-template",
  "path": "/templates/social-media-grid-template",
  "h1": "Social media grid template",
  "blurb": "Nine numbered boxes at 3:4 — the ratio a profile grid actually crops to.",
  "category": "planning",
  "preset": "social-grid-3x4",
  "hints": [
   "POST 1",
   "POST 2",
   "POST 3",
   "POST 4",
   "POST 5",
   "POST 6",
   "POST 7",
   "POST 8",
   "POST 9"
  ],
  "cells": 9,
  "size": {
   "w": 360,
   "h": 480
  }
 }
];
