// Cloudflare Worker entrypoint. Handles /api/* routes; everything else
// falls through to env.ASSETS which serves the Vite-built dist/.
//
// /api/og?url=…       — fetches the URL server-side, parses Open Graph
//                       and favicon metadata, returns JSON. Used by link
//                       cards to render previews without hitting CORS.
// /api/tags/*         — AI tagging pipeline (embed, apply verdicts, name
//                       emergent clusters). See worker-tags.js for the
//                       per-route contracts. All routes auth-checked
//                       against the user's Supabase JWT.
// /api/share-thumb/*  — serves a shared board's stored R2 thumbnail as the
//                       og:image behind /share link previews. Gated by the
//                       share token (get_share_meta RPC), no user auth.
// /api/email-thumb/*  — serves a board's stored R2 thumbnail to email clients
//                       (the welcome email embeds the recipient's own board).
//                       Gated by an HMAC in the URL, no user auth.

import { handleTagsRoute } from './worker-tags.js';
import { handleSeoRoute, INDEXNOW_KEY, getTier } from './worker-seo.js';
import { handleAiRoute } from './worker-ai.js';
import { runCompactionJob1 } from './worker-compaction.js';
// Self-authored SEO landing pages (tool / "alternative to" / hub). Pure-data
// registry shared with the React component so the crawlable server-rendered
// text can't drift from what the app renders (anti-cloaking).
import { getLandingSpec, SEO_LANDING_PAGES, landingOgPath, EXPLORE_INTRO, matchToolPath } from './lib/seoLanding.js';
// /c/<slug> editorial article: shared model + renderer (imported by BOTH this
// worker and PublicBoardView's article — parity by construction, like seoLanding).
import { buildPageModel, renderArticleHtml } from './lib/publicPageModel.js';
// Build stamp (generated by scripts/stamp-build.mjs via the prebuild hook; a
// committed fallback keeps bare checkouts compiling). Serves /api/build-info —
// the deploy-drift detector compares this against an expected minimum.
import { BUILD_DATE, BUILD_SHA } from './lib/buildInfo.js';

const PARTYKIT_HOST = 'soleil-boards-party.arconkli.partykit.dev';

// ── Per-route SEO metadata ──────────────────────────────────────────────
// The SPA serves ONE index.html for every path (single-page-application
// asset fallback), so the static <title>/description/canonical are the
// homepage's for every URL. That makes /pricing and /legal/* look like
// duplicates of "/" to Google — which is a big reason there are no sitelinks.
// We inject each public route's own metadata here at the edge via
// HTMLRewriter, giving Google distinct, properly-labeled, indexable pages
// without adding SSR or a build step. Unknown paths keep the homepage
// defaults (harmless); non-HTML responses pass through untouched.
const SITE_ORIGIN = 'https://clusters.soleilpictures.com';
const DEFAULT_DESCRIPTION =
  'Soleil Clusters is a creative workspace and moodboard tool for film, photo, design, and brand teams — organize references, projects, and ideas in one place.';
const ROUTE_META = {
  '/': {
    title: 'Soleil Clusters — Creative Workspace & Moodboard for Production Teams',
    description: DEFAULT_DESCRIPTION,
  },
  '/pricing': {
    title: 'Pricing — Soleil Clusters',
    description:
      'Soleil Clusters pricing — start free with the Demo, or go Creator ($25/mo) for unlimited boards, 100GB storage, any file type, and Edit Mode. Simple monthly or annual plans.',
  },
  '/legal/privacy': {
    title: 'Privacy Policy — Soleil Clusters',
    description: 'How Soleil Clusters collects, uses, and protects your data.',
  },
  '/legal/terms': {
    title: 'Terms of Service — Soleil Clusters',
    description: 'The terms that govern your use of Soleil Clusters.',
  },
  '/legal/cookies': {
    title: 'Cookie Policy — Soleil Clusters',
    description: 'How Soleil Clusters uses cookies and similar technologies.',
  },
};

// Lowercase + strip a trailing slash (except root) so '/Pricing/' === '/pricing'.
function normalizePath(pathname) {
  let p = (pathname || '/').toLowerCase();
  if (p.length > 1 && p.endsWith('/')) p = p.slice(0, -1);
  return p;
}

// Tiny HTMLRewriter element handlers — each owns one mutation.
class SetText      { constructor(t) { this.t = t; } element(el) { el.setInnerContent(this.t); } }
class SetContent   { constructor(v) { this.v = v; } element(el) { el.setAttribute('content', this.v); } }
class SetHref      { constructor(h) { this.h = h; } element(el) { el.setAttribute('href', this.h); } }
// html:true appends are NOT escaped — the string must stay fully static
// (never interpolate board names or other user data into it).
class AppendHead   { constructor(h) { this.h = h; } element(el) { el.append(this.h, { html: true }); } }
// Replace an element's inner HTML with a (pre-escaped) string. Used to drop
// server-rendered crawlable content into <main id="seo-fallback">.
class SetInnerHtml { constructor(h) { this.h = h; } element(el) { el.setInnerContent(this.h, { html: true }); } }
// Drop an element entirely (e.g. the homepage canonical on a 404 document).
class RemoveEl     { element(el) { el.remove(); } }

// Escape for HTML text/attribute contexts. EVERY interpolation of board/card/
// admin-authored text into injected HTML MUST pass through this — the public
// board pages render USER-authored card titles/alt + admin SEO copy, all
// untrusted. (AppendHead / setInnerContent with html:true do NOT escape.)
function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"']/g, (c) => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]
  ));
}
// Serialize an object to embed inside <script type="application/ld+json">.
// JSON.stringify escapes quotes; we additionally neutralize </script> breakout
// and HTML-active chars so card/admin text can't break out of the script tag.
function jsonLdSafe(obj) {
  return JSON.stringify(obj)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026');
}

// Copy a response, forcing HTML documents to revalidate on every load so new
// deploys' chunk hashes are picked up immediately. `no-cache` still lets the
// browser/CDN cache the bytes — it just requires a conditional revalidation
// first, so the common case is a cheap 304, not a full re-download.
function withRevalidate(res) {
  const headers = new Headers(res.headers);
  headers.set('cache-control', 'no-cache');
  return new Response(res.body, { status: res.status, statusText: res.statusText, headers });
}

// A real 404 for page URLs that definitively don't exist (unknown /tools|/vs
// landing paths, unpublished /c/<slug>). Kills the sitewide soft-404 pattern:
// crawlers get status 404 + noindex, JS users still get the SPA shell (React
// renders a branded not-found). HTMLRewriter PRESERVES the input Response's
// status, so the 404 status must be set by rebuilding BEFORE transforming.
// `no-store` (not withRevalidate's no-cache): never let a cache revalidate a
// 404 shell into longevity. The injected HTML is fully static — AppendHead /
// SetInnerHtml(html:true) do not escape, so never interpolate request data.
const NOT_FOUND_HTML = `<div style="max-width:680px;margin:0 auto;padding:18vh 24px 24px;">
  <h1 style="font-size:1.9rem;font-weight:600;margin:0 0 .5em;">Page not found</h1>
  <p style="color:#b7b1a6;margin:0 0 1.5em;">This page doesn’t exist — it may have moved or been unpublished.</p>
  <nav style="font-size:.95rem;line-height:2;">
    <a href="/use-cases" style="color:#FFA500;text-decoration:none;margin-right:1.2em;">What you can make with Clusters</a>
    <a href="/tools/mood-board-maker" style="color:#FFA500;text-decoration:none;margin-right:1.2em;">Mood board maker</a>
    <a href="/explore" style="color:#FFA500;text-decoration:none;margin-right:1.2em;">Explore boards</a>
    <a href="/pricing" style="color:#FFA500;text-decoration:none;margin-right:1.2em;">Pricing</a>
    <a href="/" style="color:#FFA500;text-decoration:none;">Home</a>
  </nav>
</div>`;
function notFoundResponse(res, title = 'Page not found — Soleil Clusters') {
  const nf = new Response(res.body, { status: 404, statusText: 'Not Found', headers: res.headers });
  const out = new HTMLRewriter()
    .on('title',                    new SetText(title))
    .on('meta[name="description"]', new SetContent('This page doesn’t exist.'))
    .on('head',                     new AppendHead('<meta name="robots" content="noindex">'))
    // A 404 must not carry the homepage canonical/og:url (contradictory signals).
    .on('link[rel="canonical"]',    new RemoveEl())
    .on('meta[property="og:url"]',  new RemoveEl())
    .on('main#seo-fallback',        new SetInnerHtml(NOT_FOUND_HTML))
    .transform(nf);
  const headers = new Headers(out.headers);
  headers.set('cache-control', 'no-store');
  headers.set('x-robots-tag', 'noindex');
  return new Response(out.body, { status: 404, statusText: 'Not Found', headers });
}

// Rewrite the document's title/description/canonical + the OG/Twitter mirrors
// to `meta`, and point canonical/og:url at `canonical`.
function injectRouteMeta(res, meta, canonical) {
  return new HTMLRewriter()
    .on('title',                            new SetText(meta.title))
    .on('meta[name="description"]',         new SetContent(meta.description))
    .on('meta[property="og:title"]',        new SetContent(meta.title))
    .on('meta[property="og:description"]',  new SetContent(meta.description))
    .on('meta[property="og:url"]',          new SetContent(canonical))
    .on('meta[name="twitter:title"]',       new SetContent(meta.title))
    .on('meta[name="twitter:description"]', new SetContent(meta.description))
    .on('link[rel="canonical"]',            new SetHref(canonical))
    .transform(res);
}

// ── Shared-board link previews ──────────────────────────────────────────
// /share/<token> is served by the same SPA fallback as everything else, so
// without intervention every shared board unfurls as the homepage card. Here
// we resolve the token to its board (get_share_meta RPC, migration 0132 —
// same validation semantics as get_share_bundle) and rewrite the OG/Twitter
// meta to the board's name plus its stored R2 thumbnail, served token-gated
// via /api/share-thumb/<token>. RPC failure/timeout → default meta; the
// share page itself must never break on a metadata miss.
const SHARE_PATH_RE = /^\/share\/([0-9a-f-]{36})\/?$/i;
const UUID_RE = /^[0-9a-f-]{36}$/i;

// Admin-curated public marketing boards (migration 0136): clean keyword slugs at
// /c/<slug>, plus the /explore index. The slug charset is a deliberate superset
// of the DB CHECK (which forbids consecutive/edge hyphens) — the DB is the real
// gate; the route only needs to catch every valid slug. A non-matching-but-
// routed slug just resolves to no published board → default meta, no noindex.
const PUBLIC_BOARD_PATH_RE = /^\/c\/([a-z0-9][a-z0-9-]{0,79})\/?$/;
const EXPLORE_PATH_RE = /^\/explore\/?$/;

// Early share-bundle fetch, injected into /share HTML so the POST overlaps
// the entire JS download/parse instead of waiting for PublicBoardView to
// mount (saves the serialized bundle RTT — hundreds of ms on mobile).
// PublicBoardView consumes window.__shareBundle one-shot when token/boardId
// match; any mismatch or rejection falls back to its normal fetch.
// SAFETY: the string is fully static — token/?b are read from `location`
// in-browser, never interpolated here (AppendHead html:true does not escape).
// Only PARTYKIT_HOST (a build-time constant) is templated in.
const SHARE_EARLY_FETCH = `<script>(function(){try{
var m=location.pathname.match(/^\\/share\\/([0-9a-f-]{36})\\/?$/i);if(!m)return;
var b=new URLSearchParams(location.search).get('b');
var boardId=(b&&/^[0-9a-f-]{36}$/i.test(b))?b:null;
var body={token:m[1]};if(boardId)body.boardId=boardId;
window.__shareBundle={token:m[1],boardId:boardId,promise:fetch(
'https://${PARTYKIT_HOST}/parties/upload/share/share-bundle',
{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})};
}catch(_){}})()<\/script>`;

// Early public-bundle fetch for /c/<slug> marketing pages — the slug-keyed
// analog of SHARE_EARLY_FETCH. Overlaps the bundle POST with JS download so
// PublicBoardView can consume window.__publicBundle instead of re-fetching.
// SAFETY: fully static — slug/?b are read from `location` in-browser, never
// interpolated here. Only PARTYKIT_HOST (build constant) is templated.
const PUBLIC_EARLY_FETCH = `<script>(function(){try{
var m=location.pathname.match(/^\\/c\\/([a-z0-9][a-z0-9-]{0,79})\\/?$/);if(!m)return;
var b=new URLSearchParams(location.search).get('b');
var boardId=(b&&/^[0-9a-f-]{36}$/i.test(b))?b:null;
var body={slug:m[1]};if(boardId)body.boardId=boardId;
window.__publicBundle={slug:m[1],boardId:boardId,promise:fetch(
'https://${PARTYKIT_HOST}/parties/upload/share/public-bundle',
{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})};
}catch(_){}})()<\/script>`;

function injectShareMeta(res, meta, token) {
  const rw = new HTMLRewriter();
  // Tokened URLs are noindexed unless the link owner opted in (allow_indexing,
  // 0134) OR the board is a published public board (public_slug, 0136). In the
  // public_slug case we DROP the noindex and canonicalize this /share/<token>
  // onto /c/<slug> below, so the legacy link consolidates its ranking instead of
  // being deindexed (Google ignores rel=canonical when combined with noindex).
  // A failed/missing meta fetch keeps the noindex: fail closed.
  // NOTE: the appended string must stay fully static (AppendHead does not
  // escape) — never interpolate board data here.
  if (!meta?.public_slug && !meta?.allow_indexing) {
    rw.on('head', new AppendHead('<meta name="robots" content="noindex">'));
  }
  // Resolved meta = the token is valid → start the bundle fetch during HTML
  // parse. Invalid/expired tokens (meta null) skip it: no doomed POST, the
  // client renders its dead-end normally.
  if (meta?.board_id) {
    rw.on('head', new AppendHead(SHARE_EARLY_FETCH));
  }

  const name = (meta?.name || '').trim();
  if (!name) return rw.transform(res); // no meta → keep homepage defaults

  // Mirror the client's shareUrl() convention (PublicBoardView): the root
  // board is the clean /share/<token> URL; sub-boards carry ?b=<id>.
  const isSub = meta.board_id && meta.root_id && meta.board_id !== meta.root_id;
  const shareUrl = `${SITE_ORIGIN}/share/${token}${isSub ? `?b=${meta.board_id}` : ''}`;
  // Consolidate ranking: when this board is a published public board, point both
  // og:url and rel=canonical at its /c/<slug> instead of the tokened URL.
  const canonicalUrl = meta.public_slug ? `${SITE_ORIGIN}/c/${meta.public_slug}` : shareUrl;
  const title = `${name} — Soleil Clusters`;
  // Board-specific description for unfurls + (when indexable) SERP snippets.
  // The name only ever flows through SetContent/SetText, which escape it.
  const description = `“${name}” — a board shared from Soleil Clusters. References, images, and ideas in one place. Explore it, then make your own free.`;
  rw.on('title',                            new SetText(title))
    .on('meta[name="description"]',         new SetContent(description))
    .on('meta[property="og:title"]',        new SetContent(title))
    .on('meta[property="og:description"]',  new SetContent(description))
    .on('meta[property="og:url"]',          new SetContent(canonicalUrl))
    .on('meta[name="twitter:title"]',       new SetContent(title))
    .on('meta[name="twitter:description"]', new SetContent(description))
    .on('link[rel="canonical"]',            new SetHref(canonicalUrl));

  // Only point og:image at the thumb route when the board HAS a stored
  // thumbnail — otherwise leave the logo defaults untouched (some scrapers
  // reject og:image URLs that redirect, so "don't rewrite" beats "fallback").
  if (meta.thumb_key) {
    const v = encodeURIComponent(meta.thumb_updated_at || '');
    const img = `${SITE_ORIGIN}/api/share-thumb/${token}?b=${meta.board_id}&v=${v}`;
    // v2+ thumbnails (mini-screenshot rework) are 16:9 1200×675 logical;
    // legacy v1 renders still serving are 800×600. Dims are advisory hints
    // for scrapers, so the stale-bytes window during self-heal is harmless.
    const isV2 = (meta.thumb_version || 0) >= 2;
    rw.on('meta[property="og:image"]',        new SetContent(img))
      .on('meta[property="og:image:width"]',  new SetContent(isV2 ? '1200' : '800'))
      .on('meta[property="og:image:height"]', new SetContent(isV2 ? '675' : '600'))
      .on('meta[property="og:image:type"]',   new SetContent('image/webp'))
      .on('meta[property="og:image:alt"]',    new SetContent(name))
      .on('meta[name="twitter:image"]',       new SetContent(img))
      .on('meta[name="twitter:image:alt"]',   new SetContent(name));
  }
  return rw.transform(res);
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    // ── URL normalization (SEO): 301 duplicate-URL variants onto the canonical
    // form so Google consolidates instead of relying on rel=canonical alone.
    // Scope: GET/HEAD page URLs only — never /api/*, /assets/*, or real files
    // (dotted paths). Trailing slashes strip everywhere; case-folding applies
    // ONLY to marketing prefixes (never /share/<token> — token case matters).
    if ((request.method === 'GET' || request.method === 'HEAD')
        && !url.pathname.startsWith('/api/') && !url.pathname.startsWith('/assets/')
        && !url.pathname.includes('.')) {
      let p = url.pathname;
      if (p.length > 1 && p.endsWith('/')) p = p.replace(/\/+$/, '') || '/';
      if (/^\/(tools|vs|use-cases|pricing|legal|explore|c)(\/|$)/i.test(p)) p = p.toLowerCase();
      // Bare section prefixes have no page of their own — send them to the hub.
      if (p === '/tools' || p === '/vs') p = '/use-cases';
      if (p !== url.pathname) {
        return Response.redirect(url.origin + p + url.search, 301);
      }
    }

    // Guard every /api/* route: an uncaught throw here would otherwise surface
    // as a contentless Cloudflare 500. await so rejected promises are caught.
    try {
      if (url.pathname === '/api/og') return await handleOg(url, request);
      if (url.pathname.startsWith('/api/tags/')) return await handleTagsRoute(url, request, env);
      if (url.pathname.startsWith('/api/seo/')) return await handleSeoRoute(url, request, env);
      if (url.pathname.startsWith('/api/ai/')) return await handleAiRoute(url, request, env);
      const resetMatch = url.pathname.match(/^\/api\/board\/([\w-]+)\/reset$/);
      if (resetMatch) return await handleBoardReset(resetMatch[1], request);
      const thumbMatch = url.pathname.match(/^\/api\/share-thumb\/([0-9a-f-]{36})$/i);
      if (thumbMatch) return await handleShareThumb(env, thumbMatch[1], url.searchParams, request);
      const emailThumbMatch = url.pathname.match(/^\/api\/email-thumb\/([0-9a-f-]{36})$/i);
      if (emailThumbMatch) return await handleEmailThumb(env, emailThumbMatch[1], url.searchParams, request);
      if (url.pathname === '/api/admin/backfill-image-sizes') return await handleBackfillImageSizes(request, env);
      // Public marketing boards (migration 0136). Dynamic sitemap + indexable
      // og:image + crawlable per-card images, all keyed by slug. Intercepted
      // here (before env.ASSETS) so /sitemap.xml wins over any static asset.
      if (url.pathname === '/sitemap.xml') return await handleSitemap(env, request);
      if (url.pathname === '/sitemap-images.xml') return await handleImageSitemap(env, request);
      // Deploy stamp for the SEO health/drift detector: what code is actually
      // serving? (scripts/stamp-build.mjs regenerates buildInfo.js at build.)
      if (url.pathname === '/api/build-info') {
        return json({ sha: BUILD_SHA, date: BUILD_DATE }); // json() defaults to no-store
      }
      // IndexNow ownership key file (Bing/Yandex verify our submissions here).
      if (url.pathname === `/${INDEXNOW_KEY}.txt`) {
        return new Response(INDEXNOW_KEY, { headers: { 'content-type': 'text/plain; charset=utf-8', 'cache-control': 'public, max-age=86400' } });
      }
      const pubThumbMatch = url.pathname.match(/^\/api\/public-thumb\/([a-z0-9][a-z0-9-]{0,79})$/);
      if (pubThumbMatch) return await handlePublicThumb(env, pubThumbMatch[1], url.searchParams, request);
      const pubImgMatch = url.pathname.match(/^\/api\/public-img\/([a-z0-9][a-z0-9-]{0,79})$/);
      if (pubImgMatch) return await handlePublicImg(env, pubImgMatch[1], url.searchParams, request);
      // Admin-only preview of a still-pending board's images (Approvals tab).
      const admPrevMatch = url.pathname.match(/^\/api\/admin\/preview-img\/([0-9a-f-]{36})$/i);
      if (admPrevMatch) return await handleAdminPreviewImg(env, admPrevMatch[1], url.searchParams, request);
      // Logged-out one-click unsubscribe for lifecycle email (migration 0173).
      if (url.pathname === '/api/unsubscribe') return await handleUnsubscribe(request, url, env);
    } catch (e) {
      return json({ error: e?.message || String(e) }, 500);
    }

    // Kick the share-meta RPC off BEFORE the assets fetch so the Supabase
    // round-trip overlaps it instead of adding to TTFB. Failures (revoked
    // token, timeout, network) resolve to null → default homepage meta.
    // GET or HEAD: crawlers probe with HEAD, and a HEAD response must carry
    // the same status + headers (404s, x-robots-tag) as its GET twin.
    const isPageReq = request.method === 'GET' || request.method === 'HEAD';
    const shareMatch = isPageReq ? url.pathname.match(SHARE_PATH_RE) : null;
    const shareMetaPromise = shareMatch
      ? fetchShareMeta(env, shareMatch[1], url.searchParams.get('b')).catch(() => null)
      : null;

    // Same overlap trick for /c/<slug> marketing pages + the /explore index:
    // kick the Supabase RPCs off before the asset fetch. All fail to null →
    // /c falls back to default homepage meta (never noindex), /explore to empty.
    const pubMatch = isPageReq ? url.pathname.match(PUBLIC_BOARD_PATH_RE) : null;
    const pubMetaPromise = pubMatch ? fetchPublicBoardMeta(env, pubMatch[1]).catch(() => null) : null;
    const pubContentPromise = pubMatch ? fetchPublicBoardContent(env, pubMatch[1]).catch(() => null) : null;
    const pubPagePromise = pubMatch ? fetchPublicBoardPage(env, pubMatch[1]).catch(() => null) : null;
    const pubRelatedPromise = pubMatch ? fetchRelatedPublicBoards(env, pubMatch[1]).catch(() => null) : null;
    const exploreMatch = isPageReq ? url.pathname.match(EXPLORE_PATH_RE) : null;
    const exploreListPromise = exploreMatch ? fetchPublicBoards(env).catch(() => null) : null;

    // Page URLs (no extension, not /assets/*): strip conditional headers before
    // asking ASSETS, so it always returns a full 200 document instead of a 304.
    // A 304 has no content-type/body, which would silently skip EVERY branch
    // below (meta injection, the real 404s, share noindex) — and the SPA shell's
    // shared etag would mislabel per-route injected content anyway. Real assets
    // (/assets/*, dotted paths) keep full conditional-request semantics.
    let assetReq = request;
    if (isPageReq && !url.pathname.startsWith('/assets/') && !url.pathname.includes('.')
        && (request.headers.has('if-none-match') || request.headers.has('if-modified-since'))) {
      assetReq = new Request(request);
      assetReq.headers.delete('if-none-match');
      assetReq.headers.delete('if-modified-since');
    }
    const res = await env.ASSETS.fetch(assetReq);
    const contentType = res.headers.get('content-type') || '';

    // A request for a content-hashed build asset (/assets/<name>-<hash>.js|css)
    // that the SPA fallback answered with index.html (text/html) means that exact
    // chunk no longer exists on this deploy — i.e. a stale client running the
    // PREVIOUS build. Return a clean 404 so the browser rejects the dynamic
    // import with "Failed to fetch dynamically imported module" (which
    // lazyWithReload recognizes → one-shot reload) instead of trying to execute
    // the HTML as JavaScript and crashing with "undefined (reading 'default')".
    if (request.method === 'GET' && url.pathname.startsWith('/assets/') && contentType.includes('text/html')) {
      return new Response('Not found', {
        status: 404,
        headers: { 'content-type': 'text/plain; charset=utf-8', 'cache-control': 'no-store' },
      });
    }

    // Inject per-route SEO metadata for HTML document navigations to a known
    // public route. The asset served is index.html (SPA fallback), but the
    // Worker still sees the real pathname, so we can give each URL its own meta.
    if (isPageReq) {
      const meta = ROUTE_META[normalizePath(url.pathname)];
      if (meta && contentType.includes('text/html')) {
        const p = normalizePath(url.pathname);
        const canonical = p === '/' ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}${p}`;
        return withRevalidate(injectRouteMeta(res, meta, canonical));
      }
    }

    // Self-authored SEO landing pages (/tools/*, /vs/*, /use-cases): inject the
    // spec's meta + crawlable content + JSON-LD (SoftwareApplication + FAQPage +
    // BreadcrumbList). Pure static data, no RPC — resolve the exact spec here.
    // A landing-SHAPED path that's not in the registry is a definitive miss →
    // real 404 (the SPA shell would otherwise serve homepage meta at 200 for
    // /tools/<anything>, an unbounded soft-404/doorway surface).
    if (isPageReq && contentType.includes('text/html')) {
      const landingSpec = getLandingSpec(url.pathname);
      if (landingSpec) return withRevalidate(injectLanding(res, landingSpec));
      if (/^\/(?:tools|vs)\//i.test(url.pathname) || /^\/use-cases\//i.test(url.pathname)) {
        return notFoundResponse(res);
      }
    }

    // Public marketing board (/c/<slug>): keyword-rich meta + crawlable
    // server-rendered content + JSON-LD. Never noindex — these are meant to
    // rank. Definitive not-found (P0002 sentinel) → real 404; transient RPC
    // miss (null) → SPA shell with default meta at 200 (fail open, no noindex).
    if (pubMatch && contentType.includes('text/html')) {
      const [meta, content, related, page] = await Promise.all([
        pubMetaPromise, pubContentPromise, pubRelatedPromise, pubPagePromise]);
      if (meta === PUB_NOT_FOUND) {
        return notFoundResponse(res, 'Board not found — Soleil Clusters');
      }
      return withRevalidate(injectPublicBoard(res, meta, content, pubMatch[1], related, page));
    }

    // Public board index (/explore): crawlable list of /c/<slug> links + JSON-LD.
    if (exploreMatch && contentType.includes('text/html')) {
      const boards = await exploreListPromise;
      return withRevalidate(injectExplore(res, boards));
    }

    // Shared-board link previews: rewrite OG/Twitter meta on /share/<token>
    // HTML to the board's name + stored thumbnail so pasted links unfurl as
    // the board itself (and noindex the tokened URL either way).
    if (shareMatch && contentType.includes('text/html')) {
      const meta = await shareMetaPromise;
      const out = withRevalidate(injectShareMeta(res, meta, shareMatch[1]));
      // Mirror injectShareMeta's robots-meta condition as a response HEADER so
      // non-HTML-parsing fetchers also see the noindex (meta-only is invisible
      // to them). Same fail-closed rule: no meta → noindex.
      if (!meta?.public_slug && !meta?.allow_indexing) {
        out.headers.set('x-robots-tag', 'noindex');
      }
      return out;
    }

    // index.html (the SPA document, served for every app route) must be
    // revalidated so a returning client always picks up the newest deploy's
    // content-hashed chunk references instead of running a stale index that
    // points at chunks that have since been replaced. Hashed /assets/* keep
    // their year-long immutable cache (public/_headers) — only the HTML shell
    // is made always-fresh here.
    if (contentType.includes('text/html')) return withRevalidate(res);
    return res;
  },
  async scheduled(event, env, ctx) {
    // The worker has TWO cron schedules (see wrangler.toml):
    //   "0 4 * * *"   — daily 04:00 UTC; runs the history-aware R2 orphan sweep
    //   "15 * * * *"  — hourly at :15; runs Job 1 compaction (board_ops → R2 batches)
    //
    // Both default to dry-run mode. Flip via env vars when ready:
    //   R2_SWEEP_MODE=delete            (actually delete R2 orphans)
    //   HISTORY_COMPACTION_MODE=run     (actually merge + PUT + delete source ops)
    //
    // event.cron lets us distinguish which schedule fired this invocation.
    const which = event?.cron || '';
    if (which === '15 * * * *') {
      ctx.waitUntil(runCompactionJob1(env));
    } else if (which === '0 4 * * *') {
      // daily 04:00 UTC — fill in any missing image sizes (additive, runs live),
      // then the history-aware orphan sweep. Sequential so R2 ops don't spike.
      ctx.waitUntil(runImageSizeBackfill(env).then(() => runR2Sweep(env)));
    } else {
      // An edited wrangler.toml schedule must never silently reroute into the
      // destructive sweep — unknown crons are a loud no-op.
      console.error('[cron] unrecognized schedule; nothing run:', which);
    }
  },
};

// History-aware R2 orphan sweep. Replaces the previous find_orphan_images
// version (which only looked at card_index) with find_history_safe_orphan_images,
// which additionally requires that the storage_path appears in NO retained
// snapshot's r2_keys_referenced AND NO op's r2_keys array.
//
// Every candidate considered — kept or deleted — is recorded in
// r2_sweep_audit for operator review. Defaults to dry-run; actual deletes
// require R2_SWEEP_MODE=delete env var.
async function runR2Sweep(env) {
  if (!env?.IMAGES) {
    console.log('[r2-sweep] skipped: IMAGES R2 binding not configured');
    return;
  }
  if (!env?.SUPABASE_SERVICE_ROLE_KEY) {
    console.log('[r2-sweep] skipped: SUPABASE_SERVICE_ROLE_KEY not set');
    return;
  }
  const startedAt = Date.now();
  const mode = (env.R2_SWEEP_MODE || 'dryrun').toLowerCase();
  const dryRun = mode !== 'delete';
  const runId = crypto.randomUUID();

  let kept = 0;
  let toDelete = 0;
  let deleted = 0;
  const errors = [];

  try {
    // p_dryrun is passed to the RPC so its `decision` column reflects mode;
    // the worker still applies the gate itself before any R2 op below.
    const rows = await rpc(env, 'find_history_safe_orphan_images', {
      p_limit: 500,
      p_dryrun: dryRun,
    });
    if (!Array.isArray(rows) || rows.length === 0) {
      console.log(`[r2-sweep] run=${runId} mode=${mode} no candidates (${Date.now() - startedAt}ms)`);
      return;
    }

    // Audit every candidate BEFORE any destructive op — the audit trail is
    // the safety contract for the sweep. If we can't record what we're about
    // to do, we don't do it; the next daily run picks the candidates up again.
    try {
      await rpc(env, 'record_r2_sweep_audit', { p_run_id: runId, p_rows: rows });
    } catch (e) {
      console.error(`[r2-sweep] run=${runId} audit insert failed; aborting sweep`, e);
      return;
    }

    const deletedIds = [];
    for (const row of rows) {
      if (row.decision === 'keep') {
        kept++;
        continue;
      }
      if (dryRun || row.decision === 'skipped_dryrun') {
        toDelete++;
        continue;
      }
      // Only an explicit 'delete' decision is destructive — a decision value
      // we don't recognize is treated as keep, never as delete.
      if (row.decision !== 'delete') {
        kept++;
        continue;
      }
      try {
        if (row.storage_path) await env.IMAGES.delete(row.storage_path);
        deletedIds.push(row.id);
        deleted++;
      } catch (e) {
        const msg = String(e?.message || e);
        if (msg.includes('NoSuchKey') || msg.includes('404')) {
          // R2 object already gone — still close the loop in Postgres.
          deletedIds.push(row.id);
          deleted++;
        } else {
          errors.push({ id: row.id, storage_path: row.storage_path, error: msg });
        }
      }
    }

    if (deletedIds.length > 0) {
      try { await rpc(env, 'mark_image_rows_swept', { p_ids: deletedIds }); }
      catch (e) { console.warn('[r2-sweep] mark_swept rpc failed', e); }
    }

    console.log(
      `[r2-sweep] run=${runId} mode=${mode} candidates=${rows.length} kept=${kept} would-delete=${toDelete} deleted=${deleted} errors=${errors.length} took=${Date.now() - startedAt}ms`,
      errors.length > 0 ? { firstError: errors[0] } : '',
    );
  } catch (e) {
    console.error('[r2-sweep] failed', e);
  }
}

// ── Lifecycle email: logged-out one-click unsubscribe ───────────────────────
// GET renders a confirm page and DOES NOT mutate (email clients prefetch GET
// links). POST — from the confirm button AND RFC 8058 List-Unsubscribe=One-Click
// — flips the consent flag via the service-role email_unsubscribe RPC.
function unsubShell(inner) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">`
    + `<meta name="viewport" content="width=device-width,initial-scale=1">`
    + `<title>Unsubscribe · Clusters</title></head>`
    + `<body style="margin:0;background:#0a0a0c;color:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">`
    + `<div style="max-width:440px;margin:0 auto;padding:80px 24px;text-align:center;">`
    + `<div style="font:700 20px/1 inherit;letter-spacing:.18em;text-transform:uppercase;color:#f5f5f7;margin-bottom:32px;">Clusters</div>`
    + inner
    + `<p style="margin-top:24px;font-size:12px;line-height:1.5;color:#8a8a8e;">Sign-in codes and account-critical emails are unaffected.</p>`
    + `</div></body></html>`;
}

function unsubConfirmPage(action) {
  return unsubShell(
    `<p style="font-size:16px;line-height:1.6;color:#b3b3b7;">Stop getting product tips &amp; check-in emails from Clusters?</p>`
    + `<form method="POST" action="${action}" style="margin-top:24px;">`
    + `<button type="submit" style="background:#ffa500;color:#0a0a0c;border:0;border-radius:4px;padding:12px 22px;font:600 14px inherit;cursor:pointer;">Unsubscribe</button>`
    + `</form>`,
  );
}

function unsubResultPage(message) {
  return unsubShell(`<p style="font-size:16px;line-height:1.6;color:#b3b3b7;">${message}</p>`);
}

async function handleUnsubscribe(request, url, env) {
  const token = url.searchParams.get('u') || '';
  const keyRaw = url.searchParams.get('k') || 'email_lifecycle';
  const key = keyRaw === 'email_lifecycle' ? keyRaw : 'email_lifecycle';   // allowlist
  const validToken = /^[0-9a-f]{64}$/.test(token);
  const headers = {
    'content-type': 'text/html; charset=utf-8',
    'cache-control': 'no-store',
    'referrer-policy': 'no-referrer',
  };
  // Build the form action ourselves from the validated token (no echo of raw query).
  const action = `/api/unsubscribe?u=${token}&k=${key}`;

  if (request.method === 'POST') {
    if (!validToken) return new Response(unsubResultPage('That link looks invalid.'), { status: 400, headers });
    let ok = false;
    try { ok = (await rpc(env, 'email_unsubscribe', { p_token: token, p_key: key })) === true; }
    catch (e) { console.warn('[unsubscribe] rpc failed', e); ok = false; }
    return new Response(
      unsubResultPage(ok
        ? "You're unsubscribed. You won't get these notes anymore."
        : "We couldn't process that — the link may have expired."),
      { status: 200, headers },
    );
  }

  if (request.method !== 'GET') return new Response('Method not allowed', { status: 405, headers });
  if (!validToken) return new Response(unsubResultPage('That link looks invalid.'), { status: 400, headers });
  return new Response(unsubConfirmPage(action), { status: 200, headers });
}

async function rpc(env, fn, params) {
  const url = `${env.SUPABASE_URL}/rest/v1/rpc/${fn}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'apikey': env.SUPABASE_SERVICE_ROLE_KEY,
      'authorization': `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
      'content-type': 'application/json',
      'accept': 'application/json',
    },
    body: JSON.stringify(params || {}),
    // Generous because the cron RPCs (orphan scan, compaction) do real
    // table scans — but bounded, so a hung request can't eat the whole
    // scheduled() invocation.
    signal: AbortSignal.timeout(30_000),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(`rpc ${fn} ${res.status}: ${text.slice(0, 200)}`);
  }
  return await res.json();
}

// Anon-key variant of rpc() for token-gated public functions. Short timeout:
// this runs inline with HTML serving, not in a cron — a slow Supabase must
// degrade to default meta, not stall the share page.
async function anonRpc(env, fn, params, timeoutMs = 1500) {
  const res = await fetch(`${env.SUPABASE_URL}/rest/v1/rpc/${fn}`, {
    method: 'POST',
    headers: {
      'apikey': env.SUPABASE_ANON_KEY,
      'authorization': `Bearer ${env.SUPABASE_ANON_KEY}`,
      'content-type': 'application/json',
      'accept': 'application/json',
    },
    body: JSON.stringify(params || {}),
    signal: AbortSignal.timeout(timeoutMs),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(`rpc ${fn} ${res.status}: ${text.slice(0, 200)}`);
  }
  return await res.json();
}

// Resolve a share token (+ optional sub-board) to {board_id, root_id, name,
// thumb_key, thumb_updated_at}. All validation lives in the SECURITY DEFINER
// RPC (migration 0132, lockstep with get_share_bundle): revoked/expired
// tokens and unauthorized sub-boards throw — callers treat that as null.
function fetchShareMeta(env, token, boardId) {
  const params = { p_token: token };
  if (boardId && UUID_RE.test(boardId)) params.p_board_id = boardId;
  return anonRpc(env, 'get_share_meta', params);
}

// ── Public marketing boards (migration 0136) ────────────────────────────────
// Anon RPC helpers. All SECURITY DEFINER + gated on published_at + not-deleted.

// Sentinel distinguishing "this slug definitively has no published board" from
// a transient RPC failure. get_public_board_meta RAISES errcode P0002 for a
// missing/unpublished slug, which PostgREST surfaces as HTTP 500 with
// {"code":"P0002"} in the body (verified against prod). Matching the errcode —
// never the message or bare status — means outages/timeouts still throw →
// callers fail OPEN (200 + default meta), while true misses can 404.
const PUB_NOT_FOUND = Object.freeze({ notFound: true });
async function fetchPublicBoardMeta(env, slug) {
  const res = await fetch(`${env.SUPABASE_URL}/rest/v1/rpc/get_public_board_meta`, {
    method: 'POST',
    headers: {
      'apikey': env.SUPABASE_ANON_KEY,
      'authorization': `Bearer ${env.SUPABASE_ANON_KEY}`,
      'content-type': 'application/json',
      'accept': 'application/json',
    },
    body: JSON.stringify({ p_slug: slug }),
    signal: AbortSignal.timeout(1500),
  });
  if (res.ok) return await res.json();
  const text = await res.text().catch(() => '');
  if (text.includes('"P0002"')) return PUB_NOT_FOUND;
  throw new Error(`rpc get_public_board_meta ${res.status}: ${text.slice(0, 200)}`);
}
function fetchPublicBoardContent(env, slug) { return anonRpc(env, 'get_public_board_content', { p_slug: slug }); }
// Structured all-kinds page content (0181). Page rendering only — /api/public-img
// and the image sitemap stay on get_public_board_content (frozen ?i semantics).
function fetchPublicBoardPage(env, slug) { return anonRpc(env, 'get_public_board_page', { p_slug: slug }); }
function fetchRelatedPublicBoards(env, slug) { return anonRpc(env, 'get_related_public_boards', { p_slug: slug }); }
function fetchPublicBoards(env, timeoutMs = 4000) { return anonRpc(env, 'list_public_boards', {}, timeoutMs); }

function imgContentType(key) {
  const ext = (String(key).split('.').pop() || '').toLowerCase();
  return ext === 'png' ? 'image/png'
    : ext === 'webp' ? 'image/webp'
    : ext === 'gif' ? 'image/gif'
    : ext === 'svg' ? 'image/svg+xml'
    : 'image/jpeg';
}

// Inject /c/<slug> meta + crawlable content + JSON-LD. NEVER noindex: a public
// board is meant to rank, and a transient RPC miss must not deindex it — on miss
// we serve the SPA shell untouched (default homepage meta, no noindex).
function injectPublicBoard(res, meta, content, slug, related, page) {
  const rw = new HTMLRewriter();
  if (!meta?.board_id) return rw.transform(res);
  // Editorial page model (0181). Built once here, rendered as crawlable HTML
  // AND handed to React via window.__publicPageModel — same structure, same
  // order, zero extra client fetch. Falls back to the legacy flat list when
  // the page RPC missed (transient) so the route always serves content.
  const model = (page && Array.isArray(page.cards) && page.cards.length)
    ? buildPageModel({ ...(page.meta || {}), slug }, page.cards, related)
    : null;

  // Early bundle fetch (overlaps JS download). Fully static; slug read in-browser.
  rw.on('head', new AppendHead(PUBLIC_EARLY_FETCH));

  const name = (meta.name || '').trim();
  const title = (meta.seo_title || `${name} — Soleil Clusters`).trim();
  const description = (meta.seo_description
    || `${name} — a curated board on Soleil Clusters. References, images, and ideas in one place.`).trim();
  const canonical = `${SITE_ORIGIN}/c/${slug}`;

  // name/title/description flow through SetContent/SetText, which escape.
  rw.on('title',                            new SetText(title))
    .on('meta[name="description"]',         new SetContent(description))
    .on('meta[property="og:title"]',        new SetContent(title))
    .on('meta[property="og:description"]',  new SetContent(description))
    .on('meta[property="og:url"]',          new SetContent(canonical))
    .on('meta[name="twitter:title"]',       new SetContent(title))
    .on('meta[name="twitter:description"]', new SetContent(description))
    .on('link[rel="canonical"]',            new SetHref(canonical));

  // og:image — served INDEXABLE from /api/public-thumb/<slug>.
  if (meta.thumb_key || meta.og_image_key) {
    const v = encodeURIComponent(meta.thumb_updated_at || '');
    const img = `${SITE_ORIGIN}/api/public-thumb/${slug}?v=${v}`;
    const isV2 = (meta.thumb_version || 0) >= 2;
    rw.on('meta[property="og:image"]',        new SetContent(img))
      .on('meta[property="og:image:width"]',  new SetContent(isV2 ? '1200' : '800'))
      .on('meta[property="og:image:height"]', new SetContent(isV2 ? '675' : '600'))
      .on('meta[property="og:image:type"]',   new SetContent('image/webp'))
      .on('meta[property="og:image:alt"]',    new SetContent(name))
      .on('meta[name="twitter:image"]',       new SetContent(img))
      .on('meta[name="twitter:image:alt"]',   new SetContent(name));
  }

  // Crawlable server-rendered content (replaces the homepage SEO fallback) +
  // JSON-LD. All interpolation escaped (escapeHtml / jsonLdSafe / model esc).
  const cards = Array.isArray(content?.cards) ? content.cards : [];
  rw.on('main#seo-fallback', new SetInnerHtml(
    model ? renderArticleHtml(model) : buildCrawlableHtml(meta, content, slug, related)));
  if (model) {
    rw.on('head', new AppendHead(
      '<script>window.__publicPageModel=' + jsonLdSafe(model) + '</script>'));
  }
  rw.on('head', new AppendHead(
    '<script type="application/ld+json">' + jsonLdSafe(buildPublicJsonLd(meta, cards, slug, model)) + '</script>'
  ));
  return rw.transform(res);
}

// Build the crawlable inner HTML for <main id="seo-fallback">. Server text MUST
// match what PublicBoardView renders from the same card_index (anti-cloaking).
// Every value is escapeHtml'd; image src is an index into /api/public-img, never
// a reflected key; link URLs render as escaped text, never as an href (avoids
// javascript:-scheme reflection).
function buildCrawlableHtml(meta, content, slug, related) {
  const h1 = escapeHtml(meta.seo_title || meta.name || '');
  const desc = meta.seo_description ? `<p>${escapeHtml(meta.seo_description)}</p>` : '';
  const body = meta.seo_body ? `<section>${escapeHtml(meta.seo_body)}</section>` : '';
  const cards = Array.isArray(content?.cards) ? content.cards : [];
  const items = cards.map((c, i) => {
    const parts = [];
    if (c.media) {
      const alt = escapeHtml(c.media.alt || c.title || meta.name || '');
      parts.push(`<img src="${SITE_ORIGIN}/api/public-img/${escapeHtml(slug)}?i=${i}" alt="${alt}" loading="lazy" width="320" height="240">`);
    }
    if (c.title) parts.push(`<h3>${escapeHtml(c.title)}</h3>`);
    if (c.body) parts.push(`<p>${escapeHtml(c.body)}</p>`);
    else if (c.kind === 'link' && c.href) parts.push(`<p>${escapeHtml(c.href)}</p>`);
    return parts.length ? `<li>${parts.join('')}</li>` : '';
  }).join('');
  const subs = Array.isArray(content?.subboards) ? content.subboards : [];
  const subList = subs.length
    ? `<p>Sections: ${subs.map((s) => escapeHtml(s.name)).join(', ')}</p>`
    : '';
  // Related boards (shared tags) — internal-linking spokes with keyword anchors.
  const rel = Array.isArray(related) ? related : [];
  const relNav = rel.length
    ? `<nav aria-label="Related boards" style="margin-top:1.6em;"><h2 style="font-size:1.1rem;">Related boards</h2><ul>${
        rel.map((r) => `<li><a href="/c/${escapeHtml(r.slug)}" style="color:#FFA500;">${escapeHtml(r.seo_title || r.slug)}</a></li>`).join('')
      }</ul></nav>`
    : '';
  // Spoke → hub: point back at the tool page that makes this kind of board +
  // the use-cases hub, so example boards feed link equity into the landings.
  const tool = matchToolPath(meta.target_keyword || meta.seo_title || meta.name);
  const makeNav = `<nav aria-label="Make it with Clusters" style="margin-top:1.6em;">`
    + (tool ? `<a href="${escapeHtml(tool)}" style="color:#FFA500;margin-right:1.4em;">Make your own — free</a>` : '')
    + `<a href="/use-cases" style="color:#FFA500;margin-right:1.4em;">What you can make with Clusters</a>`
    + `<a href="/explore" style="color:#FFA500;">Explore more boards</a></nav>`;
  return `<div style="max-width:880px;margin:0 auto;padding:14vh 24px 24px;">
  <article>
    <h1 style="font-size:1.9rem;font-weight:600;margin:0 0 .5em;">${h1}</h1>
    ${desc}
    ${body}
    ${subList}
    <ul style="list-style:none;padding:0;">${items}</ul>
    ${relNav}
    ${makeNav}
  </article>
</div>`;
}

// CollectionPage → ImageGallery (ImageObject per image, capped) → BreadcrumbList
// (+ FAQPage when the page model carries recipe-authored Q&As — rich results for
// FAQ are dead but the schema still feeds AI-answer citation).
function buildPublicJsonLd(meta, cards, slug, model) {
  const url = `${SITE_ORIGIN}/c/${slug}`;
  const name = meta.seo_title || meta.name || '';
  const images = cards
    .map((c, i) => ({ c, i }))
    .filter((x) => x.c.media)
    .slice(0, 25)
    .map(({ c, i }) => ({
      '@type': 'ImageObject',
      contentUrl: `${SITE_ORIGIN}/api/public-img/${slug}?i=${i}`,
      name: c.media.alt || c.title || name,
      caption: c.media.alt || c.title || undefined,
    }));
  return {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'CollectionPage',
        '@id': `${url}#page`,
        url,
        name,
        description: meta.seo_description || undefined,
        // Dates come from get_public_board_meta (migration 0179); optional so
        // the page keeps working against an un-migrated DB.
        ...(meta.published_at ? { datePublished: String(meta.published_at).slice(0, 10) } : {}),
        ...(meta.updated_at ? { dateModified: String(meta.updated_at).slice(0, 10) } : {}),
        ...(meta.thumb_key || meta.og_image_key
          ? { primaryImageOfPage: { '@type': 'ImageObject', url: `${SITE_ORIGIN}/api/public-thumb/${slug}` } }
          : {}),
        isPartOf: { '@id': `${SITE_ORIGIN}/#website` },
        ...(meta.target_keyword ? { about: { '@type': 'Thing', name: meta.target_keyword } } : {}),
        mainEntity: {
          '@type': 'ImageGallery',
          name,
          ...(images.length ? { associatedMedia: images } : {}),
        },
      },
      ...(model && model.faq && model.faq.length ? [{
        '@type': 'FAQPage',
        '@id': `${url}#faq`,
        mainEntity: model.faq.map((f) => ({
          '@type': 'Question',
          name: f.q,
          acceptedAnswer: { '@type': 'Answer', text: f.a },
        })),
      }] : []),
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE_ORIGIN}/` },
          { '@type': 'ListItem', position: 2, name: 'Explore', item: `${SITE_ORIGIN}/explore` },
          { '@type': 'ListItem', position: 3, name, item: url },
        ],
      },
    ],
  };
}

// Inject the /explore index: crawlable list of /c/<slug> links + JSON-LD ItemList.
function injectExplore(res, boards) {
  const rw = new HTMLRewriter();
  const list = Array.isArray(boards) ? boards : [];
  const title = 'Explore Boards — Soleil Clusters';
  const description = 'Browse curated public moodboards and reference collections made with Soleil Clusters.';
  const canonical = `${SITE_ORIGIN}/explore`;
  rw.on('title',                            new SetText(title))
    .on('meta[name="description"]',         new SetContent(description))
    .on('meta[property="og:title"]',        new SetContent(title))
    .on('meta[property="og:description"]',  new SetContent(description))
    .on('meta[property="og:url"]',          new SetContent(canonical))
    .on('meta[name="twitter:title"]',       new SetContent(title))
    .on('meta[name="twitter:description"]', new SetContent(description))
    .on('link[rel="canonical"]',            new SetHref(canonical));

  const items = list.map((b) => {
    const t = escapeHtml(b.seo_title || b.slug);
    const d = b.seo_description ? `<p style="color:#b7b1a6;margin:.2em 0 0;">${escapeHtml(b.seo_description)}</p>` : '';
    // Spoke → hub: each example board links back to the tool page that makes
    // that kind of board, so link equity flows /explore → boards → landings.
    const tool = matchToolPath(b.target_keyword || b.seo_title);
    const make = tool ? ` <a href="${escapeHtml(tool)}" style="color:#FFA500;font-size:.9rem;">— make your own</a>` : '';
    return `<li style="margin:0 0 1.1em;"><a href="/c/${escapeHtml(b.slug)}" style="color:#FFA500;font-size:1.15rem;font-weight:600;text-decoration:none;">${t}</a>${make}${d}</li>`;
  }).join('');
  // Hub block: /explore is the crawlable center of the hub-and-spoke — it must
  // link every landing page (keyword anchors) or they sit as near-orphans.
  const toolsNav = `<nav aria-label="Make it with Clusters" style="margin:0 0 1.6em;">
    <h2 style="font-size:1.1rem;font-weight:600;margin:0 0 .4em;">Make it with Clusters</h2>
    <p style="margin:0;line-height:1.9;">${SEO_LANDING_PAGES.map((s) =>
      `<a href="${escapeHtml(s.path)}" style="color:#FFA500;text-decoration:none;margin-right:1.2em;">${escapeHtml(s.h1)}</a>`
    ).join('')}<a href="/pricing" style="color:#FFA500;text-decoration:none;">Pricing</a></p>
  </nav>`;
  const html = `<div style="max-width:760px;margin:0 auto;padding:14vh 24px 24px;">
  <article>
    <h1 style="font-size:1.9rem;font-weight:600;margin:0 0 .5em;">Explore Boards</h1>
    <p style="color:#b7b1a6;margin:0 0 1.5em;">${escapeHtml(EXPLORE_INTRO)}</p>
    ${toolsNav}
    <ul style="list-style:none;padding:0;">${items}</ul>
  </article>
</div>`;
  rw.on('main#seo-fallback', new SetInnerHtml(html));

  const jsonld = {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    url: canonical,
    name: title,
    description,
    isPartOf: { '@id': `${SITE_ORIGIN}/#website` },
    mainEntity: {
      '@type': 'ItemList',
      itemListElement: list.slice(0, 50).map((b, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        name: b.seo_title || b.slug,
        url: `${SITE_ORIGIN}/c/${b.slug}`,
      })),
    },
  };
  rw.on('head', new AppendHead('<script type="application/ld+json">' + jsonLdSafe(jsonld) + '</script>'));
  return rw.transform(res);
}

// ── Self-authored SEO landing pages ─────────────────────────────────────
// Inject a landing spec's meta + crawlable content + JSON-LD. The content is
// static (lib/seoLanding.js) but every interpolation is still escapeHtml'd /
// jsonLdSafe'd for defense in depth. Server-rendered text mirrors what
// SeoLandingPage.jsx renders from the same spec (anti-cloaking parity).
function injectLanding(res, spec) {
  const canonical = `${SITE_ORIGIN}${spec.path}`;
  const og = `${SITE_ORIGIN}${landingOgPath(spec)}`;
  const rw = new HTMLRewriter()
    .on('title',                            new SetText(spec.title))
    .on('meta[name="description"]',         new SetContent(spec.metaDescription))
    .on('meta[property="og:title"]',        new SetContent(spec.title))
    .on('meta[property="og:description"]',  new SetContent(spec.metaDescription))
    .on('meta[property="og:url"]',          new SetContent(canonical))
    .on('meta[property="og:image"]',        new SetContent(og))
    .on('meta[property="og:image:width"]',  new SetContent('1200'))
    .on('meta[property="og:image:height"]', new SetContent('630'))
    .on('meta[property="og:image:type"]',   new SetContent('image/png'))
    .on('meta[property="og:image:alt"]',    new SetContent(spec.h1))
    .on('meta[name="twitter:title"]',       new SetContent(spec.title))
    .on('meta[name="twitter:description"]', new SetContent(spec.metaDescription))
    .on('meta[name="twitter:image"]',       new SetContent(og))
    .on('meta[name="twitter:image:alt"]',   new SetContent(spec.h1))
    .on('link[rel="canonical"]',            new SetHref(canonical));
  rw.on('main#seo-fallback', new SetInnerHtml(buildLandingCrawlableHtml(spec)));
  rw.on('head', new AppendHead(
    '<script type="application/ld+json">' + jsonLdSafe(buildLandingJsonLd(spec, canonical)) + '</script>'
  ));
  return rw.transform(res);
}

function buildLandingCrawlableHtml(spec) {
  const H2 = 'font-size:1.35rem;font-weight:600;margin:1.4em 0 .4em;';
  const parts = [];
  if (spec.eyebrow) parts.push(`<p style="color:#FFA500;font-size:.8rem;letter-spacing:.16em;text-transform:uppercase;font-weight:700;margin:0 0 .8em;">${escapeHtml(spec.eyebrow)}</p>`);
  parts.push(`<h1 style="font-size:1.9rem;font-weight:700;margin:0 0 .4em;">${escapeHtml(spec.h1)}</h1>`);
  parts.push(`<p style="color:#b7b1a6;font-size:1.15rem;margin:0 0 1.4em;">${escapeHtml(spec.subhead)}</p>`);
  // The extractable direct answer + a visible freshness signal (mirrors the
  // React hero — anti-cloaking parity).
  if (spec.answer) parts.push(`<p><b>${escapeHtml(spec.answer)}</b></p>`);
  if (spec.updated) {
    const pretty = new Date(spec.updated + 'T00:00:00Z')
      .toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC' });
    parts.push(`<p style="color:#8a8a92;font-size:.85rem;"><time datetime="${escapeHtml(spec.updated)}">Updated ${escapeHtml(pretty)}</time></p>`);
  }
  for (const s of spec.sections || []) {
    parts.push(`<section><h2 style="${H2}">${escapeHtml(s.heading)}</h2><p>${escapeHtml(s.body)}</p>`);
    if (Array.isArray(s.bullets) && s.bullets.length) {
      parts.push(`<ul>${s.bullets.map((b) => `<li>${escapeHtml(b)}</li>`).join('')}</ul>`);
    }
    parts.push(`</section>`);
  }
  if (Array.isArray(spec.steps) && spec.steps.length) {
    parts.push(`<section><h2 style="${H2}">${escapeHtml(spec.stepsHeading || 'How it works')}</h2><ol>`);
    for (const s of spec.steps) parts.push(`<li><b>${escapeHtml(s.t)}</b> — ${escapeHtml(s.d)}</li>`);
    parts.push(`</ol></section>`);
  }
  if (spec.compare) {
    parts.push(`<section><h2 style="${H2}">Clusters vs ${escapeHtml(spec.compare.competitor)}</h2>`);
    if (spec.compare.intro) parts.push(`<p>${escapeHtml(spec.compare.intro)}</p>`);
    parts.push(`<table><thead><tr><th>Feature</th><th>Clusters</th><th>${escapeHtml(spec.compare.competitor)}</th></tr></thead><tbody>`);
    for (const r of spec.compare.rows || []) {
      parts.push(`<tr><th>${escapeHtml(r.feature)}</th><td>${escapeHtml(r.us)}</td><td>${escapeHtml(r.them)}</td></tr>`);
    }
    parts.push(`</tbody></table></section>`);
  }
  // Example boards — landing→board internal links (hub-and-spoke both ways).
  // Mirrors the React "Made with Clusters" section (anti-cloaking parity).
  if (Array.isArray(spec.exampleSlugs) && spec.exampleSlugs.length) {
    parts.push(`<section><h2 style="${H2}">Made with Clusters</h2><p>Real boards published from the canvas — open one and explore it live.</p><ul>`);
    for (const slug of spec.exampleSlugs) {
      const label = escapeHtml(String(slug).replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()));
      parts.push(`<li><a href="/c/${escapeHtml(slug)}" style="color:#FFA500;"><img src="/api/public-thumb/${escapeHtml(slug)}" alt="${label} — example board made with Clusters" loading="lazy" width="320" height="180"> ${label}</a></li>`);
    }
    parts.push(`</ul></section>`);
  }
  if (Array.isArray(spec.faq) && spec.faq.length) {
    parts.push(`<section><h2 style="${H2}">Frequently asked questions</h2>`);
    for (const f of spec.faq) parts.push(`<h3>${escapeHtml(f.q)}</h3><p>${escapeHtml(f.a)}</p>`);
    parts.push(`</section>`);
  }
  const related = spec.related || [];
  if (related.length) {
    parts.push(`<nav aria-label="Related pages" style="margin-top:1.6em;"><h2 style="font-size:1.1rem;">Keep exploring</h2><ul>`);
    for (const p of related) {
      const label = getLandingSpec(p)?.h1 || p;
      parts.push(`<li><a href="${escapeHtml(p)}" style="color:#FFA500;">${escapeHtml(label)}</a></li>`);
    }
    parts.push(`<li><a href="/explore" style="color:#FFA500;">Explore example boards</a></li>`);
    parts.push(`<li><a href="/pricing" style="color:#FFA500;">Pricing</a></li></ul></nav>`);
  }
  return `<div style="max-width:800px;margin:0 auto;padding:14vh 24px 24px;"><article>${parts.join('')}</article></div>`;
}

// SoftwareApplication + BreadcrumbList + (if present) FAQPage — the FAQ is
// visible on-page (the accordion), which is what FAQ rich results require.
function buildLandingJsonLd(spec, url) {
  const og = `${SITE_ORIGIN}${landingOgPath(spec)}`;
  const graph = [
    {
      '@type': 'WebPage',
      '@id': `${url}#webpage`,
      url,
      name: spec.title,
      description: spec.metaDescription,
      ...(spec.updated ? { dateModified: spec.updated } : {}),
      primaryImageOfPage: { '@type': 'ImageObject', url: og, width: 1200, height: 630 },
      isPartOf: { '@id': `${SITE_ORIGIN}/#website` },
    },
    {
      '@type': 'SoftwareApplication',
      '@id': `${url}#software`,
      name: 'Soleil Clusters',
      applicationCategory: 'BusinessApplication',
      applicationSubCategory: spec.h1,
      operatingSystem: 'Web, iOS, Android',
      url,
      description: spec.metaDescription,
      screenshot: og,
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      isPartOf: { '@id': `${SITE_ORIGIN}/#website` },
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE_ORIGIN}/` },
        { '@type': 'ListItem', position: 2, name: spec.h1, item: url },
      ],
    },
  ];
  if (Array.isArray(spec.faq) && spec.faq.length) {
    graph.push({
      '@type': 'FAQPage',
      '@id': `${url}#faq`,
      mainEntity: spec.faq.map((f) => ({
        '@type': 'Question',
        name: f.q,
        acceptedAnswer: { '@type': 'Answer', text: f.a },
      })),
    });
  }
  return { '@context': 'https://schema.org', '@graph': graph };
}

// Dynamic /sitemap.xml: static pages + /explore + every published /c/<slug>.
// MUST never 500 or shrink to empty (Google reads a sudden empty sitemap as a
// deindex signal): on RPC failure we still emit the static set. Short-cached.
async function handleSitemap(env, request) {
  // lastmod policy: HONEST dates only (fabricated per-deploy freshness trains
  // Google to ignore the field). Landings carry their spec's `updated`; the
  // homepage the date its copy last changed; /explore the newest board;
  // /c/<slug> the board's updated_at; everything else omits lastmod.
  const HOME_LASTMOD = '2026-07-07'; // homepage head/OG + crawlable copy last edited
  let boards = null;
  try { boards = await fetchPublicBoards(env, 4000); } catch (_) { boards = null; }
  const boardList = Array.isArray(boards) ? boards.filter((b) => b?.slug) : [];
  const newestBoard = boardList.reduce((max, b) => {
    const d = b.updated_at ? String(b.updated_at).slice(0, 10) : null;
    return d && (!max || d > max) ? d : max;
  }, null);
  const urls = [
    { loc: `${SITE_ORIGIN}/`,        lastmod: HOME_LASTMOD, changefreq: 'weekly',  priority: '1.0' },
    { loc: `${SITE_ORIGIN}/pricing`,                        changefreq: 'monthly', priority: '0.9' },
    { loc: `${SITE_ORIGIN}/explore`, lastmod: newestBoard,  changefreq: 'daily',   priority: '0.8' },
    // Self-authored SEO landing pages (lib/seoLanding.js): tool / "alternative
    // to" / hub. These rank independent of user-uploaded boards.
    ...SEO_LANDING_PAGES.map((s) => ({
      loc: `${SITE_ORIGIN}${s.path}`, lastmod: s.updated || null, changefreq: 'monthly', priority: '0.8',
    })),
    { loc: `${SITE_ORIGIN}/legal/privacy`,  changefreq: 'yearly',  priority: '0.3' },
    { loc: `${SITE_ORIGIN}/legal/terms`,    changefreq: 'yearly',  priority: '0.3' },
    { loc: `${SITE_ORIGIN}/legal/cookies`,  changefreq: 'yearly',  priority: '0.3' },
  ];
  for (const b of boardList) {
    urls.push({
      loc: `${SITE_ORIGIN}/c/${b.slug}`,
      lastmod: b.updated_at ? String(b.updated_at).slice(0, 10) : null,
      changefreq: 'weekly',
      priority: '0.7',
    });
  }
  const body = `<?xml version="1.0" encoding="UTF-8"?>\n`
    + `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`
    + urls.map((u) => `  <url><loc>${escapeHtml(u.loc)}</loc>`
        + (u.lastmod ? `<lastmod>${u.lastmod}</lastmod>` : '')
        + (u.changefreq ? `<changefreq>${u.changefreq}</changefreq>` : '')
        + (u.priority ? `<priority>${u.priority}</priority>` : '')
        + `</url>`).join('\n')
    + `\n</urlset>\n`;
  return sitemapResponse(body, request);
}

// Shared sitemap response: strong ETag (content hash) + 304 support so
// crawlers' conditional GETs are cheap, on top of the existing cache-control.
async function sitemapResponse(body, request) {
  const digest = await crypto.subtle.digest('SHA-1', new TextEncoder().encode(body));
  const etag = `"${[...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('')}"`;
  const headers = {
    'content-type': 'application/xml; charset=utf-8',
    'cache-control': 'public, max-age=300, s-maxage=3600',
    'etag': etag,
  };
  if (request && request.headers.get('if-none-match') === etag) {
    return new Response(null, { status: 304, headers });
  }
  return new Response(body, { headers });
}

// Dedicated image sitemap (/sitemap-images.xml) — surfaces each board's images
// (which only load via JS on the live canvas) to Google Images, our highest-ROI
// surface. ONE list_public_board_images RPC (migration 0179) returns every
// {slug, i, title} row — the old shape (one get_public_board_content subrequest
// per board) capped coverage at 40 boards because 150 boards would blow the
// 50-subrequest Workers limit. The RPC's `i` is row_number() over the SAME
// card ordering as get_public_board_content, so /api/public-img/<slug>?i=N
// keeps resolving 1:1. Falls back to the legacy per-board path (40-board cap)
// if the RPC is missing/failing — the sitemap must never 500 or shrink to
// empty (Google reads that as a deindex signal).
async function handleImageSitemap(env, request) {
  let rows = null;
  try { rows = await anonRpc(env, 'list_public_board_images', {}, 6000); } catch (_) { rows = null; }

  let blocks = [];
  if (Array.isArray(rows) && rows.length) {
    const bySlug = new Map();
    for (const r of rows) {
      if (!r?.slug || !Number.isInteger(r.i)) continue;
      const list = bySlug.get(r.slug) || [];
      list.push(r);
      bySlug.set(r.slug, list);
    }
    for (const [slug, imgs] of bySlug) {
      const entries = imgs.map((r) => {
        const title = escapeHtml(String(r.title || '').slice(0, 200));
        return `    <image:image><image:loc>${SITE_ORIGIN}/api/public-img/${escapeHtml(slug)}?i=${r.i}</image:loc>`
          + (title ? `<image:title>${title}</image:title>` : '') + `</image:image>`;
      });
      blocks.push(`  <url><loc>${SITE_ORIGIN}/c/${escapeHtml(slug)}</loc>\n${entries.join('\n')}\n  </url>`);
    }
  } else {
    // Legacy fallback: per-board content fetches, bounded to the subrequest cap.
    let boards = null;
    try { boards = await fetchPublicBoards(env, 4000); } catch (_) { boards = null; }
    const list = (Array.isArray(boards) ? boards : []).slice(0, 40);
    blocks = (await Promise.all(list.map(async (b) => {
      if (!b?.slug) return '';
      let content = null;
      try { content = await fetchPublicBoardContent(env, b.slug); } catch (_) { return ''; }
      const cards = Array.isArray(content?.cards) ? content.cards : [];
      const imgs = [];
      cards.forEach((c, i) => {
        if (c.media && imgs.length < 30) {
          const title = escapeHtml((c.media.alt || c.title || b.seo_title || b.slug || '').slice(0, 200));
          imgs.push(`    <image:image><image:loc>${SITE_ORIGIN}/api/public-img/${escapeHtml(b.slug)}?i=${i}</image:loc>`
            + (title ? `<image:title>${title}</image:title>` : '') + `</image:image>`);
        }
      });
      if (!imgs.length) return '';
      return `  <url><loc>${SITE_ORIGIN}/c/${escapeHtml(b.slug)}</loc>\n${imgs.join('\n')}\n  </url>`;
    }))).filter(Boolean);
  }

  const body = `<?xml version="1.0" encoding="UTF-8"?>\n`
    + `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n`
    + blocks.join('\n')
    + `\n</urlset>\n`;
  return sitemapResponse(body, request);
}

// og:image for /c/<slug> — clone of handleShareThumb but slug-keyed and
// INDEXABLE (no x-robots-tag: noindex). Prefers an admin og_image_key override.
async function handlePublicThumb(env, slug, searchParams, request) {
  const fallback = () =>
    new Response(null, {
      status: 302,
      headers: { location: `${SITE_ORIGIN}/clusters-logo-dark.png`, 'cache-control': 'no-store' },
    });
  let meta = null;
  try { meta = await fetchPublicBoardMeta(env, slug); } catch { return fallback(); }
  if (!meta || meta === PUB_NOT_FOUND) return fallback();
  const key = (meta?.og_image_key || meta?.thumb_key || '').replace(/^r2:/, '');
  if (!key || !env.IMAGES) return fallback();
  const obj = await env.IMAGES.get(key);
  if (!obj) return fallback();
  const headers = {
    'content-type': obj.httpMetadata?.contentType || imgContentType(key),
    'cache-control': 'public, max-age=3600',
    'etag': obj.httpEtag,
  };
  if (request.headers.get('if-none-match') === obj.httpEtag) {
    return new Response(null, { status: 304, headers });
  }
  return new Response(obj.body, { status: 200, headers });
}

// Crawlable per-card image for /c/<slug> (?i=<index>). Re-authorizes on EVERY
// request: re-resolves the slug through the published+not-deleted gate, bounds
// the index, and only serves a key that actually belongs to that board's image
// card (no enumeration oracle). INDEXABLE (no noindex).
async function handlePublicImg(env, slug, searchParams, request) {
  const i = parseInt(searchParams.get('i') || '', 10);
  if (!Number.isInteger(i) || i < 0) return new Response('Not found', { status: 404 });
  let content = null;
  try { content = await fetchPublicBoardContent(env, slug); } catch { return new Response('Not found', { status: 404 }); }
  const cards = Array.isArray(content?.cards) ? content.cards : [];
  const card = cards[i];
  if (!card || card.kind !== 'image' || !card.media) return new Response('Not found', { status: 404 });
  const key = String(card.media.preview_key || card.media.src_key || '').replace(/^r2:/, '');
  if (!key || !env.IMAGES) return new Response('Not found', { status: 404 });
  const obj = await env.IMAGES.get(key);
  if (!obj) return new Response('Not found', { status: 404 });
  const headers = {
    'content-type': obj.httpMetadata?.contentType || imgContentType(key),
    'cache-control': 'public, max-age=86400',
    'etag': obj.httpEtag,
  };
  if (request.headers.get('if-none-match') === obj.httpEtag) {
    return new Response(null, { status: 304, headers });
  }
  return new Response(obj.body, { status: 200, headers });
}

// rpc() variant that runs AS a specific signed-in user (anon apikey + their JWT)
// so SECURITY DEFINER functions gated on is_admin()/auth.uid() see that user
// rather than the service role. Used by the admin preview-image route.
async function userRpc(env, fn, params, userToken, timeoutMs = 8000) {
  const res = await fetch(`${env.SUPABASE_URL}/rest/v1/rpc/${fn}`, {
    method: 'POST',
    headers: {
      'apikey': env.SUPABASE_ANON_KEY,
      'authorization': `Bearer ${userToken}`,
      'content-type': 'application/json',
      'accept': 'application/json',
    },
    body: JSON.stringify(params || {}),
    signal: AbortSignal.timeout(timeoutMs),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(`rpc ${fn} ${res.status}: ${text.slice(0, 200)}`);
  }
  return await res.json();
}

// Admin-only preview of a still-PENDING board's per-card image (the Approvals
// tab gallery). A plain <img> can't carry a bearer header and R2 buckets are
// membership-scoped (0165), so the normal in-app read path rejects an admin who
// isn't a member of the board. The admin client therefore fetch()es this with
// its Supabase access token; we re-verify admin at the edge, then call
// admin_public_board_preview AS that admin (so is_admin() passes) and only serve
// a key that actually belongs to that board's image cards (no enumeration
// oracle). Mirrors handlePublicImg, but keyed by board_id + auth-gated.
async function handleAdminPreviewImg(env, boardId, searchParams, request) {
  const i = parseInt(searchParams.get('i') || '', 10);
  if (!Number.isInteger(i) || i < 0) return new Response('Not found', { status: 404 });
  const token = (request.headers.get('authorization') || '').replace(/^Bearer\s+/i, '');
  if (!token) return new Response('Unauthorized', { status: 401 });
  let tier = null;
  try { tier = await getTier(env, token); } catch { return new Response('tier check failed', { status: 502 }); }
  if (tier !== 'admin') return new Response('Forbidden', { status: 403 });

  let content = null;
  try { content = await userRpc(env, 'admin_public_board_preview', { p_board_id: boardId }, token); }
  catch { return new Response('Not found', { status: 404 }); }
  const cards = Array.isArray(content?.cards) ? content.cards : [];
  const card = cards[i];
  if (!card || card.kind !== 'image' || !card.media) return new Response('Not found', { status: 404 });
  const key = String(card.media.preview_key || card.media.src_key || '').replace(/^r2:/, '');
  if (!key || !env.IMAGES) return new Response('Not found', { status: 404 });
  const obj = await env.IMAGES.get(key);
  if (!obj) return new Response('Not found', { status: 404 });
  const headers = {
    'content-type': obj.httpMetadata?.contentType || imgContentType(key),
    // private: it's behind an admin gate — never let a shared cache hold it.
    'cache-control': 'private, no-store',
    'etag': obj.httpEtag,
  };
  if (request.headers.get('if-none-match') === obj.httpEtag) {
    return new Response(null, { status: 304, headers });
  }
  return new Response(obj.body, { status: 200, headers });
}

// Serves a shared board's stored thumbnail (<ws>/thumbs/<board>.webp in R2)
// as the og:image behind /share link previews. Same token gate as the share
// bundle. injectShareMeta only points og:image here when the board HAS a
// thumb, so the 302→logo below is a defensive fallback for stale unfurls
// (revoked links, thumb rows that never resolved), not a normal path.
async function handleShareThumb(env, token, searchParams, request) {
  const fallback = () =>
    new Response(null, {
      status: 302,
      headers: { location: `${SITE_ORIGIN}/clusters-logo-dark.png`, 'cache-control': 'no-store' },
    });

  let meta = null;
  try {
    meta = await fetchShareMeta(env, token, searchParams.get('b'));
  } catch {
    return fallback();
  }
  const key = (meta?.thumb_key || '').replace(/^r2:/, '');
  if (!key || !env.IMAGES) return fallback();

  const obj = await env.IMAGES.get(key);
  if (!obj) return fallback();

  const headers = {
    'content-type': 'image/webp',
    // 1h browser cache: the URL carries a v= cache-buster for freshness, and
    // a short TTL bounds how long a just-revoked link keeps serving bytes.
    'cache-control': 'public, max-age=3600',
    'etag': obj.httpEtag,
    'x-robots-tag': 'noindex',
  };
  if (request.headers.get('if-none-match') === obj.httpEtag) {
    return new Response(null, { status: 304, headers });
  }
  return new Response(obj.body, { status: 200, headers });
}

// Signature for /api/email-thumb URLs. The HMAC key is DERIVED from the
// service-role key (SHA-256 over key + a domain-separation tag) — this worker
// and the lifecycle-email-cron edge fn both already hold that secret, so no
// new secret has to be provisioned on either side. HMAC output reveals nothing
// about the key; rotating the service key merely invalidates old email image
// URLs, which then 302 to the logo fallback. lifecycle-email-cron carries the
// mirror of this derivation — keep the two in lockstep.
async function emailThumbSig(env, boardId) {
  const enc = new TextEncoder();
  const keyBytes = await crypto.subtle.digest(
    'SHA-256', enc.encode(`${env.SUPABASE_SERVICE_ROLE_KEY}:email-thumb-v1`),
  );
  const key = await crypto.subtle.importKey(
    'raw', keyBytes, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign'],
  );
  const mac = await crypto.subtle.sign('HMAC', key, enc.encode(`email-thumb:${boardId}`));
  return [...new Uint8Array(mac)].map((b) => b.toString(16).padStart(2, '0')).join('').slice(0, 32);
}

// Serves a board's stored thumbnail to EMAIL CLIENTS (the welcome email embeds
// the recipient's own board). Email <img> fetches arrive unauthenticated and
// possibly weeks after send, so the gate is a permanent board-scoped HMAC in
// the URL — a session gate can't work and a 7-day signed R2 URL would die
// before many emails get opened. Body mirrors handleShareThumb, with the
// share-token gate swapped for the signature + a direct boards lookup.
async function handleEmailThumb(env, boardId, searchParams, request) {
  const fallback = () =>
    new Response(null, {
      status: 302,
      headers: { location: `${SITE_ORIGIN}/clusters-logo-dark.png`, 'cache-control': 'no-store' },
    });

  let expected = '';
  try { expected = await emailThumbSig(env, boardId); } catch { return fallback(); }
  if (!expected || searchParams.get('s') !== expected) return fallback();

  let row = null;
  try {
    const res = await fetch(
      `${env.SUPABASE_URL}/rest/v1/boards?id=eq.${boardId}&select=thumb_key,deleted_at`,
      {
        headers: {
          'apikey': env.SUPABASE_SERVICE_ROLE_KEY,
          'authorization': `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
          'accept': 'application/json',
        },
        signal: AbortSignal.timeout(5000),
      },
    );
    if (!res.ok) return fallback();
    row = (await res.json())?.[0] || null;
  } catch {
    return fallback();
  }
  if (!row || row.deleted_at) return fallback();

  const key = (row.thumb_key || '').replace(/^r2:/, '');
  if (!key || !env.IMAGES) return fallback();

  const obj = await env.IMAGES.get(key);
  if (!obj) return fallback();

  const headers = {
    'content-type': 'image/webp',
    // 1h cache like share-thumb: the v= param busts on re-render, and a short
    // TTL bounds how long a just-deleted board's thumb keeps serving bytes.
    'cache-control': 'public, max-age=3600',
    'etag': obj.httpEtag,
    'x-robots-tag': 'noindex',
  };
  if (request.headers.get('if-none-match') === obj.httpEtag) {
    return new Response(null, { status: 304, headers });
  }
  return new Response(obj.body, { status: 200, headers });
}

// Same-origin proxy for PartyKit's /reset endpoint. The browser would
// otherwise CORS-block the cross-origin POST (PartyKit's CORS headers
// work via curl but get flaky from real browsers — different deploy
// edges, cached preflight failures, etc.). Going through the worker
// avoids CORS entirely since the call is same-origin from the client's
// perspective and worker-to-PartyKit is server-to-server.
async function handleBoardReset(boardId, request) {
  if (request.method !== 'POST') {
    return new Response('Method not allowed', { status: 405 });
  }
  const auth = request.headers.get('authorization') || '';
  const token = auth.replace(/^Bearer\s+/i, '');
  if (!token) return new Response('Missing token', { status: 401 });

  const target = `https://${PARTYKIT_HOST}/parties/main/${encodeURIComponent(boardId)}/reset`;
  try {
    const res = await fetch(target, {
      method: 'POST',
      headers: {
        'authorization': `Bearer ${token}`,
        'content-type': 'application/json',
      },
      signal: AbortSignal.timeout(10_000),
    });
    const body = await res.text();
    return new Response(body, {
      status: res.status,
      headers: {
        'content-type': res.headers.get('content-type') || 'application/json',
        'cache-control': 'no-store',
      },
    });
  } catch (e) {
    return new Response(JSON.stringify({ error: String(e?.message || e) }), {
      status: 502,
      headers: { 'content-type': 'application/json', 'cache-control': 'no-store' },
    });
  }
}

async function handleOg(url, request) {
  const target = url.searchParams.get('url');
  if (!target) {
    return json({ error: 'missing url' }, 400);
  }
  let absolute;
  try {
    absolute = target.startsWith('http://') || target.startsWith('https://')
      ? target
      : `https://${target}`;
    new URL(absolute);
  } catch (_) {
    return json({ error: 'invalid url' }, 400);
  }
  try {
    const upstream = await fetch(absolute, {
      method: 'GET',
      headers: {
        'User-Agent': 'Mozilla/5.0 (compatible; SoleilClustersPreview/1.0; +https://clusters.soleilpictures.com)',
        'Accept': 'text/html,application/xhtml+xml',
        'Accept-Language': 'en-US,en;q=0.5',
      },
      redirect: 'follow',
      cf: { cacheTtl: 3600, cacheEverything: true },
      signal: AbortSignal.timeout(10_000),
    });
    if (!upstream.ok) return json({ error: `upstream ${upstream.status}` }, 502);
    const ct = upstream.headers.get('content-type') || '';
    if (!ct.includes('text/html') && !ct.includes('application/xhtml')) {
      return json({ error: 'not html' }, 415);
    }
    // Cap body size — only need the <head>. 256 KB is plenty.
    const text = await readCapped(upstream, 256 * 1024);
    const data = parseOg(text, absolute);
    return json(data, 200, true);
  } catch (e) {
    return json({ error: String(e?.message || e) }, 500);
  }
}

async function readCapped(response, maxBytes) {
  const reader = response.body.getReader();
  const chunks = [];
  let total = 0;
  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    chunks.push(value);
    total += value.length;
    if (total >= maxBytes) {
      try { reader.cancel(); } catch (_) {}
      break;
    }
  }
  return new TextDecoder('utf-8').decode(concat(chunks));
}

function concat(chunks) {
  let total = 0;
  for (const c of chunks) total += c.length;
  const out = new Uint8Array(total);
  let off = 0;
  for (const c of chunks) { out.set(c, off); off += c.length; }
  return out;
}

function decodeEntities(s) {
  if (!s) return s;
  return s
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&nbsp;/g, ' ')
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(parseInt(n, 10)))
    .trim();
}

function parseOg(html, sourceUrl) {
  // Limit search to <head> to avoid being fooled by stray meta in body.
  const headEnd = html.toLowerCase().indexOf('</head>');
  const head = headEnd >= 0 ? html.slice(0, headEnd) : html;

  const meta = (prop) => {
    const escaped = prop.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    // property="..." content="..."
    const a = head.match(new RegExp(`<meta[^>]+(?:property|name|itemprop)=["']${escaped}["'][^>]*content=["']([^"']*)["']`, 'i'));
    if (a) return decodeEntities(a[1]);
    // content="..." property="..."
    const b = head.match(new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]*(?:property|name|itemprop)=["']${escaped}["']`, 'i'));
    if (b) return decodeEntities(b[1]);
    return null;
  };

  const linkHref = (rel) => {
    const escaped = rel.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const a = head.match(new RegExp(`<link[^>]+rel=["'][^"']*${escaped}[^"']*["'][^>]*href=["']([^"']*)["']`, 'i'));
    if (a) return decodeEntities(a[1]);
    const b = head.match(new RegExp(`<link[^>]+href=["']([^"']*)["'][^>]*rel=["'][^"']*${escaped}[^"']*["']`, 'i'));
    if (b) return decodeEntities(b[1]);
    return null;
  };

  const titleTag = head.match(/<title[^>]*>([^<]*)<\/title>/i);
  const titleText = titleTag ? decodeEntities(titleTag[1]) : null;

  const abs = (rel) => {
    if (!rel) return null;
    try { return new URL(rel, sourceUrl).href; } catch (_) { return null; }
  };

  const ogImage = meta('og:image') || meta('og:image:url') || meta('og:image:secure_url') || meta('twitter:image') || meta('twitter:image:src');
  const fav = linkHref('icon') || linkHref('shortcut icon') || linkHref('apple-touch-icon') || '/favicon.ico';

  return {
    title: meta('og:title') || meta('twitter:title') || titleText,
    description: meta('og:description') || meta('twitter:description') || meta('description'),
    image: abs(ogImage),
    favicon: abs(fav),
    url: meta('og:url') || sourceUrl,
  };
}

function json(data, status = 200, cacheable = false) {
  const headers = {
    'content-type': 'application/json; charset=utf-8',
    'access-control-allow-origin': '*',
  };
  if (cacheable) {
    // 1 hour browser cache, 1 day CDN cache.
    headers['cache-control'] = 'public, max-age=3600, s-maxage=86400';
  } else {
    headers['cache-control'] = 'no-store';
  }
  return new Response(JSON.stringify(data), { status, headers });
}

// Admin-only: backfill public.images.size_bytes by HEAD-ing every R2
// object whose row has size_bytes IS NULL. Called manually from
// /admin Analytics → Storage section. Idempotent; batches of up to 500.
// Returns counts + how many rows still need backfill so the UI can loop.
async function handleBackfillImageSizes(request, env) {
  if (request.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: {
      'access-control-allow-origin':  '*',
      'access-control-allow-methods': 'POST, OPTIONS',
      'access-control-allow-headers': 'authorization, content-type',
    } });
  }
  if (request.method !== 'POST') return json({ error: 'POST only' }, 405);

  const userToken = (request.headers.get('authorization') || '').replace(/^Bearer\s+/i, '');
  if (!userToken) return json({ error: 'auth required' }, 401);

  // Validate caller is admin via the existing get_my_tier RPC. We use
  // the user's JWT so RLS / function gate runs as them.
  let tierRes;
  try {
    tierRes = await fetch(`${env.SUPABASE_URL}/rest/v1/rpc/get_my_tier`, {
      method: 'POST',
      headers: {
        apikey:        env.SUPABASE_ANON_KEY || env.SUPABASE_SERVICE_ROLE_KEY,
        authorization: `Bearer ${userToken}`,
        'content-type': 'application/json',
      },
      body: '{}',
      signal: AbortSignal.timeout(10_000),
    });
  } catch (_) {
    return json({ error: 'tier check failed' }, 502);
  }
  if (!tierRes.ok) return json({ error: 'tier check failed' }, 401);
  const tierData = await tierRes.json();
  const tier = Array.isArray(tierData) ? tierData[0]?.tier : tierData?.tier;
  if (tier !== 'admin') return json({ error: 'admin only' }, 403);

  // Service-role key authenticates the list/patch/count REST calls below. It's
  // a Worker secret (not in wrangler.toml); without it those fetches fail. Guard
  // explicitly so the UI shows the cause instead of a generic error.
  if (!env.SUPABASE_SERVICE_ROLE_KEY) {
    return json({ error: 'Worker is missing the SUPABASE_SERVICE_ROLE_KEY secret — set it on the soleil-boards Worker.' }, 500);
  }

  if (!env.IMAGES) return json({ error: 'R2 binding missing' }, 500);

  const url   = new URL(request.url);
  const limit = Math.max(1, Math.min(500, Number(url.searchParams.get('limit') || 100)));

  try {
    const result = await backfillImageSizesOnce(env, limit);
    return json({ ok: true, ...result });
  } catch (_) {
    return json({ error: 'list failed' }, 500);
  }
}

// Run an async fn over items with a bounded number in flight at once, so a few
// hundred R2 HEADs don't fire all at once (or run dead-sequentially).
async function mapLimit(items, limit, fn) {
  let i = 0;
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (i < items.length) {
      const idx = i++;
      await fn(items[idx]);
    }
  });
  await Promise.all(workers);
}

// Core of the size backfill: HEAD up to `limit` size-less R2 objects and write
// their byte size back to images.size_bytes. Shared by the admin HTTP endpoint
// and the nightly cron. Additive only (sets a metadata column; never deletes),
// idempotent, and returns how many rows still need a size so a caller can loop.
async function backfillImageSizesOnce(env, limit) {
  const listUrl =
    `${env.SUPABASE_URL}/rest/v1/images?size_bytes=is.null&deleted_at=is.null` +
    `&select=id,storage_path&limit=${limit}&order=created_at.desc`;
  const listRes = await fetch(listUrl, {
    headers: {
      apikey:        env.SUPABASE_SERVICE_ROLE_KEY,
      authorization: `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
    },
    signal: AbortSignal.timeout(10_000),
  });
  if (!listRes.ok) throw new Error('list failed');
  const rows = await listRes.json();

  let processed = 0, notFound = 0, errors = 0;
  await mapLimit(rows, 8, async (row) => {
    if (!row?.storage_path) return;
    try {
      const obj = await env.IMAGES.head(row.storage_path);
      if (!obj) { notFound++; return; }
      const upd = await fetch(
        `${env.SUPABASE_URL}/rest/v1/images?id=eq.${row.id}`,
        {
          method: 'PATCH',
          headers: {
            apikey:        env.SUPABASE_SERVICE_ROLE_KEY,
            authorization: `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
            'content-type': 'application/json',
            prefer:        'return=minimal',
          },
          body: JSON.stringify({ size_bytes: obj.size }),
          signal: AbortSignal.timeout(10_000),
        },
      );
      if (upd.ok) processed++; else errors++;
    } catch (_) { errors++; }
  });

  // Remaining count so a caller can keep looping until it hits zero.
  const remRes = await fetch(
    `${env.SUPABASE_URL}/rest/v1/images?size_bytes=is.null&deleted_at=is.null&select=id&limit=1`,
    {
      headers: {
        apikey:        env.SUPABASE_SERVICE_ROLE_KEY,
        authorization: `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
        prefer:        'count=exact',
      },
      signal: AbortSignal.timeout(10_000),
    },
  );
  const remHeader = remRes.headers.get('content-range') || '';
  const remaining = parseInt(remHeader.split('/').pop() || '0', 10) || 0;

  return { processed, not_found: notFound, errors, remaining };
}

// Nightly auto-backfill (runs from the daily cron). Drains size-less image rows
// in batches until done, until a batch makes no progress (e.g. the only rows
// left are not_found — their R2 object is gone, so they can never get a size),
// or until a per-run cap. New uploads already stamp size_bytes, so this only
// has to clear the historical backlog once and then stays at ~0. Safe to run
// live with no dry-run gate — it never deletes anything.
async function runImageSizeBackfill(env, { cap = 5000 } = {}) {
  if (!env.IMAGES || !env.SUPABASE_SERVICE_ROLE_KEY) {
    console.log('[size-backfill] skipped — missing IMAGES binding or SUPABASE_SERVICE_ROLE_KEY');
    return;
  }
  let totalProcessed = 0, totalErrors = 0, totalNotFound = 0, remaining = null, rounds = 0;
  while (totalProcessed < cap) {
    let r;
    try {
      r = await backfillImageSizesOnce(env, 200);
    } catch (e) {
      console.log(`[size-backfill] batch failed: ${e?.message || e}`);
      break;
    }
    rounds++;
    totalProcessed += r.processed;
    totalErrors    += r.errors;
    totalNotFound  += r.not_found;
    remaining = r.remaining;
    if (r.remaining === 0) break;
    if (r.processed === 0) break;   // no recoverable rows left — avoid an infinite loop
  }
  console.log(`[size-backfill] processed=${totalProcessed} errors=${totalErrors} not_found=${totalNotFound} remaining=${remaining} rounds=${rounds}`);
}
