#!/usr/bin/env node
// Regenerate src/lib/buildInfo.js with the current commit's date + short SHA.
// Runs as the `prebuild` npm hook, so both local `npm run build` and Cloudflare
// Workers Builds stamp the artifact before vite/wrangler bundle it. The Worker
// serves the stamp at /api/build-info; the SEO health check compares it against
// an expected minimum to catch "prod isn't serving what we shipped".

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, '../src/lib/buildInfo.js');

let date = new Date().toISOString().slice(0, 10);
let sha = 'unknown';
try {
  date = execSync('git log -1 --format=%cs', { cwd: HERE }).toString().trim() || date;
  sha = execSync('git log -1 --format=%h', { cwd: HERE }).toString().trim() || sha;
} catch (_) {
  // Not a git checkout (some CI tarballs) — fall back to today's date.
}

writeFileSync(OUT, `// Build stamp — REGENERATED by scripts/stamp-build.mjs (prebuild hook) with the
// current commit's date + short SHA at build time. This committed fallback only
// exists so a bare checkout compiles; 'dev' means "not a stamped build".
// Served by the Worker at /api/build-info for the SEO health/drift detector:
// "is production actually running the code we shipped?"
export const BUILD_DATE = '${date}';
export const BUILD_SHA = '${sha}';
`);
console.log(`✓ buildInfo.js stamped: ${date} @ ${sha}`);
